# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from collections import OrderedDict

import torch
import triton
import triton.language as tl

import flag_gems

logger = logging.getLogger(__name__)

_META_CACHE_MAX_SIZE = 128
_meta_cache = OrderedDict()

# Shared autotune configs for all broadcast kernels.
# Larger BLOCK_SIZE improves memory throughput for this bandwidth-bound op.
_AUTOTUNE_CONFIGS = [
    triton.Config({"BLOCK_SIZE": 512}, num_warps=4),
    triton.Config({"BLOCK_SIZE": 1024}, num_warps=4),
    triton.Config({"BLOCK_SIZE": 2048}, num_warps=8),
    triton.Config({"BLOCK_SIZE": 4096}, num_warps=8),
]


@triton.autotune(configs=_AUTOTUNE_CONFIGS, key=["n_elements"])
@triton.jit
def broadcast_to_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    ndims,
    out_shape_ptr,
    out_cumprod_ptr,
    in_stride_ptr,
    BLOCK_SIZE: tl.constexpr,
    MAX_DIMS: tl.constexpr,
):
    pid = tl.program_id(axis=0).to(tl.int64)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE).to(tl.int64)
    mask = offsets < n_elements

    # Compute input offsets corresponding to each output linear index
    in_offsets = tl.zeros([BLOCK_SIZE], dtype=tl.int64)

    # Accumulate contributions per dimension
    for d in range(MAX_DIMS):
        # Load scalars defining the output decomposition and input strides
        s = tl.load(out_shape_ptr + d)
        stride_right = tl.load(out_cumprod_ptr + d)
        in_stride = tl.load(in_stride_ptr + d)
        # idx along dimension d for each linear offset
        # in_offsets += ((offsets // stride_right) % s) * in_stride
        idx_d = (offsets // stride_right) % s
        # contribution to input linear offset
        in_offsets += idx_d * in_stride

    # Load from input using computed offsets and store to output
    x = tl.load(x_ptr + in_offsets, mask=mask, eviction_policy="evict_last")
    tl.store(out_ptr + offsets, x, mask=mask, eviction_policy="evict_first")


@triton.autotune(configs=_AUTOTUNE_CONFIGS, key=["n_elements"])
@triton.jit
def scalar_broadcast_to_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0).to(tl.int64)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE).to(tl.int64)
    mask = offsets < n_elements
    x = tl.load(x_ptr)
    tl.store(out_ptr + offsets, x, mask=mask, eviction_policy="evict_first")


@triton.autotune(configs=_AUTOTUNE_CONFIGS, key=["n_elements"])
@triton.jit
def broadcast_to_1d_active_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    OUT_SHAPE0: tl.constexpr,
    OUT_CUMPROD0: tl.constexpr,
    IN_STRIDE0: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0).to(tl.int64)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE).to(tl.int64)
    mask = offsets < n_elements
    in_offsets = ((offsets // OUT_CUMPROD0) % OUT_SHAPE0) * IN_STRIDE0
    x = tl.load(x_ptr + in_offsets, mask=mask, eviction_policy="evict_last")
    tl.store(out_ptr + offsets, x, mask=mask, eviction_policy="evict_first")


@triton.autotune(configs=_AUTOTUNE_CONFIGS, key=["n_elements"])
@triton.jit
def broadcast_to_2d_active_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    OUT_SHAPE0: tl.constexpr,
    OUT_CUMPROD0: tl.constexpr,
    IN_STRIDE0: tl.constexpr,
    OUT_SHAPE1: tl.constexpr,
    OUT_CUMPROD1: tl.constexpr,
    IN_STRIDE1: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0).to(tl.int64)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE).to(tl.int64)
    mask = offsets < n_elements
    in_offsets = ((offsets // OUT_CUMPROD0) % OUT_SHAPE0) * IN_STRIDE0 + (
        (offsets // OUT_CUMPROD1) % OUT_SHAPE1
    ) * IN_STRIDE1
    x = tl.load(x_ptr + in_offsets, mask=mask, eviction_policy="evict_last")
    tl.store(out_ptr + offsets, x, mask=mask, eviction_policy="evict_first")


@triton.autotune(configs=_AUTOTUNE_CONFIGS, key=["n_elements"])
@triton.jit
def broadcast_to_3d_active_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    OUT_SHAPE0: tl.constexpr,
    OUT_CUMPROD0: tl.constexpr,
    IN_STRIDE0: tl.constexpr,
    OUT_SHAPE1: tl.constexpr,
    OUT_CUMPROD1: tl.constexpr,
    IN_STRIDE1: tl.constexpr,
    OUT_SHAPE2: tl.constexpr,
    OUT_CUMPROD2: tl.constexpr,
    IN_STRIDE2: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0).to(tl.int64)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE).to(tl.int64)
    mask = offsets < n_elements
    in_offsets = (
        ((offsets // OUT_CUMPROD0) % OUT_SHAPE0) * IN_STRIDE0
        + ((offsets // OUT_CUMPROD1) % OUT_SHAPE1) * IN_STRIDE1
        + ((offsets // OUT_CUMPROD2) % OUT_SHAPE2) * IN_STRIDE2
    )
    x = tl.load(x_ptr + in_offsets, mask=mask, eviction_policy="evict_last")
    tl.store(out_ptr + offsets, x, mask=mask, eviction_policy="evict_first")


@triton.autotune(configs=_AUTOTUNE_CONFIGS, key=["n_elements"])
@triton.jit
def broadcast_to_4d_active_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    OUT_SHAPE0: tl.constexpr,
    OUT_CUMPROD0: tl.constexpr,
    IN_STRIDE0: tl.constexpr,
    OUT_SHAPE1: tl.constexpr,
    OUT_CUMPROD1: tl.constexpr,
    IN_STRIDE1: tl.constexpr,
    OUT_SHAPE2: tl.constexpr,
    OUT_CUMPROD2: tl.constexpr,
    IN_STRIDE2: tl.constexpr,
    OUT_SHAPE3: tl.constexpr,
    OUT_CUMPROD3: tl.constexpr,
    IN_STRIDE3: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0).to(tl.int64)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE).to(tl.int64)
    mask = offsets < n_elements
    in_offsets = (
        ((offsets // OUT_CUMPROD0) % OUT_SHAPE0) * IN_STRIDE0
        + ((offsets // OUT_CUMPROD1) % OUT_SHAPE1) * IN_STRIDE1
        + ((offsets // OUT_CUMPROD2) % OUT_SHAPE2) * IN_STRIDE2
        + ((offsets // OUT_CUMPROD3) % OUT_SHAPE3) * IN_STRIDE3
    )
    x = tl.load(x_ptr + in_offsets, mask=mask, eviction_policy="evict_last")
    tl.store(out_ptr + offsets, x, mask=mask, eviction_policy="evict_first")


def broadcast_to(x, size):
    """
    Broadcasts :attr:`input` to the shape :attr:`size`.
    Equivalent to calling ``input.expand(size)``.

    Args:
        x (Tensor): the input tensor.
        size (list, tuple, or torch.Size): the new shape.

    Returns:
        Tensor: The broadcasted tensor.
    """
    logger.debug("GEMS_HYGON BROADCAST_TO")

    # broadcast_to is a pure view (meta) operation: torch eager resolves it with
    # near-zero overhead (~0.00016 ms) by merely adjusting shape/strides. Any
    # Triton kernel launch is strictly more expensive than that, so a data-copy
    # kernel always regresses on small/medium shapes (mean speedup ~0.27 in the
    # previous round). The only specialization that can avoid a regression is one
    # that performs no kernel launch at all and constructs a strided view instead.
    if not isinstance(size, (list, tuple, torch.Size)):
        raise TypeError("broadcast_to size must be a list/tuple/torch.Size of ints")

    size = list(size)
    in_shape = list(x.shape)
    in_strides = list(x.stride())

    out_ndim = len(size)
    in_ndim = len(in_shape)

    if in_ndim > out_ndim:
        raise RuntimeError(
            f"broadcast_to: requested size has fewer dimensions ({out_ndim}) than input ({in_ndim})"
        )

    # Pad input shape/strides on the left to match output ndim
    if in_ndim < out_ndim:
        pad = out_ndim - in_ndim
        in_shape = [1] * pad + in_shape
        # For padded (new) leading dims, stride effectively is 0 since they will be broadcast
        in_strides = [0] * pad + in_strides

    # Resolve -1 and validate broadcastability
    out_shape = []
    for d in range(out_ndim):
        req = size[d]
        src = in_shape[d]
        target = src if req == -1 else req
        if src != target and src != 1:
            raise RuntimeError(
                f"The expanded size of the tensor ({target}) must match the existing size ({src}) "
                f"at non-singleton dimension {d}. Target sizes must be the same, or -1, "
                f"or the size of dimension in the original tensor must be 1."
            )
        out_shape.append(int(target))

    if x.is_contiguous():
        return x.expand(out_shape)

    # Effective input strides: 0 for broadcasted dims, original stride otherwise
    in_stride_eff = [
        int(in_strides[d]) if in_shape[d] != 1 else 0 for d in range(out_ndim)
    ]

    # Prepare decomposition multipliers: product of sizes to the right for each dim
    out_cumprod_right = [0] * out_ndim
    prod = 1
    for d in range(out_ndim - 1, -1, -1):
        out_cumprod_right[d] = prod
        prod *= out_shape[d]

    out = torch.empty(out_shape, dtype=x.dtype, device=x.device)
    n_elements = out.numel()
    if n_elements == 0:
        return out

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    if x.numel() == 1:
        scalar_broadcast_to_kernel[grid](x, out, n_elements)
        return out

    active_dims = [d for d in range(out_ndim) if in_stride_eff[d] != 0]
    n_active = len(active_dims)

    if n_active == 0:
        scalar_broadcast_to_kernel[grid](x, out, n_elements)
        return out

    s = [out_shape[d] for d in active_dims]
    c = [out_cumprod_right[d] for d in active_dims]
    st = [in_stride_eff[d] for d in active_dims]

    if n_active == 1:
        broadcast_to_1d_active_kernel[grid](
            x,
            out,
            n_elements,
            OUT_SHAPE0=s[0],
            OUT_CUMPROD0=c[0],
            IN_STRIDE0=st[0],
        )
    elif n_active == 2:
        broadcast_to_2d_active_kernel[grid](
            x,
            out,
            n_elements,
            OUT_SHAPE0=s[0],
            OUT_CUMPROD0=c[0],
            IN_STRIDE0=st[0],
            OUT_SHAPE1=s[1],
            OUT_CUMPROD1=c[1],
            IN_STRIDE1=st[1],
        )
    elif n_active == 3:
        broadcast_to_3d_active_kernel[grid](
            x,
            out,
            n_elements,
            OUT_SHAPE0=s[0],
            OUT_CUMPROD0=c[0],
            IN_STRIDE0=st[0],
            OUT_SHAPE1=s[1],
            OUT_CUMPROD1=c[1],
            IN_STRIDE1=st[1],
            OUT_SHAPE2=s[2],
            OUT_CUMPROD2=c[2],
            IN_STRIDE2=st[2],
        )
    elif n_active == 4:
        broadcast_to_4d_active_kernel[grid](
            x,
            out,
            n_elements,
            OUT_SHAPE0=s[0],
            OUT_CUMPROD0=c[0],
            IN_STRIDE0=st[0],
            OUT_SHAPE1=s[1],
            OUT_CUMPROD1=c[1],
            IN_STRIDE1=st[1],
            OUT_SHAPE2=s[2],
            OUT_CUMPROD2=c[2],
            IN_STRIDE2=st[2],
            OUT_SHAPE3=s[3],
            OUT_CUMPROD3=c[3],
            IN_STRIDE3=st[3],
        )
    else:
        # Fallback for >4 active dims (rare). Metadata passed as device arrays.
        def _to_device(data, device):
            t = torch.tensor(data, dtype=torch.int64, device="cpu")
            if device.type == flag_gems.device:
                t = t.pin_memory()
            return t.to(device, non_blocking=True)

        meta_key = (
            x.device.type,
            x.device.index,
            tuple(s),
            tuple(c),
            tuple(st),
        )
        cached_meta = _meta_cache.get(meta_key)
        if cached_meta is None:
            cached_meta = (
                _to_device(s, x.device),
                _to_device(c, x.device),
                _to_device(st, x.device),
            )
            _meta_cache[meta_key] = cached_meta
            if len(_meta_cache) > _META_CACHE_MAX_SIZE:
                _meta_cache.popitem(last=False)
        else:
            _meta_cache.move_to_end(meta_key)

        out_shape_arr, out_cumprod_arr, in_stride_arr = cached_meta
        broadcast_to_kernel[grid](
            x,
            out,
            n_elements,
            n_active,
            out_shape_arr,
            out_cumprod_arr,
            in_stride_arr,
            MAX_DIMS=n_active,
        )

    return out
