[pytest]
testpaths = tests
pythonpath = src
filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
    ignore::DeprecationWarning
    ignore:Warning only once for all operators,  other operators may also be .*:UserWarning
markers =
    median: Median operator tests
