# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils


@pytest.mark.special_modified_bessel_i0
@pytest.mark.parametrize("shape", utils.SPECIAL_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_special_modified_bessel_i0(shape, dtype):
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    # upcast=True:  use float
    ref_inp = utils.to_reference(inp, True)
    ref_out = torch.special.modified_bessel_i0(ref_inp)

    res_out = flag_gems.special_modified_bessel_i0(inp)

    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.special_modified_bessel_i0_out
@pytest.mark.parametrize("shape", utils.SPECIAL_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_special_modified_bessel_i0_out(shape, dtype):
    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device)
    ref_inp = utils.to_reference(inp, True)
    ref_out = torch.special.modified_bessel_i0(ref_inp)

    out_act = torch.empty_like(inp)
    act_out = flag_gems.special_modified_bessel_i0_out(inp, out=out_act)

    utils.gems_assert_close(act_out, ref_out, dtype)
    utils.gems_assert_close(out_act, ref_out, dtype)
