# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils
from . import conftest as cfg

# Per-channel fake quantization backward always operates in float32; scale and
# zero_point are 1-D and sized along the quantization axis. We use moderate
# channel counts to keep the saturation / in-range coverage representative.
if cfg.QUICK_MODE:
    # Minimal per-channel shapes for quick smoke runs.
    PER_CHANNEL_SHAPES = [
        (4, 8),
        (16, 64),
    ]
else:
    # Moderate channel counts to keep saturation / in-range coverage representative.
    PER_CHANNEL_SHAPES = [
        (8,),
        (4, 16),
        (16, 64),
        (20, 32, 15),
        (16, 128, 64, 60),
    ]

AXIS_LIST = [0, 1] if cfg.QUICK_MODE else [0, 1, 2]
QUANT_RANGES = [(-128, 127), (0, 255), (-7, 7)]
GRAD_FACTORS = [1.0] if cfg.QUICK_MODE else [1.0, 0.5, 2.0]
# The aten op schema fixes all tensors to float32; no other dtypes are valid.
DTYPES = [torch.float32]

# The op is only exposed via the aten namespace (not as a top-level torch attr).
_ATEN_OP = torch.ops.aten._fake_quantize_learnable_per_channel_affine_backward


def _gen_inputs(shape, axis, dtype, quant_max, sat_factor, grad_factor):
    # Magnify so that some channels saturate (xqi outside [quant_min, quant_max])
    # while others stay in range.
    numel_along = shape[axis]
    scale = (
        torch.rand(numel_along, dtype=torch.float32, device=flag_gems.device) * 0.4
        + 0.05
    )
    # zero_point in float; reference rounds & clamps it.
    zero_point = torch.rand(
        numel_along, dtype=torch.float32, device=flag_gems.device
    ) * (quant_max * 0.5)
    self_t = (
        torch.randn(shape, dtype=torch.float32, device=flag_gems.device) * sat_factor
    )
    grad = torch.randn(shape, dtype=torch.float32, device=flag_gems.device)
    return grad, self_t, scale, zero_point


@pytest.mark.fake_quantize_learnable_per_channel_affine_backward
@pytest.mark.parametrize("shape", PER_CHANNEL_SHAPES)
@pytest.mark.parametrize("axis", AXIS_LIST)
@pytest.mark.parametrize("qrange", QUANT_RANGES)
@pytest.mark.parametrize("grad_factor", GRAD_FACTORS)
def test_fake_quantize_learnable_per_channel_affine_backward(
    shape, axis, qrange, grad_factor
):
    if axis >= len(shape):
        pytest.skip("axis out of range for this shape")
    quant_min, quant_max = qrange
    # Seed the generator so the random inputs are deterministic across runs
    # (the per-test param values otherwise inherit global RNG state, which made
    # a few saturation-heavy channels cross the float32 accumulation tolerance
    # nondeterministically).
    torch.manual_seed(1234)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(1234)
    # sat_factor scales the input so some quantized values fall outside the range.
    sat_factor = float(quant_max) * 0.05
    grad, self_t, scale, zero_point = _gen_inputs(
        shape, axis, torch.float32, quant_max, sat_factor, grad_factor
    )

    ref_grad = utils.to_reference(grad)
    ref_self = utils.to_reference(self_t)
    ref_scale = utils.to_reference(scale)
    ref_zp = utils.to_reference(zero_point)

    ref_out = _ATEN_OP(
        ref_grad,
        ref_self,
        ref_scale,
        ref_zp,
        axis,
        quant_min,
        quant_max,
        grad_factor,
    )
    res_out = flag_gems._fake_quantize_learnable_per_channel_affine_backward(
        grad,
        self_t,
        scale,
        zero_point,
        axis,
        quant_min,
        quant_max,
        grad_factor,
    )

    assert len(res_out) == 3
    # dX is a plain elementwise map (no reduction); tight tolerance is fine.
    # dScale / dZeroPoint are reductions over all non-axis dims (potentially many
    # elements), so compare with a reduce_dim proportional to the accumulated
    # count to allow for float32 accumulation differences.
    reduce_size = 1
    for i, s in enumerate(shape):
        if i != axis:
            reduce_size *= s
    for name, res, ref in zip(("dX", "dScale", "dZeroPoint"), res_out, ref_out):
        rdim = 1 if name == "dX" else reduce_size
        utils.gems_assert_close(res, ref, torch.float32, reduce_dim=rdim)


@pytest.mark.skipif(
    cfg.TO_CPU, reason="CPU reference diverges on inf/-inf saturation gradients"
)
@pytest.mark.fake_quantize_learnable_per_channel_affine_backward
def test_fake_quantize_learnable_per_channel_affine_backward_extreme():
    """Cover extreme inputs: all-zero and inf/-inf entries that saturate."""
    # Small fixed shape keeps the extreme-input test fast and deterministic.
    shape = (4, 16)
    axis = 1
    quant_min, quant_max = -128, 127
    grad_factor = 1.0
    torch.manual_seed(1234)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(1234)
    scale = torch.full((16,), 0.1, dtype=torch.float32, device=flag_gems.device)
    zero_point = torch.zeros(16, dtype=torch.float32, device=flag_gems.device)
    self_t = torch.zeros(shape, dtype=torch.float32, device=flag_gems.device)
    # Inject inf so xqi saturates to quant_max (or -inf to quant_min).
    self_t[:, 0] = float("inf")
    self_t[:, 1] = float("-inf")
    grad = torch.randn(shape, dtype=torch.float32, device=flag_gems.device)

    ref_grad = utils.to_reference(grad)
    ref_self = utils.to_reference(self_t)
    ref_scale = utils.to_reference(scale)
    ref_zp = utils.to_reference(zero_point)

    ref_out = _ATEN_OP(
        ref_grad, ref_self, ref_scale, ref_zp, axis, quant_min, quant_max, grad_factor
    )
    res_out = flag_gems._fake_quantize_learnable_per_channel_affine_backward(
        grad, self_t, scale, zero_point, axis, quant_min, quant_max, grad_factor
    )
    reduce_size = 1
    for i, s in enumerate(shape):
        if i != axis:
            reduce_size *= s
    for name, res, ref in zip(("dX", "dScale", "dZeroPoint"), res_out, ref_out):
        rdim = 1 if name == "dX" else reduce_size
        utils.gems_assert_close(
            res, ref, torch.float32, reduce_dim=rdim, equal_nan=True
        )
