# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils


@pytest.mark.igamma
@pytest.mark.parametrize("shape", utils.POINTWISE_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_igamma(shape, dtype):
    # Ensure positive inputs for igamma (lower incomplete gamma function)
    inp1 = torch.rand(shape, dtype=dtype, device=flag_gems.device) + 0.1
    inp2 = torch.rand(shape, dtype=dtype, device=flag_gems.device) + 0.1

    ref_inp1 = utils.to_reference(inp1, True)
    ref_inp2 = utils.to_reference(inp2, True)

    ref_out = torch.igamma(ref_inp1, ref_inp2)
    res_out = flag_gems.igamma(inp1, inp2)

    utils.gems_assert_close(res_out, ref_out, dtype, equal_nan=True)
