# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils
from . import conftest as cfg

# Custom shapes: (N, H, W)
if cfg.QUICK_MODE:
    AFFINE_GRID_SHAPES = [
        (1, 2, 2),
    ]
else:
    AFFINE_GRID_SHAPES = [
        (1, 2, 2),
        (1, 4, 4),
        (2, 8, 8),
        (4, 16, 16),
        (1, 32, 32),
        (2, 64, 64),
    ]


@pytest.mark.affine_grid_generator
@pytest.mark.parametrize("shape", AFFINE_GRID_SHAPES)
# affine_grid kernel uses float32 internally; Half precision causes mismatch
@pytest.mark.parametrize("dtype", [torch.float32])
@pytest.mark.parametrize("align_corners", [False, True])
def test_affine_grid_generator(shape, dtype, align_corners):
    N, H, W = shape
    theta = torch.randn((N, 2, 3), dtype=dtype, device=flag_gems.device)
    size = [N, 3, H, W]

    ref_theta = utils.to_reference(theta)

    ref_out = torch.affine_grid_generator(ref_theta, size, align_corners)
    with flag_gems.use_gems():
        res_out = torch.affine_grid_generator(theta, size, align_corners)

    utils.gems_assert_close(res_out, ref_out, dtype)
