# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import os

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# NOTE: This test does not use flag_gems.use_gems() because it compares
# torch.cudnn_convolution_transpose across different devices to verify
# cuDNN device compatibility. The FlagGems wrapper delegates to the
# same underlying torch.cudnn_convolution_transpose call.

SHAPE_CONV_TRANSPOSE2D = [
    ((1, 2, 5, 5), (2, 2, 3, 3)),
    ((2, 3, 9, 9), (3, 1, 3, 3)),
    ((32, 8, 8, 8), (8, 8, 2, 2)),
]


@pytest.mark.cudnn_convolution_transpose
@pytest.mark.parametrize("shape, kernel", SHAPE_CONV_TRANSPOSE2D)
@pytest.mark.parametrize("stride", [1, 2])
@pytest.mark.parametrize("padding", [0, 1])
# NOTE: torch.cudnn_convolution_transpose only supports float16 and float32, not bfloat16
@pytest.mark.parametrize("dtype", [torch.float16, torch.float32])
@pytest.mark.parametrize("dilation", [1])
@pytest.mark.parametrize("groups", [1])
def test_cudnn_convolution_transpose(
    shape, kernel, stride, padding, dtype, dilation, groups
):
    if flag_gems.vendor_name == "mthreads" and dtype == torch.float16:
        os.environ["MUSA_ENABLE_SQMMA"] = "1"

    inp = torch.randn(shape, dtype=dtype, device=flag_gems.device, requires_grad=False)
    ref_inp = utils.to_reference(inp, True)
    torch.backends.cudnn.allow_tf32 = False
    weight = torch.randn(
        kernel, dtype=dtype, device=flag_gems.device, requires_grad=False
    )
    ref_weight = utils.to_reference(weight, True)

    # Compute output padding based on stride and padding
    output_padding_h = (
        (stride - 1) * shape[2] - 2 * padding + dilation * (kernel[2] - 1)
    )
    output_padding_w = (
        (stride - 1) * shape[3] - 2 * padding + dilation * (kernel[3] - 1)
    )
    # Make sure output size is same as input for testing
    output_padding = (output_padding_h % stride, output_padding_w % stride)

    ref_out = torch.cudnn_convolution_transpose(
        ref_inp,
        ref_weight,
        padding=(padding, padding),
        output_padding=output_padding,
        stride=(stride, stride),
        dilation=(dilation, dilation),
        groups=groups,
        benchmark=False,
        deterministic=False,
        allow_tf32=False,
    ).to(dtype)

    res_out = torch.cudnn_convolution_transpose(
        inp,
        weight,
        padding=(padding, padding),
        output_padding=output_padding,
        stride=(stride, stride),
        dilation=(dilation, dilation),
        groups=groups,
        benchmark=False,
        deterministic=False,
        allow_tf32=False,
    )

    utils.gems_assert_close(res_out, ref_out, dtype)
