# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# Shapes: (seq_len, batch_size, input_size, hidden_size)
QUANTIZED_LSTM_SHAPES = [
    (4, 1, 64, 64),
    (8, 16, 128, 128),
    (8, 32, 256, 256),
    (4, 64, 256, 256),
    (4, 64, 512, 512),
]


def _make_cell_params(input_size, hidden_size, has_biases, device, dtype):
    """Build one layer of quantized LSTM params plus their dequantized form.

    aten::quantized_lstm.input takes CellParamsBase script objects holding
    prepacked int8 weights. Those are CPU-only, so they are built on CPU and
    the dequantized copies are returned alongside for the device-side
    reference computation.
    """
    w_ih = torch.randn(4 * hidden_size, input_size) * 0.3
    w_hh = torch.randn(4 * hidden_size, hidden_size) * 0.3
    b_ih = torch.randn(4 * hidden_size) * 0.1
    b_hh = torch.randn(4 * hidden_size) * 0.1

    q_ih = torch.quantize_per_tensor(
        w_ih, w_ih.abs().max().item() / 127, 0, torch.qint8
    )
    q_hh = torch.quantize_per_tensor(
        w_hh, w_hh.abs().max().item() / 127, 0, torch.qint8
    )
    packed_ih = torch.ops.quantized.linear_prepack(q_ih, b_ih)
    packed_hh = torch.ops.quantized.linear_prepack(q_hh, b_hh)
    cell_params = torch.ops.quantized.make_quantized_cell_params_dynamic(
        packed_ih, packed_hh, b_ih, b_hh, True
    )

    # Reading the weights back through linear_unpack gives exactly the values
    # the kernel consumes, so the reference sees the same int8 rounding.
    deq_ih = torch.ops.quantized.linear_unpack(packed_ih)[0].dequantize()
    deq_hh = torch.ops.quantized.linear_unpack(packed_hh)[0].dequantize()

    ref = {
        "w_ih": deq_ih.to(device=device, dtype=dtype),
        "w_hh": deq_hh.to(device=device, dtype=dtype),
        "b_ih": b_ih.to(device=device, dtype=dtype) if has_biases else None,
        "b_hh": b_hh.to(device=device, dtype=dtype) if has_biases else None,
    }
    return cell_params, ref


def _reference_lstm(x, h0, c0, layer_refs, num_layers, bidirectional):
    """Sequential LSTM reference over the dequantized weights.

    Runs in the caller's dtype on device, mirroring the kernel's math so the
    comparison isolates the kernel rather than re-measuring quantization error.
    """
    num_directions = 2 if bidirectional else 1
    layer_input = x
    h_final = []
    c_final = []

    for layer in range(num_layers):
        dir_outputs = []
        for direction in range(num_directions):
            idx = layer * num_directions + direction
            ref = layer_refs[idx]
            h, c = h0[idx], c0[idx]
            seq_len = layer_input.shape[0]
            steps = range(seq_len - 1, -1, -1) if direction == 1 else range(seq_len)
            outs = [None] * seq_len

            for t in steps:
                gates = layer_input[t] @ ref["w_ih"].T + h @ ref["w_hh"].T
                if ref["b_ih"] is not None:
                    gates = gates + ref["b_ih"] + ref["b_hh"]
                g_i, g_f, g_g, g_o = gates.chunk(4, dim=1)
                c = torch.sigmoid(g_f) * c + torch.sigmoid(g_i) * torch.tanh(g_g)
                h = torch.sigmoid(g_o) * torch.tanh(c)
                outs[t] = h

            dir_outputs.append(torch.stack(outs))
            h_final.append(h)
            c_final.append(c)

        layer_input = (
            dir_outputs[0] if num_directions == 1 else torch.cat(dir_outputs, dim=-1)
        )

    return layer_input, torch.stack(h_final), torch.stack(c_final)


def _tolerance(dtype, seq_len):
    """Tolerance for a recurrence of the given depth.

    Every timestep rounds its state to the input dtype before feeding it into
    the next one, so the mantissa loss compounds along the sequence and grows
    with hidden_size. float32 keeps a strict bound; float16 and bfloat16 are
    scaled by their mantissa width and by how many steps the error travels
    through. Measured worst cases over these shapes are 5e-6 (float32),
    8e-3 (float16) and 7e-2 (bfloat16).
    """
    if dtype == torch.float32:
        return 1e-3
    if dtype == torch.float16:
        return 2e-3 * seq_len
    return 1.6e-2 * seq_len


@pytest.mark.quantized_lstm
@pytest.mark.parametrize("shape", QUANTIZED_LSTM_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_accuracy_quantized_lstm(shape, dtype):
    """Single-layer unidirectional quantized_lstm."""
    seq_len, batch_size, input_size, hidden_size = shape
    torch.manual_seed(42)
    torch.cuda.manual_seed(42)
    torch.backends.quantized.engine = "fbgemm"

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device="cuda")
    h0 = torch.randn(1, batch_size, hidden_size, dtype=dtype, device="cuda") * 0.1
    c0 = torch.randn(1, batch_size, hidden_size, dtype=dtype, device="cuda") * 0.1

    cell_params, layer_ref = _make_cell_params(
        input_size, hidden_size, True, "cuda", dtype
    )

    # The kernel accumulates in fp32 regardless of input dtype, so the
    # reference is upcast to keep a single strict tolerance meaningful.
    ref_inp = utils.to_reference(inp, upcast=True)
    ref_h0 = utils.to_reference(h0, upcast=True)
    ref_c0 = utils.to_reference(c0, upcast=True)
    ref_layer = {
        k: utils.to_reference(v, upcast=True) if v is not None else None
        for k, v in layer_ref.items()
    }

    ref_out, ref_hn, ref_cn = _reference_lstm(
        ref_inp, ref_h0, ref_c0, [ref_layer], 1, False
    )

    with flag_gems.use_gems():
        res_out, res_hn, res_cn = flag_gems.quantized_lstm(
            inp, [h0, c0], [cell_params], True, 1, 0.0, False, False, False
        )

    atol = _tolerance(dtype, seq_len)
    utils.gems_assert_close(res_out, ref_out, dtype, atol=atol)
    utils.gems_assert_close(res_hn, ref_hn, dtype, atol=atol)
    utils.gems_assert_close(res_cn, ref_cn, dtype, atol=atol)


@pytest.mark.quantized_lstm
@pytest.mark.parametrize("shape", QUANTIZED_LSTM_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_accuracy_quantized_lstm_bidirectional(shape, dtype):
    """Bidirectional quantized_lstm, covering the reversed-direction path."""
    seq_len, batch_size, input_size, hidden_size = shape
    torch.manual_seed(42)
    torch.cuda.manual_seed(42)
    torch.backends.quantized.engine = "fbgemm"

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device="cuda")
    h0 = torch.randn(2, batch_size, hidden_size, dtype=dtype, device="cuda") * 0.1
    c0 = torch.randn(2, batch_size, hidden_size, dtype=dtype, device="cuda") * 0.1

    params = []
    layer_refs = []
    for _ in range(2):
        cell_params, layer_ref = _make_cell_params(
            input_size, hidden_size, True, "cuda", dtype
        )
        params.append(cell_params)
        layer_refs.append(layer_ref)

    ref_inp = utils.to_reference(inp, upcast=True)
    ref_h0 = utils.to_reference(h0, upcast=True)
    ref_c0 = utils.to_reference(c0, upcast=True)
    ref_layers = [
        {
            k: utils.to_reference(v, upcast=True) if v is not None else None
            for k, v in layer_ref.items()
        }
        for layer_ref in layer_refs
    ]

    ref_out, ref_hn, ref_cn = _reference_lstm(
        ref_inp, ref_h0, ref_c0, ref_layers, 1, True
    )

    with flag_gems.use_gems():
        res_out, res_hn, res_cn = flag_gems.quantized_lstm(
            inp, [h0, c0], params, True, 1, 0.0, False, True, False
        )

    atol = _tolerance(dtype, seq_len)
    utils.gems_assert_close(res_out, ref_out, dtype, atol=atol)
    utils.gems_assert_close(res_hn, ref_hn, dtype, atol=atol)
    utils.gems_assert_close(res_cn, ref_cn, dtype, atol=atol)


@pytest.mark.quantized_lstm
@pytest.mark.parametrize("shape", QUANTIZED_LSTM_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_accuracy_quantized_lstm_no_bias(shape, dtype):
    """quantized_lstm with has_biases disabled."""
    seq_len, batch_size, input_size, hidden_size = shape
    torch.manual_seed(42)
    torch.cuda.manual_seed(42)
    torch.backends.quantized.engine = "fbgemm"

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device="cuda")
    h0 = torch.randn(1, batch_size, hidden_size, dtype=dtype, device="cuda") * 0.1
    c0 = torch.randn(1, batch_size, hidden_size, dtype=dtype, device="cuda") * 0.1

    cell_params, layer_ref = _make_cell_params(
        input_size, hidden_size, False, "cuda", dtype
    )

    ref_inp = utils.to_reference(inp, upcast=True)
    ref_h0 = utils.to_reference(h0, upcast=True)
    ref_c0 = utils.to_reference(c0, upcast=True)
    ref_layer = {
        k: utils.to_reference(v, upcast=True) if v is not None else None
        for k, v in layer_ref.items()
    }

    ref_out, ref_hn, ref_cn = _reference_lstm(
        ref_inp, ref_h0, ref_c0, [ref_layer], 1, False
    )

    with flag_gems.use_gems():
        res_out, res_hn, res_cn = flag_gems.quantized_lstm(
            inp, [h0, c0], [cell_params], False, 1, 0.0, False, False, False
        )

    atol = _tolerance(dtype, seq_len)
    utils.gems_assert_close(res_out, ref_out, dtype, atol=atol)
    utils.gems_assert_close(res_hn, ref_hn, dtype, atol=atol)
    utils.gems_assert_close(res_cn, ref_cn, dtype, atol=atol)
