# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

import flag_gems

logger = logging.getLogger(__name__)


@triton.jit
def broadcast_to_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    ndims,
    out_shape_ptr,
    out_cumprod_ptr,
    in_stride_ptr,
    BLOCK_SIZE: tl.constexpr,
    MAX_DIMS: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    # Compute input offsets corresponding to each output linear index
    in_offsets = tl.zeros([BLOCK_SIZE], dtype=tl.int64)

    # Accumulate contributions per dimension
    for d in range(MAX_DIMS):
        # Load scalars defining the output decomposition and input strides
        s = tl.load(out_shape_ptr + d)
        stride_right = tl.load(out_cumprod_ptr + d)
        in_stride = tl.load(in_stride_ptr + d)
        # idx along dimension d for each linear offset
        idx_d = (offsets // stride_right) % s
        # contribution to input linear offset
        in_offsets += idx_d * in_stride

    # Load from input using computed offsets and store to output
    x = tl.load(x_ptr + in_offsets, mask=mask)
    tl.store(out_ptr + offsets, x, mask=mask)


def broadcast_to(x, size):
    """
    Broadcasts :attr:`input` to the shape :attr:`size`.
    Equivalent to calling ``input.expand(size)``.

    Args:
        x (Tensor): the input tensor.
        size (list, tuple, or torch.Size): the new shape.

    Returns:
        Tensor: The broadcasted tensor.
    """
    logger.debug("GEMS_ENFLAME BROADCAST_TO")

    if not isinstance(size, (list, tuple, torch.Size)):
        raise TypeError("broadcast_to size must be a list/tuple/torch.Size of ints")

    size = list(size)
    in_shape = list(x.shape)
    in_strides = list(x.stride())

    out_ndim = len(size)
    in_ndim = len(in_shape)

    if in_ndim > out_ndim:
        raise RuntimeError(
            f"broadcast_to: requested size has fewer dimensions ({out_ndim}) than input ({in_ndim})"
        )

    # Pad input shape/strides on the left to match output ndim
    if in_ndim < out_ndim:
        pad = out_ndim - in_ndim
        in_shape = [1] * pad + in_shape
        # For padded (new) leading dims, stride effectively is 0 since they will be broadcast
        in_strides = [0] * pad + in_strides

    # Resolve -1 and validate broadcastability
    out_shape = []
    for d in range(out_ndim):
        req = size[d]
        src = in_shape[d]
        if req == -1:
            target = src
        else:
            target = req
        if src != target and src != 1:
            raise RuntimeError(
                f"The expanded size of the tensor ({target}) must match the existing size ({src}) "
                f"at non-singleton dimension {d}. Target sizes must be the same, or -1, "
                f"or the size of dimension in the original tensor must be 1."
            )
        out_shape.append(int(target))

    # Check if no broadcast is needed
    if in_shape == out_shape:
        return x.expand(size)

    # Effective input strides: 0 for broadcasted dims, original stride otherwise
    in_stride_eff = [
        int(in_strides[d]) if in_shape[d] != 1 else 0 for d in range(out_ndim)
    ]

    # Prepare decomposition multipliers: product of sizes to the right for each dim
    out_cumprod_right = [0] * out_ndim
    prod = 1
    for d in range(out_ndim - 1, -1, -1):
        out_cumprod_right[d] = prod
        prod *= out_shape[d]

    # Allocate output
    out = torch.empty(out_shape, dtype=x.dtype, device=x.device)

    n_elements = out.numel()
    if n_elements == 0:
        return out

    # Triton kernel parameters
    BLOCK_SIZE = 1024
    if n_elements // BLOCK_SIZE > 48:
        BLOCK_SIZE = 16384
    if n_elements // BLOCK_SIZE > 48:
        BLOCK_SIZE = 16384 * 2
    MAX_DIMS = max(out_ndim, 1)  # at least 1
    # Round up MAX_DIMS to a reasonable static upper bound for compilation (e.g., 16)
    STATIC_MAX = 16
    if MAX_DIMS > STATIC_MAX:
        STATIC_MAX = MAX_DIMS

    # Create device arrays for shapes/strides with padding for MAX_DIMS
    pad_len = STATIC_MAX - out_ndim

    # torch.tensor(..., device=cuda) first allocates on CPU then copies to CUDA.
    # This implicit unpinned CPU->CUDA copy is illegal during CUDA graph capture
    # (triggered by models with attention_bias=True or mlp_bias=True that route
    # through addmm -> broadcast_to).
    # Fix: allocate on CPU with pin_memory=True, then transfer non-blocking.
    # The device.type guard avoids calling pin_memory() on CPU-only tensors.

    def _to_device(data, device):
        t = torch.tensor(data, dtype=torch.int64, device="cpu")
        if device.type == flag_gems.device:
            t = t.pin_memory()
        return t.to(device, non_blocking=True)

    out_shape_arr = _to_device(out_shape + [1] * pad_len, x.device)
    out_cumprod_arr = _to_device(out_cumprod_right + [1] * pad_len, x.device)
    in_stride_arr = _to_device(in_stride_eff + [0] * pad_len, x.device)

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    broadcast_to_kernel[grid](
        x,
        out,
        n_elements,
        out_ndim,
        out_shape_arr,
        out_cumprod_arr,
        in_stride_arr,
        BLOCK_SIZE=BLOCK_SIZE,
        MAX_DIMS=STATIC_MAX,
    )
    return out
