# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@triton.jit
def prev_multiple_of(a, b):
    return tl.cdiv(a, b) * b - b


@libentry()
@triton.jit(do_not_specialize=["eps"])
def add_rms_norm_kernel(
    out_ptr,
    in_ptr1,
    in_ptr2,
    w_ptr,
    y_stride_r,
    y_stride_c,
    x1_stride_r,
    x1_stride_c,
    x2_stride_r,
    x2_stride_c,
    N,
    eps,
    BLOCK_SIZE: tl.constexpr,
):
    if tl.constexpr(in_ptr1.dtype.element_ty == tl.float16) or tl.constexpr(
        in_ptr1.dtype.element_ty == tl.bfloat16
    ):
        cdtype = tl.float32
    else:
        cdtype = in_ptr1.dtype.element_ty

    pid = tl.program_id(0)
    out_ptr += pid * y_stride_r
    in_ptr1 += pid * x1_stride_r
    in_ptr2 += pid * x2_stride_r

    mask = tl.arange(0, BLOCK_SIZE) < N
    cols = tl.arange(0, BLOCK_SIZE)
    x1 = tl.load(in_ptr1 + cols * x1_stride_c, mask, other=0.0).to(cdtype)
    x2 = tl.load(in_ptr2 + cols * x2_stride_c, mask, other=0.0).to(cdtype)

    # Add the two inputs
    x = x1 + x2

    var = tl.sum(x * x, axis=0) / N
    rrms = 1 / tl.sqrt(var + eps)

    w = tl.load(w_ptr + tl.arange(0, BLOCK_SIZE), mask=mask, other=0.0)
    y = (x * rrms * w).to(cdtype)
    tl.store(out_ptr + cols * y_stride_c, y, mask=mask)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("add_rms_norm_loop"),
    key=["N"],
)
@triton.jit(do_not_specialize=["eps"])
def add_rms_norm_loop_kernel(
    out_ptr,
    in_ptr1,
    in_ptr2,
    w_ptr,
    N,
    eps,
    TILE_N: tl.constexpr,
):
    if tl.constexpr(in_ptr1.dtype.element_ty == tl.float16) or tl.constexpr(
        in_ptr1.dtype.element_ty == tl.bfloat16
    ):
        cdtype = tl.float32
    else:
        cdtype = in_ptr1.dtype.element_ty

    pid = tle.program_id(0)

    # Pass 1: compute sum(x^2) in chunks
    acc = tl.zeros((TILE_N,), dtype=tl.float32)
    num_steps = tl.cdiv(N, TILE_N)

    for step in range(0, num_steps - 1):
        start_n = step * TILE_N
        n_offsets = start_n + tl.arange(0, TILE_N)
        x1 = tl.load(in_ptr1 + pid * N + n_offsets).to(tl.float32)
        x2 = tl.load(in_ptr2 + pid * N + n_offsets).to(tl.float32)
        x = x1 + x2
        acc += x * x

    # last step with mask
    start_n = (num_steps - 1) * TILE_N
    n_offsets = start_n + tl.arange(0, TILE_N)
    mask = n_offsets < N
    x1 = tl.load(in_ptr1 + pid * N + n_offsets, mask=mask, other=0.0).to(tl.float32)
    x2 = tl.load(in_ptr2 + pid * N + n_offsets, mask=mask, other=0.0).to(tl.float32)
    x = x1 + x2
    acc += x * x

    var = tl.sum(acc) / N
    rrms = 1 / tl.sqrt(var + eps)

    # Pass 2: normalize in reverse order (better L2 cache reuse)
    prev_multiple = prev_multiple_of(N, TILE_N)

    # first reverse step with mask
    for start_n in range(0, TILE_N, TILE_N):
        n_offsets = (prev_multiple - start_n) + tl.arange(0, TILE_N)
        mask = n_offsets < N
        x1 = tl.load(
            in_ptr1 + pid * N + n_offsets,
            mask=mask,
            other=0.0,
            eviction_policy="evict_first",
        ).to(cdtype)
        x2 = tl.load(
            in_ptr2 + pid * N + n_offsets,
            mask=mask,
            other=0.0,
            eviction_policy="evict_first",
        ).to(cdtype)
        x = x1 + x2
        w = tl.load(w_ptr + n_offsets, mask=mask, other=0.0)
        y = (x * rrms * w).to(cdtype)
        tl.store(out_ptr + pid * N + n_offsets, y, mask=mask)

    for start_n in range(TILE_N, N, TILE_N):
        n_offsets = (prev_multiple - start_n) + tl.arange(0, TILE_N)
        x1 = tl.load(
            in_ptr1 + pid * N + n_offsets,
            eviction_policy="evict_first",
        ).to(cdtype)
        x2 = tl.load(
            in_ptr2 + pid * N + n_offsets,
            eviction_policy="evict_first",
        ).to(cdtype)
        x = x1 + x2
        w = tl.load(w_ptr + n_offsets)
        y = (x * rrms * w).to(cdtype)
        tl.store(out_ptr + pid * N + n_offsets, y)


def add_rms_norm(x1, x2, normalized_shape, weight, eps=1e-5):
    """
    Add_RMSNorm: Add two inputs element-wise and apply RMS normalization.

    Args:
        x1: First input tensor
        x2: Second input tensor
        normalized_shape: Shape to normalize over (typically the last dimensions)
        weight: Optional weight tensor for the normalization
        eps: Epsilon value for numerical stability

    Returns:
        Normalized output tensor
    """
    logger.debug(
        "GEMS ADD_RMS_NORM FORWARD, [input1 shape]: %s, [input2 shape]: %s, [weight shape]: %s",
        x1.size(),
        x2.size(),
        weight.size() if weight is not None else None,
    )
    dim = x1.ndim - len(normalized_shape)
    M = math.prod(x1.shape[:dim])
    N = math.prod(normalized_shape)

    # Verify shapes match
    assert x1.shape == x2.shape, f"Input shapes must match: {x1.shape} vs {x2.shape}"

    x1 = x1.contiguous()
    x2 = x2.contiguous()
    weight = weight.contiguous()
    y = torch.empty_like(x1)

    with torch_device_fn.device(x1.device):
        if N <= 4096:
            BLOCK_SIZE = triton.next_power_of_2(N)
            add_rms_norm_kernel[M,](
                y, x1, x2, weight, N, 1, N, 1, N, 1, N, eps, BLOCK_SIZE
            )
        else:
            add_rms_norm_loop_kernel[M,](y, x1, x2, weight, N, eps)

    return y
