#!/usr/bin/env python

import argparse
import json
import sys
from pathlib import Path

DTYPE_MAP = {
    "torch.float16": "fp16",
    "torch.float32": "fp32",
    "torch.bfloat16": "bf16",
    "torch.complex64": "cf64",
    "torch.int16": "int16",
    "torch.int32": "int32",
    "torch.int8": "int8",
    "torch.uint8": "uint8",
    "torch.int64": "int64",
    "torch.bool": "bool",
    "torch.float8_e4m3fn": "f8-e4m3fn",
    "torch.float8_e5m2": "f8-e5m2",
}
DATA = {}
DEBUG = False
DATA_DIR = None
ARGS = argparse.Namespace()


def load_data(data_path):
    try:
        with data_path.open("r") as f:
            data = json.load(f)
        return data, True
    except Exception as ex:
        print(f"Failed to load data: {ex}")
    return {}, False


def format_record(fields):
    if ARGS.format == "csv":
        return ",".join(fields)

    # markdown
    line = " | ".join(fields)
    return f"| {line} |"


def parse_env():
    if ARGS.compare:
        env = DATA["before"].get("env", {})
    else:
        env = DATA.get("env", {})

    arch = env.get("architecture", "?")
    os = env.get("os_name", "") + " " + env.get("os_release", "")
    pyver = env.get("python", "?")
    torch_obj = env.get("torch", {})
    torch_ver = torch_obj.get("version", "?")
    flagtree_ver = env.get("flagtree", "?")
    triton_ver = env.get("triton", {}).get("version", "?")
    flaggems_vendor = env.get("flag_gems", {}).get("vendor", "?")
    flaggems_device = env.get("flag_gems", {}).get("device", "?")
    if ARGS.compare:
        ts1 = DATA["before"].get("timestamp", "?")
        ts2 = DATA["after"].get("timestamp", "?")
        timestamp = f"{ts1} -> {ts2}"
        env1 = env
        env2 = DATA["after"].get("env", {})
        ver1 = env1.get("flag_gems", {}).get("version", "?")
        ver2 = env2.get("flag_gems", {}).get("version", "?")
        flaggems_ver = f"{ver1} -> {ver2}"
    else:
        timestamp = DATA.get("timestamp", "?")
        flaggems_ver = env.get("flag_gems", {}).get("version", "?")

    lines = []
    if ARGS.format == "markdown":
        lines.append("### Test Environment")
        lines.append("")
        lines.append("| Env | Setting | Env | Setting |")
        lines.append("| --- | ------- | ----| --------|")
        lines.append(f"| **Time** | `{timestamp}` | **FlagGems** | `{flaggems_ver}` |")
        lines.append(f"| **Arch** | `{arch}` | **OS** | `{os}` |")
        lines.append(f"| **Python** | `{pyver}` | **Torch** | `{torch_ver}` |")
        lines.append(
            f"| **FlagTree** | `{flagtree_ver}` | **Triton** | `{triton_ver}` |"
        )
        lines.append(
            f"| **Vendor** | `{flaggems_vendor}`| **Device** | `{flaggems_device}` |"
        )
        lines.append("")

    return lines


def parse_single_accuracy_details(details, kind, case):
    lines = []
    lines.append(f"#### {kind.title()} Cases {case}")
    lines.append("")

    for reason, cases in details.get(kind, {}).items():
        reason_strs = reason.split("\n")
        lines.append("- **Reason**")
        lines.append("")
        for s in reason_strs:
            lines.append(f"  > {s}")
        lines.append("")
        lines.append("  **Test cases**")
        lines.append("")
        for case in cases:
            lines.append(f"  - `{case}`")
        lines.append("")

    return lines


def parse_single_accuracy():
    def _compose_summary(op_data):
        s = op_data.get("status", "?")
        d = op_data.get("duration", 0)
        t = op_data.get("total", 0)
        p = op_data.get("passed", 0)
        k = op_data.get("skipped", 0)
        f = op_data.get("failed", 0)
        if s == "Passed":
            s = f"<span style='color:Green'>{s}</span>"
        else:
            s = f"<span style='color:Red'>{s}</span>"
        p = f"<span style='color:Green'>{p}</span>"
        k = f"<span style='color:DeepPink'>{k}</span>"
        f = f"<span style='color:Red'>{f}</span>"
        return f"| {s} | {d:6.2f} sec | {t} | {p} | {k} | {f} |"

    if ARGS.compare:
        data1 = DATA["before"].get("result", {})
        data2 = DATA["after"].get("result", {})
    else:
        data1 = DATA.get("result", {})

    op = list(data1.keys())[0]
    op_data1 = data1.get(op, {}).get("accuracy", {})
    op_data2 = {}
    if ARGS.compare:
        op_data2 = data2.get(op, {}).get("accuracy", {})

    lines = []
    lines.append("### Accuracy Result")
    lines.append("")
    lines.append("#### Summary")
    lines.append("")
    if ARGS.compare:
        line0 = "| Case | Status | Duration | Total | Passed | Skipped | Failed |"
        line1 = "|------|--------|----------|-------|--------|---------|--------|"
    else:
        line0 = "| Status | Duration | Total | Passed | Skipped | Failed |"
        line1 = "|--------|----------|-------|--------|---------|--------|"
    lines.append(line0)
    lines.append(line1)
    summary1 = _compose_summary(op_data1)
    if not ARGS.compare:
        lines.append(summary1)
    else:
        lines.append("| **Before** " + summary1)
        summary2 = _compose_summary(op_data2)
        lines.append("| **After** " + summary2)

    lines.append("")

    # Append failed and skipped cases if any, for the first run
    details = op_data1.get("details", {})
    case = " Before" if ARGS.compare else ""
    if op_data1.get("failed", 0) > 0:
        f_lines = parse_single_accuracy_details(details, "failed", case)
        lines.extend(f_lines)
    if op_data1.get("skipped", 0) > 0:
        k_lines = parse_single_accuracy_details(details, "skipped", case)
        lines.extend(k_lines)

    if not ARGS.compare:
        return lines

    details = op_data2.get("details", {})
    if op_data2.get("failed", 0) > 0:
        f_lines = parse_single_accuracy_details(details, "failed", " After")
        lines.extend(f_lines)
    if op_data2.get("skipped", 0) > 0:
        k_lines = parse_single_accuracy_details(details, "skipped", " After")
        lines.extend(k_lines)

    return lines


def parse_single_performance():
    def _get_summary(op_data, case=None):
        status = op_data.get("status", "OK")
        duration = op_data1.get("duration", 0)
        if status in ["Skipped", "Failed"]:
            reason = op_data1.get("reason", "Unknown")
            reason = "<blockquote>" + reason.replace("\n", "<br/>") + "</blockquote>"
            if status == "Failed":
                status = "<span style='color:Red'>Failed</span>"
            else:
                status = "<span style='color:DeepPink'>Skipped</span>"
            line = f"| {status} | {duration:6.2f} seconds | {reason} |"
        elif status == "NotFound":
            status = f"<span style='color:Gray'>{status}</span>"
            line = f"| {status} | {duration:6.2f} seconds | *No test case found.* |"
        else:
            status = f"<span style='color:Green'>{status}</span>"
            line = f"| {status} | {duration:6.2f} seconds | *All tests completed.* |"

        if case is None:
            return line

        return f"| **{case}** {line}"

    if ARGS.compare:
        data1 = DATA["before"].get("result", {})
        data2 = DATA["after"].get("result", {})
        op = list(data1.keys())[0]
        op_data2 = data2.get(op, {}).get("performance", {})
    else:
        data1 = DATA.get("result", {})

    op = list(data1.keys())[0]
    op_data1 = data1.get(op, {}).get("performance", {})

    lines = []
    lines.append("### Performance Result")
    lines.append("")
    lines.append("#### Summary")
    lines.append("")
    if ARGS.compare:
        lines.append("| Case | Status | Duration | Reason |")
        lines.append("|------|--------|----------|--------|")
    else:
        lines.append("| Status | Duration | Reason |")
        lines.append("|--------|----------|--------|")

    if ARGS.compare:
        lines.append(_get_summary(op_data1, "Before"))
        lines.append(_get_summary(op_data2, "After"))
    else:
        lines.append(_get_summary(op_data1))

    lines.append("")

    lines.append("#### Benchmark data")
    lines.append("")

    perf_data1 = op_data1.get("data", {})
    perf_data2 = {}
    if ARGS.compare:
        perf_data2 = op_data2.get("data", {})
    if not perf_data1 and not perf_data2:
        lines.append("*No performance data collected!*")
        return lines

    lines.append("| Dtype  | Speedup | Base | Gems  | Shape |")
    lines.append("|--------|---------|------|-------|-------|")
    for dtype, ddata1 in perf_data1.items():
        ddata2 = perf_data2.get(dtype, {})
        speedup1 = ddata1.get("speedup", 0)
        if ARGS.compare:
            speedup2 = ddata2.get("speedup", 0)
            spd_str = f"**{speedup1:.3f} -> {speedup2:.3f}**"
            if speedup2 > speedup1:
                spd_str = f"<span style='color:Green'>**{spd_str}**</span>"
            else:
                spd_str = f"<span style='color:Red'>**{spd_str}**</span>"

            line = f"| {dtype} | {spd_str} | - | - | - |"
        else:
            line = f"| {dtype} | **{speedup1:.3f}** | - | - | - |"
        lines.append(line)

        for shp, res1 in ddata1.get("details", {}).items():
            s1 = res1.get("speedup", 0)
            b1 = res1.get("base", 0)
            g1 = res1.get("gems", 0)

            if ARGS.compare and shp in ddata2.get("details", {}):
                res2 = ddata2.get("details").get(shp)
                s2 = res2.get("speedup", 0)
                b2 = res2.get("base", 0)
                g2 = res2.get("gems", 0)

                spd_str = f"{s1:.3f} -> {s2:.3f}"
                if s2 > s1:
                    spd_str = f"<span style='color:Green'>{spd_str}</span>"
                else:
                    spd_str = f"<span style='color:Red'>{spd_str}</span>"

                line = (
                    f"| | {spd_str} |"
                    f" {b1:.3f} -> {b2:.3f} |"
                    f" {g1:.3f} -> {g2:.3f} |"
                    f" `{shp}` |"
                )
            else:
                line = f"| | {s1:6.3f} | {b1:6.3f} | {g1:6.3f} | `{shp}` |"

            lines.append(line)

        # Deal with case where dtype in _after_ but not in _before_
        if ARGS.compare:
            for shp, res2 in ddata2.get("details", {}).items():
                if shp in ddata1.get("details", {}):
                    continue
                s2 = res2.get("speedup", 0)
                b2 = res2.get("base", 0)
                g2 = res2.get("gems", 0)
                line = (
                    f"| | 0 -> {s2:.3f} |"
                    f" 0 -> {b2:.3f} |"
                    f" 0 -> {g2:.3f} |"
                    f" `{shp}` |"
                )
                lines.append(line)

    lines.append("")
    return lines


def parse_lines():
    """Write result.

    The layout is as follows:
    <id>,<astatus>,<pass/fail/skip>,<pstatus>,[<metric for each dtype>],<note>
    """
    data = DATA.get("result", {})
    lines = []
    for op, item in data.items():
        if ARGS.debug:
            print(f"[DEBUG] processing {op}", file=sys.stderr)

        fields = []
        accu = item["accuracy"]["status"]
        accud = "/".join(
            [
                str(item["accuracy"]["passed"]),
                str(item["accuracy"]["failed"]),
                str(item["accuracy"]["skipped"]),
            ]
        )
        fields.extend([op, accu, accud])

        perf_data = item["performance"]["data"]
        perf_status = item["performance"]["status"]
        if perf_status == "NotFound":
            fields.append("NotFound")
            fields.extend([""] * (len(DTYPE_MAP) + 1))

        elif perf_status in ["Failed", "Skipped"]:
            reason = item["performance"]["reason"]
            reason = reason.split("\n")[0]
            fields.append(perf_status)
            fields.extend([""] * (len(DTYPE_MAP)))
            fields.append(f'"{reason}"')

        else:
            fields.append(perf_status)
            metric_list = []
            for dtype in list(DTYPE_MAP.values()):
                dobj = perf_data.get(dtype, {})

                if ARGS.metric == "speedup":
                    # Process `speedup`
                    metric = dobj.get("speedup", None)
                else:
                    # Process `base` by averaging across all shapes
                    total = 0
                    count = 0
                    for sdata in dobj.get("details", {}).values():
                        total += sdata.get("base", 0)
                        count += 1

                    if count == 0:
                        metric = None
                    else:
                        metric = total / count

                if metric is None:
                    fields.append("")
                else:
                    fields.append(f"{metric:.3f}")
                    metric_list.append(metric)

            if len(metric_list) > 0:
                metric_avg = sum(metric_list) / len(metric_list)
                fields.append(f"{metric_avg:.3f}")
            else:
                fields.append("")
            # The note column
            fields.append("")

        lines.append(format_record(fields))

    return sorted(lines)


def parse_single():
    lines = []
    lines.extend(parse_single_accuracy())
    lines.extend(parse_single_performance())
    return lines


def parse_multi():
    lines = parse_lines()
    header_fields = (
        [
            "No.",
            "ID",
            "AccRes",
            "AccStat(pass/fail/skip)",
            "PerfRes",
        ]
        + list(DTYPE_MAP.values())
        + ["PerfAvg", "Note"]
    )

    # Add sequence number to each sorted line
    numbered_lines = []
    for idx, line in enumerate(lines, 1):
        seq = str(idx)
        if ARGS.format == "csv":
            numbered_lines.append(seq + "," + line)
        else:
            numbered_lines.append(f"| {seq} {line}")
    lines = numbered_lines

    if ARGS.format == "csv":
        lines.insert(0, ",".join(header_fields))
    else:  # fmt == markdown
        header = "|" + "----|" * len(header_fields)
        lines.insert(0, header)
        header = "| " + " | ".join(header_fields) + " |"
        lines.insert(0, header)

    return lines


def main():
    global DATA
    global ARGS

    parser = argparse.ArgumentParser()
    parser.add_argument("dir", default="result", help="the data directory to process")
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "markdown"],
        default="csv",
        help="the output format",
    )
    parser.add_argument(
        "-o", "--output", default="<stdout>", help="path to the output file."
    )
    parser.add_argument(
        "--single",
        action=argparse.BooleanOptionalAction,
        help="only parse the result from the first operator",
    )
    parser.add_argument(
        "-c",
        "--compare",
        action=argparse.BooleanOptionalAction,
        help="parse data for comparison",
    )
    parser.add_argument(
        "-d",
        "--debug",
        action=argparse.BooleanOptionalAction,
        help="flag for printing verbose information for debugging",
    )
    parser.add_argument(
        "-m",
        "--metric",
        choices=["speedup", "base"],
        default="speedup",
        help="metric to summarize from the summary JSON",
    )

    ARGS = parser.parse_args()
    if ARGS.compare and not ARGS.single:
        print("Error: --compare can only be used with --single.")
        return 1
    if ARGS.format == "csv" and ARGS.single:
        print("Error: --single mode only supports markdown.")
        return 1

    if not ARGS.compare:
        data_path = Path(ARGS.dir) / "summary.json"
        DATA, res = load_data(data_path)
        if not res:
            return 1
    else:
        data_path1 = data_path = Path(ARGS.dir) / "before" / "summary.json"
        before, res = load_data(data_path1)
        if not res:
            return 1
        data_path2 = data_path = Path(ARGS.dir) / "after" / "summary.json"
        after, res = load_data(data_path2)
        DATA = {
            "before": before,
            "after": after,
        }

    lines = parse_env()
    if ARGS.format == "markdown":
        lines.append("")
        lines.append("### Test Result")
        lines.append("")

    if ARGS.single:
        lines += parse_single()
    else:
        lines += parse_multi()

    # never dump debug information to result file
    if ARGS.output == "<stdout>":
        for ln in lines:
            print(ln)
    else:
        with open(ARGS.output, "w") as f:
            for ln in lines:
                f.write(ln + "\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
