# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _amp_update_scale_kernel(
    scale_ptr,  # float32 scalar (in-place updated) == self
    growth_tracker_ptr,  # int32 scalar (in-place updated)
    found_inf_ptr,  # float32 scalar
    scale_growth_factor,  # python float -> tl.float32 constexpr
    scale_backoff_factor,  # python float -> tl.float32 constexpr
    growth_interval,  # python int -> tl.int32 constexpr
):
    # All inputs are 0-d (scalar) tensors; the kernel runs as a single program.
    scale = tl.load(scale_ptr).to(tl.float32)
    found_inf = tl.load(found_inf_ptr).to(tl.float32)
    tracker = tl.load(growth_tracker_ptr).to(tl.int32)

    # If a non-finite value was encountered (found_inf != 0), back the scale off.
    has_inf = found_inf != 0.0

    # Growth branch: increment the tracker and, once it reaches the growth
    # interval, scale the loss scale up and reset the tracker.
    new_tracker_grow = tracker + 1
    reached_interval = new_tracker_grow == growth_interval
    # When the interval is reached we reset the tracker to 0, otherwise keep the
    # incremented value.
    tracker_grow = tl.where(reached_interval, 0, new_tracker_grow)
    scale_grow = tl.where(reached_interval, scale * scale_growth_factor, scale)

    # Backoff branch: shrink the scale and reset the tracker to 0.
    scale_backoff = scale * scale_backoff_factor

    new_scale = tl.where(has_inf, scale_backoff, scale_grow)
    new_tracker = tl.where(has_inf, 0, tracker_grow)

    tl.store(scale_ptr, new_scale.to(scale_ptr.dtype.element_ty))
    tl.store(growth_tracker_ptr, new_tracker.to(growth_tracker_ptr.dtype.element_ty))


def _amp_update_scale_(
    self,
    growth_tracker,
    found_inf,
    scale_growth_factor,
    scale_backoff_factor,
    growth_interval,
):
    """
    Update the AMP loss scale in-place.

    Mirrors ``aten::_amp_update_scale_``: ``self`` holds the current loss scale
    (a float32 scalar tensor) and is updated and returned; ``growth_tracker``
    (an int scalar tensor) is updated in-place as well.

    - When ``found_inf`` is non-zero, the scale is multiplied by
      ``scale_backoff_factor`` and the growth tracker is reset to 0.
    - Otherwise the growth tracker is incremented; when it reaches
      ``growth_interval`` the scale is multiplied by ``scale_growth_factor``
      and the tracker is reset to 0.
    """
    logger.debug("GEMS _AMP_UPDATE_SCALE_")

    if not self.is_floating_point():
        raise RuntimeError("current_scale must be a float tensor.")
    if not growth_tracker.is_floating_point() and growth_tracker.dtype not in (
        torch.int32,
        torch.int64,
        torch.int16,
        torch.int8,
    ):
        raise RuntimeError("growth_tracker must be an int tensor.")
    if not found_inf.is_floating_point():
        raise RuntimeError("found_inf must be a float tensor.")

    # Ensure the tracker is a 32-bit int for the kernel.
    if growth_tracker.dtype != torch.int32:
        growth_tracker = growth_tracker.to(torch.int32)

    with torch_device_fn.device(self.device):
        _amp_update_scale_kernel[(1,)](
            self,
            growth_tracker,
            found_inf,
            float(scale_growth_factor),
            float(scale_backoff_factor),
            int(growth_interval),
        )

    return self
