# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.ops.add import add
from flag_gems.ops.conv2d import conv2d
from flag_gems.ops.conv_transpose2d import conv_transpose2d
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


def _pair(x):
    if isinstance(x, (list, tuple)):
        if len(x) == 1:
            return int(x[0]), int(x[0])
        return int(x[0]), int(x[1])
    return int(x), int(x)


def _conv_out_size(in_size, kernel_size, stride, padding, dilation):
    return (in_size + 2 * padding - dilation * (kernel_size - 1) - 1) // stride + 1


def _conv_transpose_out_size(
    in_size, kernel_size, stride, padding, dilation, output_padding
):
    return (
        (in_size - 1) * stride
        - 2 * padding
        + dilation * (kernel_size - 1)
        + 1
        + output_padding
    )


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("conv2d_backward_weight"),
    key=[
        "input_height",
        "input_width",
        "weight_height",
        "weight_width",
        "input_c",
        "stride_height",
        "stride_width",
        "out_height",
        "out_width",
        "out_c",
        "padding_height",
        "padding_width",
    ],
)
@triton.jit
def conv_double_backward_weight_kernel(
    input_pointer,  # tensor whose channels are the "input" channels of the weight
    out_grad_pointer,  # tensor whose channels are the "output" channels of the weight
    weight_pointer,  # output gradient w.r.t. weight
    input_n_stride,
    input_c_stride,
    input_height_stride,
    input_width_stride,
    weight_n_stride,
    weight_c_stride,
    weight_height_stride,
    weight_width_stride,
    output_n_stride,
    output_c_stride,
    output_height_stride,
    output_width_stride,
    input_height,
    input_width,
    weight_height,
    weight_width,
    input_c,
    in_n,
    stride_height,
    stride_width,
    out_height,
    out_width,
    out_c,
    padding_height,
    padding_width,
    dilation_height,
    dilation_width,
    BLOCK_NO: tl.constexpr,
    BLOCK_CI_HK_WK: tl.constexpr,
    BLOCK_CO: tl.constexpr,
):
    # Computes the correlation
    #   weight[c_out, c_in, kh, kw] =
    #       sum_{n, h, w} input[n, c_in, kh*dil - pad + stride*h, kw*dil - pad + stride*w]
    #                  * out_grad[n, c_out, h, w]
    # where input/out_grad are the two operands of the double-backward whose channel
    # axes become the (c_in, c_out) axes of the resulting weight gradient.
    pid_ci_hk_wk = tl.program_id(0)
    pid_groups = tl.program_id(1)
    pid_co = tl.program_id(2)

    ci_hk_wk_offset = pid_ci_hk_wk * BLOCK_CI_HK_WK + tl.arange(0, BLOCK_CI_HK_WK)
    ci_hk_offset = ci_hk_wk_offset // weight_width
    ci_point_value = ci_hk_offset // weight_height
    weight_height_point_value = ci_hk_offset % weight_height
    weight_width_point_value = ci_hk_wk_offset % weight_width

    output_c_offset = pid_co * BLOCK_CO + tl.arange(0, BLOCK_CO)
    out_grad_pointer += (output_c_offset * output_c_stride)[None, :] + (
        pid_groups[None] * output_c_stride * out_c
    )[:, None]

    weight_pointer += (
        pid_groups * weight_n_stride * out_c + output_c_offset * weight_n_stride
    )[None, :] + (
        ci_point_value * weight_c_stride
        + weight_height_point_value * weight_height_stride
        + weight_width_point_value * weight_width_stride
    )[
        :, None
    ]

    input_pointer += (ci_point_value * input_c_stride[None])[:, None] + (
        pid_groups[None] * input_c_stride * input_c
    )[None, :]

    accum = tl.zeros((BLOCK_CI_HK_WK, BLOCK_CO), dtype=tl.float32)
    for h in range(0, out_height):
        for w in range(0, out_width):
            for n in range(0, in_n, BLOCK_NO):
                output_n_offset = n + tl.arange(0, BLOCK_NO)

                curr_out_grad_pointer = (
                    out_grad_pointer
                    + (
                        output_n_offset * output_n_stride
                        + h * output_height_stride
                        + w * output_width_stride
                    )[:, None]
                )
                out_grad_mask = (output_n_offset < in_n)[:, None] & (
                    output_c_offset < out_c
                )[None, :]

                curr_out_grad = tl.load(curr_out_grad_pointer, mask=out_grad_mask)

                input_height_offset = (
                    weight_height_point_value * dilation_height
                    - padding_height
                    + stride_height * h
                )
                input_width_offset = (
                    weight_width_point_value * dilation_width
                    - padding_width
                    + stride_width * w
                )

                curr_input_pointer = (
                    input_pointer
                    + (input_n_stride * output_n_offset)[None, :]
                    + (input_height_stride * input_height_offset)[:, None]
                    + (input_width_stride * input_width_offset)[:, None]
                )
                input_mask = (
                    (output_n_offset < in_n)[None, :]
                    & (ci_point_value < input_c)[:, None]
                    & (0 <= input_height_offset)[:, None]
                    & (input_height_offset < input_height)[:, None]
                    & (0 <= input_width_offset)[:, None]
                    & (input_width_offset < input_width)[:, None]
                )

                curr_input = tl.load(curr_input_pointer, mask=input_mask)
                accum += tl.dot(curr_input, curr_out_grad, allow_tf32=False)

    weight_mask = (
        (ci_point_value < input_c)[:, None]
        & (output_c_offset < out_c)[None, :]
        & (weight_height_point_value < weight_height)[:, None]
        & (weight_width_point_value < weight_width)[:, None]
    )
    tl.store(weight_pointer, accum, weight_mask)


def _grad_weight_correlation(
    input, out_grad, weight_shape, stride, padding, dilation, groups
):
    """Compute the weight-shaped gradient via the correlation kernel above.

    weight[c_out, c_in, kh, kw] = sum_{n, h, w} input[n, c_in, ...] * out_grad[n, c_out, ...]
    """
    out_c_total, weight_c, weight_height, weight_width = weight_shape
    out_c = out_c_total // groups  # per-group output channels
    in_n = input.shape[0]
    input_height, input_width = input.shape[2], input.shape[3]
    out_height, out_width = out_grad.shape[2], out_grad.shape[3]
    stride_height, stride_width = _pair(stride)
    padding_height, padding_width = _pair(padding)
    dilation_height, dilation_width = _pair(dilation)

    grad_weight = torch.empty(
        weight_shape,
        device=input.device,
        dtype=input.dtype,
    )

    grid = lambda META: (
        triton.cdiv(weight_c * weight_height * weight_width, META["BLOCK_CI_HK_WK"]),
        groups,
        triton.cdiv(out_c, META["BLOCK_CO"]),
    )
    conv_double_backward_weight_kernel[grid](
        input,
        out_grad,
        grad_weight,
        *input.stride(),
        *grad_weight.stride(),
        *out_grad.stride(),
        input_height,
        input_width,
        weight_height,
        weight_width,
        weight_c,
        in_n,
        stride_height,
        stride_width,
        out_height,
        out_width,
        out_c,
        padding_height,
        padding_width,
        dilation_height,
        dilation_width,
    )
    return grad_weight


def _convolution_double_backward_2d(
    ggI,
    ggW,
    ggb,
    gO,
    weight,
    self,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
    output_mask,
):
    """Second-order backward of a 2D convolution.

    Let ``y = conv(x, w, b)`` with ``(gX, gW, gB) = backward(gO)``. Given the
    second-order grad-outputs ``(ggI, ggW, ggb)`` for ``(gX, gW, gB)``, this returns
    the gradients of ``<gX, ggI> + <gW, ggW> + <gB, ggb>`` with respect to
    ``(gO, x, w)``, i.e. ``(grad_ggO, grad_self, grad_weight)``.
    """
    stride_h, stride_w = _pair(stride)
    pad_h, pad_w = _pair(padding)
    dil_h, dil_w = _pair(dilation)

    # spatial dims of the forward output (== gO spatial dims)
    gO_h, gO_w = gO.shape[2], gO.shape[3]
    # spatial dims of the forward input (== self spatial dims)
    self_h, self_w = self.shape[2], self.shape[3]
    kH, kW = weight.shape[2], weight.shape[3]

    grad_ggO = None
    grad_self = None
    grad_weight = None

    # Note: aten::_convolution_double_backward ignores ``output_mask`` for its
    # outputs and always returns all three gradients (it only ever forwards the
    # mask down to the underlying cudnn call). To match that behaviour we compute
    # every requested gradient whenever its grad-output input is available; a
    # missing ggI / ggW / ggb simply drops the corresponding contribution.

    # grad_ggO = sum of contributions from ggI, ggW and ggb.
    parts = []
    if ggI is not None:
        if not transposed:
            # contribution of ggI: this is the adjoint of the input-gradient op,
            # which is a plain forward convolution of ggI with the weight using
            # the *forward* stride/padding/dilation (output spatial size == gO's).
            parts.append(
                conv2d(
                    ggI,
                    weight,
                    stride=stride,
                    padding=padding,
                    dilation=dilation,
                    groups=groups,
                )
            )
        else:
            # contribution of ggI: transposed convolution of ggI with the weight.
            parts.append(
                conv_transpose2d(
                    ggI,
                    weight,
                    stride=stride,
                    padding=padding,
                    output_padding=output_padding,
                    groups=groups,
                    dilation=dilation,
                )
            )
    if ggW is not None:
        if not transposed:
            # contribution of ggW: forward convolution of x with ggW.
            parts.append(
                conv2d(
                    self,
                    ggW,
                    stride=stride,
                    padding=padding,
                    dilation=dilation,
                    groups=groups,
                )
            )
        else:
            # contribution of ggW: transposed convolution of x with ggW.
            parts.append(
                conv_transpose2d(
                    self,
                    ggW,
                    stride=stride,
                    padding=padding,
                    output_padding=output_padding,
                    groups=groups,
                    dilation=dilation,
                )
            )
    if ggb is not None:
        # contribution of ggb: broadcast the per-channel value over the output.
        bias_part = ggb.view(1, -1, 1, 1).expand(1, ggb.shape[0], gO_h, gO_w)
        # match batch dim of gO for broadcasting.
        bias_part = bias_part.expand(gO.shape[0], -1, -1, -1)
        parts.append(bias_part)

    if parts:
        grad_ggO = parts[0]
        for p in parts[1:]:
            grad_ggO = add(grad_ggO, p)

    if ggW is not None:
        # grad_self only depends on ggW.
        if not transposed:
            # input-gradient form: transposed convolution of gO with ggW.
            # Recover the self spatial size via output_padding.
            opad_self_h = self_h - (
                (gO_h - 1) * stride_h - 2 * pad_h + dil_h * (kH - 1) + 1
            )
            opad_self_w = self_w - (
                (gO_w - 1) * stride_w - 2 * pad_w + dil_w * (kW - 1) + 1
            )
            grad_self = conv_transpose2d(
                gO,
                ggW,
                stride=stride,
                padding=padding,
                output_padding=(opad_self_h, opad_self_w),
                groups=groups,
                dilation=dilation,
            )
        else:
            # transposed forward: grad_self is a forward convolution of gO with ggW.
            grad_self = conv2d(
                gO,
                ggW,
                stride=stride,
                padding=padding,
                dilation=dilation,
                groups=groups,
            )

    if ggI is not None:
        # grad_weight only depends on ggI.
        if not transposed:
            # weight[c_out, c_in, kh, kw] = sum ggI[c_in] * gO[c_out]
            grad_weight = _grad_weight_correlation(
                ggI, gO, weight.shape, stride, padding, dilation, groups
            )
        else:
            # transposed forward: weight[c_in, c_out, kh, kw] = sum gO[c_out] * ggI[c_in]
            grad_weight = _grad_weight_correlation(
                gO, ggI, weight.shape, stride, padding, dilation, groups
            )

    return grad_ggO, grad_self, grad_weight


def _convolution_double_backward_1d(
    ggI,
    ggW,
    ggb,
    gO,
    weight,
    self,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
    output_mask,
):
    """Second-order backward of a 1D convolution.

    1D convolutions (3-D operands ``[N, C, L]``) are handled by routing through
    the 2D implementation: a trailing spatial axis is unsqueezed
    (``[N, C, L]`` -> ``[N, C, L, 1]``), the 2D path runs, and the extra axis is
    squeezed back on every output. This mirrors how ``conv1d`` delegates to
    ``conv2d``. ``ggb`` is a 1-D channel vector and is passed through unchanged.
    """

    # Widen the lone spatial axis to a (degenerate) 2D one and pass it to the
    # 2D path. Scalar/int 1D params become length-2 lists with the second axis
    # set to identity (stride 1, no padding, dilation 1, no output padding).
    def _widen(param, fill):
        if param is None:
            return None
        if isinstance(param, (list, tuple)):
            return [param[0], fill]
        return [param, fill]

    def _unsqueeze(t):
        return t.unsqueeze(-1) if t is not None else None

    def _squeeze(t):
        return t.squeeze(-1) if t is not None else None

    res_2d = _convolution_double_backward_2d(
        _unsqueeze(ggI),
        _unsqueeze(ggW),
        ggb,
        _unsqueeze(gO),
        _unsqueeze(weight),
        _unsqueeze(self),
        _widen(stride, 1),
        _widen(padding, 0),
        _widen(dilation, 1),
        transposed,
        _widen(output_padding, 0),
        groups,
        output_mask,
    )
    return tuple(_squeeze(r) for r in res_2d)


def _convolution_double_backward(
    ggI,
    ggW,
    ggb,
    gO,
    weight,
    self,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
    output_mask,
):
    logger.debug("GEMS _CONVOLUTION_DOUBLE_BACKWARD")

    # Dispatch by spatial arity (matches the convention used by
    # ``_convolution_mode``: ``spatial_ndim = weight.ndim - 2``). 1D convolutions
    # are routed through the 2D path by unsqueezing the lone spatial axis
    # (mirroring ``conv1d``, which delegates to ``conv2d`` the same way).
    spatial_ndim = weight.ndim - 2
    if spatial_ndim == 2:
        return _convolution_double_backward_2d(
            ggI,
            ggW,
            ggb,
            gO,
            weight,
            self,
            stride,
            padding,
            dilation,
            transposed,
            output_padding,
            groups,
            output_mask,
        )
    if spatial_ndim == 1:
        return _convolution_double_backward_1d(
            ggI,
            ggW,
            ggb,
            gO,
            weight,
            self,
            stride,
            padding,
            dilation,
            transposed,
            output_padding,
            groups,
            output_mask,
        )

    raise NotImplementedError(
        "_convolution_double_backward: FlagGems supports 1D (3-D operands) and "
        "2D (4-D operands) convolutions, but 3D (5-D operands) is not yet "
        "implemented. got ndim "
        f"self={self.ndim}, weight={weight.ndim}, gO={gO.ndim}."
    )
