# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry, tl_extra_shim

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _fake_quantize_learnable_per_channel_affine_backward_kernel(
    grad_ptr,
    self_ptr,
    scale_ptr,
    zero_point_ptr,
    dX_ptr,
    dScale_vec_ptr,
    dZeroPoint_vec_ptr,
    numel,
    C,
    suffix,
    quant_min,
    quant_max,
    grad_factor,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < numel

    grad = tl.load(grad_ptr + offsets, mask=mask, other=0.0)
    x = tl.load(self_ptr + offsets, mask=mask, other=0.0)

    # Channel index along the quantization axis.
    channel = (offsets // suffix) % C
    scale = tl.load(scale_ptr + channel, mask=mask, other=0.0)
    zero_point = tl.load(zero_point_ptr + channel, mask=mask, other=0.0)

    # Rounded (and clamped) zero point, mirroring _get_rounded_zero_point.
    zp_rounded = tl_extra_shim.rint(zero_point)
    zp_rounded = tl.minimum(tl.maximum(zp_rounded, quant_min), quant_max)

    inv_scale = 1.0 / scale

    # Quantized integer value: xq = nearbyint(x * inv_scale) + zp_rounded
    xq = tl_extra_shim.rint(x * inv_scale) + zp_rounded

    in_range = (xq >= quant_min) & (xq <= quant_max)
    dX = grad * in_range.to(tl.float32)

    # Fake-quantized (clamped) value: (clamp(xq) - zp_rounded) * scale
    xq_clamped = tl.minimum(tl.maximum(xq, quant_min), quant_max)
    xfq = (xq_clamped - zp_rounded) * scale

    sat = (xq < quant_min) | (xq > quant_max)
    sat_low = xq < quant_min
    dscale_small = (quant_min - zp_rounded).to(tl.float32)
    dscale_big = (quant_max - zp_rounded).to(tl.float32)

    dScale_sat = tl.where(sat_low, grad * dscale_small, grad * dscale_big) * grad_factor
    dScale_inrange = grad * (xfq - x) * inv_scale * grad_factor
    dScale_vec = tl.where(sat, dScale_sat, dScale_inrange)

    dZeroPoint_vec = tl.where(sat, grad * (-1.0) * scale * grad_factor, 0.0)

    tl.store(dX_ptr + offsets, dX, mask=mask)
    tl.store(dScale_vec_ptr + offsets, dScale_vec, mask=mask)
    tl.store(dZeroPoint_vec_ptr + offsets, dZeroPoint_vec, mask=mask)


def _fake_quantize_learnable_per_channel_affine_backward(
    grad,
    self,
    scale,
    zero_point,
    axis,
    quant_min,
    quant_max,
    grad_factor=1.0,
):
    logger.debug("GEMS FAKE_QUANTIZE_LEARNABLE_PER_CHANNEL_AFFINE_BACKWARD")

    # The aten op requires all tensors to be float32; enforce it here too.
    assert grad.dtype == torch.float32, "grad must be float32"
    assert self.dtype == torch.float32, "self must be float32"
    assert scale.dtype == torch.float32, "scale must be float32"
    assert zero_point.dtype == torch.float32, "zero_point must be float32"
    grad = grad.contiguous()
    self = self.contiguous()
    scale = scale.contiguous()
    zero_point = zero_point.contiguous()

    numel = self.numel()
    dX = torch.empty_like(self)
    if numel == 0:
        dScale = torch.zeros_like(scale)
        dZeroPoint = torch.zeros_like(zero_point)
        return dX, dScale, dZeroPoint

    dScale_vec = torch.empty_like(self)
    dZeroPoint_vec = torch.empty_like(self)

    C = self.shape[axis]
    # Product of sizes after the quantization axis (for contiguous flatten index).
    suffix = 1
    for s in self.shape[axis + 1 :]:
        suffix *= s
    suffix = max(int(suffix), 1)

    # Block size tuned for elementwise map over flattened numel.
    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(numel, meta["BLOCK_SIZE"]),)

    _fake_quantize_learnable_per_channel_affine_backward_kernel[grid](
        grad,
        self,
        scale,
        zero_point,
        dX,
        dScale_vec,
        dZeroPoint_vec,
        numel,
        C,
        suffix,
        quant_min,
        quant_max,
        float(grad_factor),
        BLOCK_SIZE=BLOCK_SIZE,
    )

    # Reduce dScale_vec / dZeroPoint_vec over all axes except `axis`.
    ndim = self.dim()
    reduce_axes = tuple(i for i in range(ndim) if i != axis)
    dScale = dScale_vec.sum(dim=reduce_axes)
    dZeroPoint = dZeroPoint_vec.sum(dim=reduce_axes)

    return dX, dScale, dZeroPoint
