# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit(do_not_specialize=["seed", "offset"])
def _fill_mem_eff_dropout_mask_kernel(
    out_ptr,
    numel,
    seed,
    offset,
    BLOCK: tl.constexpr,
):
    # ``_fill_mem_eff_dropout_mask_`` fills a contiguous 4D float32 tensor of
    # shape ``(batch, heads, queries, keys)`` with random uniform values in
    # [0, 1) drawn from a Philox4x32-10 stream identified by ``seed`` and
    # ``offset``. The CUDA reference (curand) advances its counter by one per
    # ``curand_uniform4`` call (i.e. per 4 floats), so the counter value for the
    # block starting at linear float index ``i`` is ``(offset + i) // 4``. The
    # reference writes the four floats of each block consecutively, so the whole
    # tensor is populated in linear index order and a flat 1D grid reproduces the
    # exact same random stream.
    CURAND_2_P32_INV: tl.constexpr = 2.3283064365386963e-10  # 1.0 / (2 ** 32)
    seed = seed.to(tl.int64)
    offset = offset.to(tl.int64)

    pid = tl.program_id(0)
    # Each program handles ``BLOCK`` whole Philox blocks; one Philox block
    # yields 4 floats written to 4 consecutive linear positions.
    block_idx = pid * BLOCK + tl.arange(0, BLOCK)  # index of the 4-float block
    elem_start = block_idx * 4  # linear (float) index of the block's first element

    # curand advances its counter by one per 4-float block, so the counter for
    # block ``block_idx`` is ``(offset + block_idx * 4) // 4 == offset // 4 +
    # block_idx`` (when offset is a multiple of 4, which is the only usage in
    # practice). Keep the general formula for safety.
    linear = offset + elem_start
    c0 = (linear // 4).to(tl.uint32)
    zero = tl.zeros_like(c0)
    r0, r1, r2, r3 = tl.philox(seed, c0, zero, zero, zero)
    r0 = r0.to(tl.float32) * CURAND_2_P32_INV + (CURAND_2_P32_INV / 2.0)
    r1 = r1.to(tl.float32) * CURAND_2_P32_INV + (CURAND_2_P32_INV / 2.0)
    r2 = r2.to(tl.float32) * CURAND_2_P32_INV + (CURAND_2_P32_INV / 2.0)
    r3 = r3.to(tl.float32) * CURAND_2_P32_INV + (CURAND_2_P32_INV / 2.0)

    tl.store(out_ptr + elem_start + 0, r0, mask=elem_start + 0 < numel)
    tl.store(out_ptr + elem_start + 1, r1, mask=elem_start + 1 < numel)
    tl.store(out_ptr + elem_start + 2, r2, mask=elem_start + 2 < numel)
    tl.store(out_ptr + elem_start + 3, r3, mask=elem_start + 3 < numel)


def _fill_mem_eff_dropout_mask_(self, dropout_p, seed, offset):
    logger.debug("GEMS FILL_MEM_EFF_DROPOUT_MASK")
    assert self.is_contiguous(), "self must be contiguous"
    assert self.dim() == 4, "_fill_mem_eff_dropout_mask_ expects a 4D tensor"
    assert self.dtype == torch.float32, "self must be a float32 tensor"

    numel = self.numel()
    # Each program handles BLOCK whole Philox blocks (4 floats each).
    BLOCK = 256
    grid = (triton.cdiv(numel, BLOCK * 4),)
    with torch_device_fn.device(self.device):
        _fill_mem_eff_dropout_mask_kernel[grid](
            self,
            numel,
            seed,
            offset,
            BLOCK,
        )
    return self
