# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _nested_sum_backward_kernel(
    grad_ptr,
    out_ptr,
    numel,
    dim_size,
    inner_size,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)

    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < numel

    # Decompose the flattened output index into (outer, dim, inner) where the
    # reduced `dim` has been broadcast from `grad`, which stores a single value
    # per (outer, inner) pair. `grad` is laid out as [outer, inner] in memory.
    outer_idx = offsets // (dim_size * inner_size)
    inner_idx = offsets % inner_size
    grad_offset = outer_idx * inner_size + inner_idx

    grad = tl.load(grad_ptr + grad_offset, mask=mask)
    tl.store(out_ptr + offsets, grad, mask=mask)


def _nested_sum_backward(grad, self, dim=None, keepdim=False):
    """Backward of the (nested) tensor `sum` over a single dimension.

    Given the gradient `grad` of the summed output, broadcast it back to the
    original `self` shape along the reduced dimension. For regular dense
    tensors this is equivalent to ``grad.expand_as(self)`` after re-inserting
    the reduced dimension when ``keepdim`` is False.

    Args:
        grad (Tensor): the gradient w.r.t. the output of ``sum(dim)``.
        self (Tensor): the original input tensor, providing the output shape.
        dim (Optional[int[1]]): the dimension that was reduced.
        keepdim (bool): whether the reduced dimension was retained in `grad`.

    Returns:
        Tensor: the gradient broadcast back to the shape of `self`.
    """
    logger.debug("GEMS _NESTED_SUM_BACKWARD")

    shape = list(self.shape)
    ndim = self.dim()

    if dim is None:
        # Full reduction: `grad` is a scalar (or an all-ones keepdim shape).
        # Broadcasting a 0-d/1-d tensor to `shape` is a no-data-copy edge case
        # that never occurs for nested tensors (which always reduce a dim).
        return torch.broadcast_to(grad, shape).contiguous()

    if isinstance(dim, (list, tuple)):
        d = int(dim[0])
    else:
        d = int(dim)
    if d < 0:
        d += ndim

    inner_size = 1
    for s in shape[d + 1 :]:
        inner_size *= s
    dim_size = shape[d]

    grad = grad.contiguous()
    out = torch.empty(shape, dtype=grad.dtype, device=grad.device)

    numel = out.numel()
    if numel == 0:
        return out

    # 1024 threads covers 32 full warps, enough to saturate memory bandwidth for
    # this elementwise broadcast without needing an autotuned block size.
    _BLOCK = 1024
    grid = (triton.cdiv(numel, _BLOCK),)
    _nested_sum_backward_kernel[grid](
        grad,
        out,
        numel,
        dim_size,
        inner_size,
        BLOCK_SIZE=_BLOCK,
    )
    return out
