# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List

import torch
import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True], promotion_methods=[(0, "DEFAULT")])
@triton.jit
def _resize_output_kernel(data):
    # Simply return the data - this is used for copying data during resize
    return data


def _resize_output(inp: torch.Tensor, size: List[int], device: torch.device):
    """Resize the input tensor to the specified size.

    Args:
        inp: Input tensor
        size: Target size as a list of integers
        device: Target device

    Returns:
        Resized tensor
    """
    logger.debug("GEMS _resize_output")

    # Calculate total number of elements
    old_numel = inp.numel()
    new_numel = 1
    for s in size:
        new_numel *= s

    # If same shape and device, just return input (no-op)
    if new_numel == old_numel and inp.device == device:
        return inp.reshape(size)

    # Create output tensor on target device
    out = torch.empty(size, dtype=inp.dtype, device=device)

    # Copy data - copy min(old_numel, new_numel) elements using Triton kernel
    copy_numel = min(old_numel, new_numel)
    if copy_numel > 0:
        # Flatten and slice to get the elements to copy
        inp_flat = inp.reshape(-1)[:copy_numel]
        out_flat = out.reshape(-1)[:copy_numel]
        # Use FlagGems copy_ which uses Triton kernel
        from flag_gems.ops.copy import copy_

        copy_(out_flat, inp_flat)

    return out


def _resize_output_(inp: torch.Tensor, size: List[int], device: torch.device):
    """In-place resize the input tensor to the specified size.

    Args:
        inp: Input tensor (will be modified in place)
        size: Target size as a list of integers
        device: Target device

    Returns:
        Resized tensor (same object as input)
    """
    logger.debug("GEMS _resize_output_")

    # Calculate total number of elements
    old_numel = inp.numel()
    new_numel = 1
    for s in size:
        new_numel *= s

    # For in-place, we use PyTorch's resize_ which handles all cases
    # This includes same device/different shape, different device, etc.
    if inp.device == device:
        # Same device - use PyTorch's resize_ which modifies in place
        inp.resize_(size)
        return inp
    else:
        # Different device - need to create temp and copy
        out = torch.empty(size, dtype=inp.dtype, device=device)
        copy_numel = min(old_numel, new_numel)
        if copy_numel > 0:
            inp_flat = inp.reshape(-1)[:copy_numel]
            out_flat = out.reshape(-1)[:copy_numel]
            from flag_gems.ops.copy import copy_

            copy_(out_flat, inp_flat)
        inp.resize_(size)
        inp.copy_(out)
        return inp
        inp.resize_(size)
        inp.copy_(out)
        return inp
