# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging
import math
import struct
from typing import Optional, Sequence

import torch
import triton
import triton.language as tl

from flag_gems.runtime import device, torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _upsample_nearest_exact1d_backward_kernel(
    grad_output,
    grad_input,
    numel,
    channels,
    output_w,
    input_w,
    grad_output_stride_n,
    grad_output_stride_c,
    grad_output_stride_w,
    grad_input_stride_n,
    grad_input_stride_c,
    grad_input_stride_w,
    backward_scale,
    BATCH: tl.constexpr,
    BATCH_LOOP: tl.constexpr,
    IS_FP64: tl.constexpr,
    IS_UINT8: tl.constexpr,
    MAX_CONTRIBUTORS: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    offsets = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < numel
    input_x = offsets % input_w
    if BATCH_LOOP:
        channel = offsets // input_w
    else:
        nc = offsets // input_w
        channel = nc % channels
        batch = nc // channels

    # Match nearest_neighbor_exact_bw_compute_source_index from PyTorch:
    # ceil(input_index * scale - 0.5), clamped to output_w.
    input_x_f32 = input_x.to(tl.float32)
    start = tl.ceil(input_x_f32 * backward_scale - 0.5).to(tl.int64)
    end = tl.ceil((input_x_f32 + 1.0) * backward_scale - 0.5).to(tl.int64)
    start = tl.minimum(tl.maximum(start, 0), output_w)
    end = tl.minimum(tl.maximum(end, 0), output_w)

    if BATCH_LOOP:
        for batch_index in range(BATCH):
            if IS_UINT8:
                accumulator = tl.zeros((BLOCK_SIZE,), dtype=tl.int32)
            elif IS_FP64:
                accumulator = tl.zeros((BLOCK_SIZE,), dtype=tl.float64)
            else:
                accumulator = tl.zeros((BLOCK_SIZE,), dtype=tl.float32)
            output_base = (
                batch_index * grad_output_stride_n + channel * grad_output_stride_c
            )
            for contributor in range(MAX_CONTRIBUTORS):
                output_x = start + contributor
                contributor_mask = mask & (output_x < end)
                value = tl.load(
                    grad_output + output_base + output_x * grad_output_stride_w,
                    mask=contributor_mask,
                    other=0,
                )
                accumulator += value
            input_offset = (
                batch_index * grad_input_stride_n
                + channel * grad_input_stride_c
                + input_x * grad_input_stride_w
            )
            tl.store(grad_input + input_offset, accumulator, mask=mask)
    else:
        if IS_UINT8:
            accumulator = tl.zeros((BLOCK_SIZE,), dtype=tl.int32)
        elif IS_FP64:
            accumulator = tl.zeros((BLOCK_SIZE,), dtype=tl.float64)
        else:
            accumulator = tl.zeros((BLOCK_SIZE,), dtype=tl.float32)
        output_base = batch * grad_output_stride_n + channel * grad_output_stride_c
        for contributor in range(MAX_CONTRIBUTORS):
            output_x = start + contributor
            contributor_mask = mask & (output_x < end)
            value = tl.load(
                grad_output + output_base + output_x * grad_output_stride_w,
                mask=contributor_mask,
                other=0,
            )
            accumulator += value
        input_offset = (
            batch * grad_input_stride_n
            + channel * grad_input_stride_c
            + input_x * grad_input_stride_w
        )
        tl.store(grad_input + input_offset, accumulator, mask=mask)


def _validate_args(
    grad_output: torch.Tensor,
    output_size: Sequence[int],
    input_size: Sequence[int],
) -> tuple[int, int, int, int]:
    if grad_output.device.type != device.name:
        raise RuntimeError(
            f"Expected grad_output on {device.name}, but got {grad_output.device.type}"
        )
    if grad_output.ndim != 3:
        raise RuntimeError("Expected grad_output to be a 3D tensor")
    if len(output_size) != 1:
        raise RuntimeError("Expected output_size to contain one element")
    if len(input_size) != 3:
        raise RuntimeError("Expected input_size to contain three elements")
    if not grad_output.is_floating_point() and grad_output.dtype != torch.uint8:
        raise RuntimeError(
            f'"upsample_nearest1d_backward_out_frame" not implemented for '
            f"'{grad_output.dtype}'"
        )

    output_w = int(output_size[0])
    batch, channels, input_w = (int(value) for value in input_size)
    if input_w <= 0 or output_w <= 0:
        raise RuntimeError("Input and output sizes should be greater than 0")
    if tuple(grad_output.shape) != (batch, channels, output_w):
        raise RuntimeError(
            f"Expected grad_output shape {(batch, channels, output_w)}, "
            f"but got {tuple(grad_output.shape)}"
        )
    return batch, channels, input_w, output_w


def _as_float32(value: float) -> float:
    return struct.unpack("f", struct.pack("f", value))[0]


def _upsample_nearest_exact1d_backward_impl(
    grad_output: torch.Tensor,
    output_size: Sequence[int],
    input_size: Sequence[int],
    scales: Optional[float],
    grad_input: Optional[torch.Tensor],
) -> torch.Tensor:
    batch, channels, input_w, output_w = _validate_args(
        grad_output, output_size, input_size
    )
    if grad_input is None:
        grad_input = torch.empty(
            (batch, channels, input_w),
            dtype=grad_output.dtype,
            device=grad_output.device,
        )
    else:
        if grad_input.device != grad_output.device:
            raise RuntimeError(
                f"Expected grad_input on {grad_output.device}, "
                f"but got {grad_input.device}"
            )
        if grad_input.dtype != grad_output.dtype:
            raise RuntimeError(
                f"Expected grad_input dtype {grad_output.dtype}, "
                f"but got {grad_input.dtype}"
            )
        grad_input.resize_((batch, channels, input_w))

    if grad_input.numel() == 0:
        return grad_input

    backward_scale = _as_float32(
        float(scales) if scales is not None and scales > 0.0 else output_w / input_w
    )
    max_contributors = min(output_w, max(1, math.ceil(backward_scale) + 1))
    batch_loop = batch <= 32
    numel = channels * input_w if batch_loop else grad_input.numel()
    block_size = 256

    with torch_device_fn.device(grad_output.device):
        _upsample_nearest_exact1d_backward_kernel[(triton.cdiv(numel, block_size),)](
            grad_output,
            grad_input,
            numel,
            channels,
            output_w,
            input_w,
            *grad_output.stride(),
            *grad_input.stride(),
            backward_scale,
            BATCH=batch,
            BATCH_LOOP=batch_loop,
            IS_FP64=grad_output.dtype == torch.float64,
            IS_UINT8=grad_output.dtype == torch.uint8,
            MAX_CONTRIBUTORS=max_contributors,
            BLOCK_SIZE=block_size,
        )
    return grad_input


def _upsample_nearest_exact1d_backward(
    grad_output: torch.Tensor,
    output_size: Sequence[int],
    input_size: Sequence[int],
    scales: Optional[float] = None,
) -> torch.Tensor:
    logger.debug("GEMS _UPSAMPLE_NEAREST_EXACT1D_BACKWARD")
    return _upsample_nearest_exact1d_backward_impl(
        grad_output, output_size, input_size, scales, None
    )


def _upsample_nearest_exact1d_backward_grad_input(
    grad_output: torch.Tensor,
    output_size: Sequence[int],
    input_size: Sequence[int],
    scales: Optional[float] = None,
    *,
    grad_input: torch.Tensor,
) -> torch.Tensor:
    logger.debug("GEMS _UPSAMPLE_NEAREST_EXACT1D_BACKWARD.GRAD_INPUT")
    return _upsample_nearest_exact1d_backward_impl(
        grad_output, output_size, input_size, scales, grad_input
    )
