# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _absolute_kernel(x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask)
    zero = x * 0
    is_neg = x < zero
    y = tl.where(is_neg, -x, x)
    tl.store(out_ptr + offsets, y, mask=mask)


@triton.jit
def _absolute_complex_kernel(ri_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    base = offsets * 2
    re = tl.load(ri_ptr + base, mask=mask)
    im = tl.load(ri_ptr + base + 1, mask=mask)
    y = tl.sqrt(re * re + im * im)
    tl.store(out_ptr + offsets, y, mask=mask)


def absolute(input: torch.Tensor):
    logger.debug("GEMS ABSOLUTE")
    x = input.contiguous()
    n_elements = x.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    with torch_device_fn.device(input.device):
        if x.is_complex():
            ri = torch.view_as_real(x).contiguous()
            out_dtype = x.real.dtype
            out = torch.empty(x.shape, dtype=out_dtype, device=x.device)
            _absolute_complex_kernel[grid](ri, out, n_elements, BLOCK_SIZE=1024)
            return out
        else:
            out = torch.empty_like(x)
            _absolute_kernel[grid](x, out, n_elements, BLOCK_SIZE=1024)
            return out
