# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(
    is_tensor=[True, True, True, False], promotion_methods=[(0, 1, 2, "DEFAULT")]
)
@triton.jit
def addcdiv_kernel(x, t1, t2, value):
    return x + value * (t1 / t2)


def addcdiv_(inp, tensor1, tensor2, value=1.0):
    logger.debug("GEMS ADDCDIV_")
    addcdiv_kernel(inp, tensor1, tensor2, value, out0=inp)
    return inp
