# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2026, Yuanzhu Li
# Copyright 2026, BAAI (Beijing Academy of Artificial Intelligence)
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def atanh_kernel_(
    x_ptr, n_elements, BLOCK_SIZE: tl.constexpr, COMPUTE_IN_FP32: tl.constexpr
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)

    if COMPUTE_IN_FP32:
        xf = x.to(tl.float32)
        numerator = 1.0 + xf
        denominator = 1.0 - xf
        val = 0.5 * tl.log(numerator / denominator)
        y = val.to(x.dtype)
    else:
        xf = x
        numerator = 1.0 + xf
        denominator = 1.0 - xf
        val = 0.5 * tl.log(numerator / denominator)
        y = val

    tl.store(x_ptr + offsets, y, mask=mask)


def atanh_(*args, **kwargs):
    logger.debug("GEMS ATANH_")
    x = None
    if len(args) >= 1 and isinstance(args[0], torch.Tensor):
        x = args[0]
    else:
        x = kwargs.get("input", kwargs.get("self", None))
    if not isinstance(x, torch.Tensor):
        raise TypeError("atanh_ expects a single Tensor argument")

    if not x.is_contiguous():
        raise ValueError("Input tensor must be contiguous")
    if not x.is_floating_point():
        raise TypeError("atanh_ only supports floating point tensors")

    n_elements = x.numel()
    if n_elements == 0:
        return x

    use_fp32 = x.dtype in (torch.float16, torch.bfloat16)

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        atanh_kernel_[grid](x, n_elements, BLOCK_SIZE=1024, COMPUTE_IN_FP32=use_fp32)
    return x
