# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils.random_utils import (
    philox_backend_seed_offset,
    uint_to_uniform_float,
)
from flag_gems.utils.shape_utils import volume

logger = logging.getLogger(__name__)

# Binomial sampling split (on the *effective* mean n * min(p, 1 - p)):
#   mean <= INVERSE_MAX : inverse-transform (one uniform + CDF accumulation)
#   mean  > INVERSE_MAX : normal approximation with continuity correction
INVERSE_MAX = 30.0
# INVERSE_CAP bounds the CDF loop; covers mean=INVERSE_MAX well past 3 sigma.
INVERSE_CAP = 128
# Fixed per-element philox stride so binomial() never reads input on the host.
PHILOX_STRIDE = 4
# BLOCK_SIZE=2048 with NUM_WARPS=8 gives good occupancy for the elementwise
# sampling kernel across the benchmarked shapes without register spilling.
BLOCK_SIZE = 2048
NUM_WARPS = 8


@triton.jit
def high_precision_fast_sin_cos(x):
    two_pi = 6.283185307179586
    x = x - two_pi * tl.floor(x / two_pi + 0.5)
    x2 = x * x
    s_c0 = 0.99999999999999999999
    s_c1 = -0.16666666666666666654
    s_c2 = 0.00833333333333332876
    s_c3 = -0.00019841269841269616
    s_c4 = 2.755731922398589e-6
    s_c5 = -2.505210838544172e-8
    sin_x = x * (
        s_c0 + x2 * (s_c1 + x2 * (s_c2 + x2 * (s_c3 + x2 * (s_c4 + x2 * s_c5))))
    )
    c_c0 = 1.0
    c_c1 = -0.49999999999999999983
    c_c2 = 0.04166666666666666636
    c_c3 = -0.00138888888888888742
    c_c4 = 2.4801587301587299e-5
    c_c5 = -2.755731922398581e-7
    cos_x = c_c0 + x2 * (c_c1 + x2 * (c_c2 + x2 * (c_c3 + x2 * (c_c4 + x2 * c_c5))))
    return sin_x, cos_x


@triton.jit
def binomial_inverse(count, pe, mean_bound, seed, c0, c1, z, CAP: tl.constexpr):
    """Inverse-transform sampling: one uniform, accumulate CDF until s >= u.

    Samples from Binomial(count, pe) with pe = min(p, 1 - p) so the mean stays
    small. Uses the recurrence P(k) = P(k-1) * (count - k + 1) / k * pe / (1 - pe).
    """
    r0, r1, r2, r3 = tl.philox(seed, c0, c1, z, z)
    u = uint_to_uniform_float(r0)
    qe = tl.maximum(1.0 - pe, 1e-10)
    ratio_pq = pe / qe
    # P(X = 0) = (1 - pe) ** count
    p = tl.exp(count * tl.log(qe))
    s = p
    k = (count * 0).to(tl.int32)
    iters = tl.minimum(
        (mean_bound + 6.0 * tl.sqrt(mean_bound + 1.0) + 4.0).to(tl.int32), CAP
    )
    iters = tl.maximum(iters, 1)
    for _ in tl.range(0, iters):
        active = (u > s) & (k.to(tl.float32) < count)
        k = tl.where(active, k + 1, k)
        kf = tl.where(active, k.to(tl.float32), 1.0)
        ratio = (count - kf + 1.0) / kf * ratio_pq
        p = tl.where(active, p * ratio, p)
        s = tl.where(active, s + p, s)
    return k.to(tl.float32)


@triton.jit
def binomial_normal(count, pe, seed, c0, c1, z):
    """Normal approximation with continuity correction (Box-Muller)."""
    r0, r1, r2, r3 = tl.philox(seed, c0, c1, z, z)
    u1 = tl.maximum(uint_to_uniform_float(r0), 1e-10)
    u2 = uint_to_uniform_float(r1)
    radius = tl.sqrt(-2.0 * tl.log(u1))
    _, cos_t = high_precision_fast_sin_cos(6.283185307179586 * u2)
    g = radius * cos_t
    mean = count * pe
    std = tl.sqrt(mean * (1.0 - pe))
    y = mean + g * std
    y = tl.minimum(tl.maximum(y, 0.0), count)
    return tl.floor(y + 0.5)


@libentry()
@triton.jit(do_not_specialize=["philox_seed", "philox_offset", "N"])
def binomial_kernel(
    count_ptr,
    prob_ptr,
    out_ptr,
    N,
    philox_seed,
    philox_offset,
    BLOCK: tl.constexpr,
    CAP: tl.constexpr,
    STRIDE: tl.constexpr,
    IMAX: tl.constexpr,
):
    philox_seed = philox_seed.to(tl.int64)
    philox_offset = philox_offset.to(tl.int64)
    offs = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    count = tl.maximum(
        tl.load(count_ptr + offs, mask=mask, other=0.0).to(tl.float32), 0.0
    )
    prob = tl.load(prob_ptr + offs, mask=mask, other=0.0).to(tl.float32)
    prob = tl.minimum(tl.maximum(prob, 0.0), 1.0)
    # Sample in the "effective" space with pe = min(p, 1 - p) to keep the mean
    # small, then flip via the symmetry Binomial(n, p) = n - Binomial(n, 1 - p).
    flip = prob > 0.5
    pe = tl.where(flip, 1.0 - prob, prob)

    mean = count * pe
    bmean = tl.max(mean)

    counter = philox_offset + offs.to(tl.int64) * STRIDE
    c0 = (counter & 0xFFFFFFFF).to(tl.uint32)
    c1 = ((counter >> 32) & 0xFFFFFFFF).to(tl.uint32)
    z = c0 * 0
    if bmean <= IMAX:
        x = binomial_inverse(count, pe, bmean, philox_seed, c0, c1, z, CAP)
    else:
        inv = binomial_inverse(count, pe, IMAX * 1.0, philox_seed, c0, c1, z, CAP)
        nrm = binomial_normal(count, pe, philox_seed, c0, c1, z)
        x = tl.where(mean <= IMAX, inv, nrm)

    result = tl.where(flip, count - x, x)
    tl.store(out_ptr + offs, result, mask=mask)


def _binomial_launch(count, prob, out, generator=None):
    n = volume(out.shape)
    if n == 0:
        return out

    buf = out if out.is_contiguous() else torch.empty_like(out)
    increment = triton.cdiv(n * PHILOX_STRIDE, 4)
    philox_seed, philox_offset = philox_backend_seed_offset(
        increment, generator=generator
    )
    grid = triton.cdiv(n, BLOCK_SIZE)
    with torch_device_fn.device(out.device):
        binomial_kernel[(grid,)](
            count,
            prob,
            buf,
            n,
            philox_seed,
            philox_offset,
            BLOCK=BLOCK_SIZE,
            CAP=INVERSE_CAP,
            STRIDE=PHILOX_STRIDE,
            IMAX=INVERSE_MAX,
            num_warps=NUM_WARPS,
        )
    if buf is not out:
        out.copy_(buf.view(out.shape))
    return out


def _prepare_inputs(count, prob):
    assert count.dtype in (
        torch.float16,
        torch.bfloat16,
        torch.float32,
        torch.float64,
    ), f"Unsupported dtype: {count.dtype}"
    shape = torch.broadcast_shapes(count.shape, prob.shape)
    count = count.broadcast_to(shape).contiguous()
    prob = prob.broadcast_to(shape).to(count.dtype).contiguous()
    return count, prob, shape


def binomial(count, prob, generator=None):
    """
    Draws samples from a binomial distribution with the number of trials given
    by ``count`` and the success probability given by ``prob`` (elementwise).
    """
    logger.debug("GEMS BINOMIAL")
    count, prob, shape = _prepare_inputs(count, prob)
    out = torch.empty(shape, dtype=count.dtype, device=count.device)
    return _binomial_launch(count, prob, out, generator=generator)


def binomial_out(count, prob, generator=None, *, out):
    logger.debug("GEMS BINOMIAL_OUT")
    count, prob, shape = _prepare_inputs(count, prob)
    return _binomial_launch(count, prob, out, generator=generator)
