# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

logger = logging.getLogger(__name__)


def _compute_broadcast_shape(tensors):
    """Compute the broadcast shape from a list of tensors."""
    max_ndim = max(t.ndim for t in tensors)

    padded_shapes = []
    for t in tensors:
        shape = [1] * (max_ndim - t.ndim) + list(t.shape)
        padded_shapes.append(shape)

    broadcast_shape = []
    for i in range(max_ndim):
        # A size of 1 is broadcastable to any other size (including 0), so it
        # never determines the result. The result is the unique non-1 size,
        # or 1 if every input is 1 at this dim. Two distinct non-1 sizes (e.g.
        # 0 and 3, or 2 and 3) are incompatible and must raise.
        dim_size = 1
        for shape in padded_shapes:
            if shape[i] == 1:
                continue
            if dim_size == 1:
                dim_size = shape[i]
            elif dim_size != shape[i]:
                raise RuntimeError(
                    "The size of tensor a ("
                    f"{dim_size}) must match the size of tensor b "
                    f"({shape[i]}) at non-singleton dimension {i}"
                )
        broadcast_shape.append(dim_size)

    return tuple(broadcast_shape)


def broadcast_tensors(*tensors):
    """Broadcasts the given tensors according to broadcasting semantics."""
    logger.debug("GEMS BROADCAST_TENSORS")

    # Handle case where tensors are passed as a list
    if len(tensors) == 1 and isinstance(tensors[0], (list, tuple)):
        tensors = tuple(tensors[0])

    if not tensors:
        return []

    if len(tensors) == 1:
        return [tensors[0].expand(1) if tensors[0].ndim == 0 else tensors[0].clone()]

    broadcast_shape = _compute_broadcast_shape(tensors)
    results = []

    for tensor in tensors:
        # Pad shape to match broadcast shape
        if tensor.ndim < len(broadcast_shape):
            pad_dims = len(broadcast_shape) - tensor.ndim
            new_shape = [1] * pad_dims + list(tensor.shape)
            tensor = tensor.reshape(new_shape)

        # If already the right shape, just copy
        if tensor.shape == broadcast_shape:
            result = tensor.contiguous()
        else:
            # Use PyTorch's expand for broadcasting
            # This creates a view without copying data, then we clone to make it contiguous
            result = tensor.expand(broadcast_shape).contiguous()

        results.append(result)

    return results
