# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def bucketize_kernel(
    inp_ptr,
    boundaries_ptr,
    out_ptr,
    n_elements,
    n_boundaries,
    right: tl.constexpr,
    N_BOUNDARY_ITERS: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tle.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    # Load input value directly using pointer arithmetic
    # For contiguous row-major tensors, offset i corresponds to element i
    inp_val = tl.load(inp_ptr + offsets, mask=mask, other=0)

    # Binary search for each value
    # boundaries is a 1-D tensor of length n_boundaries
    n_boundaries_i32 = tl.full([BLOCK_SIZE], n_boundaries, dtype=tl.int32)

    # Create scalar tensors for binary search loop
    zero = tl.zeros([BLOCK_SIZE], dtype=tl.int32)
    lo = zero
    hi = n_boundaries_i32

    # Special cases handled in wrapper, but we still handle them in kernel for completeness
    # For values below first boundary, return 0
    # For values >= last boundary, return n_boundaries

    if right:
        # upper bound: find first index where boundaries[i] > val
        # If no such index, return n_boundaries
        # Binary search: find rightmost position where boundaries[pos] <= val
        for _ in range(N_BOUNDARY_ITERS):
            mid = tl.minimum((lo + hi) // 2, n_boundaries_i32 - 1)
            mid_val = tl.load(boundaries_ptr + mid)
            cond = mid_val <= inp_val
            lo = tl.where(cond, mid + 1, lo)
            hi = tl.where(cond, hi, mid)
        result = lo
    else:
        # lower bound: find first index where boundaries[i] >= val (for <= comparison, boundaries[i-1] < val
        # <= boundaries[i])
        # Actually: boundaries[i-1] < val <= boundaries[i]
        # So we want the first i where boundaries[i] >= val, but we need val > boundaries[i-1]
        # If val <= boundaries[0], return 0
        # Otherwise find first i where boundaries[i] >= val
        for _ in range(N_BOUNDARY_ITERS):
            mid = tl.minimum((lo + hi) // 2, n_boundaries_i32 - 1)
            mid_val = tl.load(boundaries_ptr + mid)
            cond = mid_val < inp_val
            lo = tl.where(cond, mid + 1, lo)
            hi = tl.where(cond, hi, mid)
        result = lo

    tl.store(out_ptr + offsets, result, mask=mask)


def bucketize(input, boundaries, *, out_int32=False, right=False):
    logger.debug("GEMS BUCKETIZE")
    if boundaries.numel() == 0:
        # Empty boundaries - all zeros
        if out_int32:
            return torch.zeros_like(input, dtype=torch.int32)
        return torch.zeros_like(input, dtype=torch.int64)

    output_dtype = torch.int32 if out_int32 else torch.int64
    output = torch.empty_like(input, dtype=output_dtype)

    n_elements = input.numel()
    n_boundaries = boundaries.numel()
    search_iterations = math.ceil(math.log2(n_boundaries + 1))

    # Keep one fixed tile size to avoid compiling shape-specific variants.
    BLOCK_SIZE = 1024
    num_warps = 4
    num_ctas = triton.cdiv(n_elements, BLOCK_SIZE)

    # Ensure contiguous and flatten the tensors
    input_flat = input.flatten()
    output_flat = output.flatten()
    boundaries = boundaries.contiguous()

    grid = (num_ctas, 1, 1)
    bucketize_kernel[grid](
        input_flat,
        boundaries,
        output_flat,
        n_elements,
        n_boundaries,
        right,
        search_iterations,
        BLOCK_SIZE,
        num_warps=num_warps,
    )

    # Reshape output back to original shape
    output = output.reshape(input.shape)

    return output
