# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry, libtuner

logger = logging.getLogger(__name__)

CHALF_CONFIGS = [
    triton.Config({"BLOCK_SIZE": 512}, num_warps=4),
    triton.Config({"BLOCK_SIZE": 1024}, num_warps=4),
    triton.Config({"BLOCK_SIZE": 1024}, num_warps=8),
    triton.Config({"BLOCK_SIZE": 2048}, num_warps=8),
    triton.Config({"BLOCK_SIZE": 4096}, num_warps=8),
]


@libentry()
@libtuner(
    configs=CHALF_CONFIGS,
    key=["n_elements"],
)
@triton.jit
def chalf_real_kernel(in_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    # Real input -> complex32 output: real part = input, imaginary part = 0.
    # out_ptr is a view_as_real (float16) buffer with interleaved real/imag slots.
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    base = offsets * 2
    val = tl.load(in_ptr + offsets, mask=mask)
    zero = tl.zeros([BLOCK_SIZE], dtype=tl.float32)

    tl.store(out_ptr + base, val, mask=mask)
    tl.store(out_ptr + base + 1, zero, mask=mask)


@libentry()
@libtuner(
    configs=CHALF_CONFIGS,
    key=["n_elements"],
)
@triton.jit
def chalf_complex_kernel(in_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    # Complex input -> complex32 output: cast real/imag slots down to float16.
    # Both in_ptr and out_ptr are view_as_real buffers; n_elements counts float slots.
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    val = tl.load(in_ptr + offsets, mask=mask)
    tl.store(out_ptr + offsets, val, mask=mask)


def chalf(input: torch.Tensor, memory_format=None) -> torch.Tensor:
    logger.debug("GEMS CHALF")

    if input.is_complex():
        # Resolve conj bit so view_as_real reflects the logical values.
        if input.is_conj():
            input = input.resolve_conj()
        src = input if input.is_contiguous() else input.contiguous()
        output = torch.empty(src.shape, dtype=torch.complex32, device=src.device)

        in_real = torch.view_as_real(src)
        out_real = torch.view_as_real(output)
        n_elements = in_real.numel()

        grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
        chalf_complex_kernel[grid](in_real, out_real, n_elements)
        return output

    # Real (or integer) input -> complex32 with zero imaginary part.
    src = input if input.is_contiguous() else input.contiguous()
    output = torch.empty(src.shape, dtype=torch.complex32, device=src.device)

    out_real = torch.view_as_real(output)
    n_elements = src.numel()

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    chalf_real_kernel[grid](src, out_real, n_elements)
    return output
