# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)


@triton.jit
def _qerror_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    # candidate pair 1
    xmin1,
    scale1,
    inv1,
    # candidate pair 2
    xmin2,
    scale2,
    inv2,
    qmax,
    BLOCK_SIZE: tl.constexpr,
):
    """Compute the sum of squared quantization errors for two candidate
    (xmin, xmax) pairs in a single pass and atomically accumulate them into
    out_ptr[0] and out_ptr[1] respectively.

    The quantization follows PyTorch's ``choose_qparams_optimized`` reference:
        q     = clamp(round((x - xmin) / scale), 0, qmax)
        x_rec = q * scale + xmin
    where ``xmin`` and ``scale`` have already been rounded to half precision on
    the host side to match the reference numerics.
    """
    pid = tl.program_id(0)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offs < n_elements
    x = tl.load(x_ptr + offs, mask=mask, other=0.0).to(tl.float32)

    # pair 1
    q1 = tl_extra_shim.nearbyint((x - xmin1) * inv1)
    q1 = tl.minimum(tl.maximum(q1, 0.0), qmax)
    xr1 = q1 * scale1 + xmin1
    d1 = x - xr1
    err1 = tl.sum(tl.where(mask, d1 * d1, 0.0))

    # pair 2
    q2 = tl_extra_shim.nearbyint((x - xmin2) * inv2)
    q2 = tl.minimum(tl.maximum(q2, 0.0), qmax)
    xr2 = q2 * scale2 + xmin2
    d2 = x - xr2
    err2 = tl.sum(tl.where(mask, d2 * d2, 0.0))

    tl.atomic_add(out_ptr + 0, err1)
    tl.atomic_add(out_ptr + 1, err2)


def _half_round(value):
    # Emulate PyTorch casting xmin / scale to at::Half before computing error.
    return float(
        torch.tensor(value, dtype=torch.float32).to(torch.float16).to(torch.float32)
    )


def _make_params(xmin, xmax, qmax):
    xmin_h = _half_round(xmin)
    data_range = xmax - xmin_h
    if data_range == 0.0:
        scale = 1.0
    else:
        scale = _half_round(data_range / qmax)
    inv = 0.0 if scale == 0.0 else 1.0 / scale
    return xmin_h, scale, inv


def _compute_errors(x, params1, params2, qmax, out_buf):
    n_elements = x.numel()
    out_buf.zero_()
    # 1024 gives good occupancy for the 1D reduction over the input tensor
    # across the shapes exercised here; the kernel is memory-bound so a single
    # fixed block size is sufficient without autotuning.
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(n_elements, BLOCK_SIZE),)
    xmin1, scale1, inv1 = params1
    xmin2, scale2, inv2 = params2
    _qerror_kernel[grid](
        x,
        out_buf,
        n_elements,
        xmin1,
        scale1,
        inv1,
        xmin2,
        scale2,
        inv2,
        float(qmax),
        BLOCK_SIZE=BLOCK_SIZE,
    )
    # Read both accumulated losses back in a single host transfer to keep the
    # number of device syncs in the search loop to a minimum.
    losses = out_buf.tolist()
    return float(losses[0]), float(losses[1])


def choose_qparams_optimized(input, numel, n_bins, ratio, bit_width):
    logger.debug("GEMS CHOOSE_QPARAMS_OPTIMIZED")

    # The aten reference is float32-only; reject other dtypes explicitly.
    assert input.dtype == torch.float32, (
        "choose_qparams_optimized only supports float32 input, " f"got {input.dtype}"
    )

    x = input.contiguous().view(-1)[:numel].to(torch.float32)

    xmin = float(x.min().item())
    xmax = float(x.max().item())
    stepsize = (xmax - xmin) / n_bins
    min_bins = int(n_bins * (1.0 - ratio))
    qmax = float((1 << bit_width) - 1)

    out_buf = torch.zeros(2, dtype=torch.float32, device=x.device)

    cur_min, cur_max = xmin, xmax
    params0 = _make_params(cur_min, cur_max, qmax)
    cur_loss, _ = _compute_errors(x, params0, params0, qmax, out_buf)

    threshold = min_bins * stepsize
    while cur_min + threshold < cur_max:
        params1 = _make_params(cur_min + stepsize, cur_max, qmax)
        params2 = _make_params(cur_min, cur_max - stepsize, qmax)
        loss1, loss2 = _compute_errors(x, params1, params2, qmax, out_buf)

        if cur_loss < loss1 and cur_loss < loss2:
            break

        if loss1 < loss2:
            cur_min = cur_min + stepsize
            cur_loss = loss1
        else:
            cur_max = cur_max - stepsize
            cur_loss = loss2

    result_dtype = input.dtype if input.dtype == torch.float32 else torch.float32
    max_out = torch.tensor([cur_max], dtype=result_dtype, device=input.device)
    min_out = torch.tensor([cur_min], dtype=result_dtype, device=input.device)
    return max_out, min_out
