# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def clamp_max_func(x, maxi):
    return tl.minimum(maxi, x.to(tl.float32))


def clamp_max(A, max_value):
    logger.debug("GEMS CLAMP_MAX")
    return clamp_max_func(A, max_value)


def clamp_max_(A, max_value):
    logger.debug("GEMS CLAMP_MAX_")
    return clamp_max_func(A, max_value, out0=A)
