# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import tl_extra_shim
from flag_gems.utils.libentry import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _lstm_cell_forward_kernel(
    pre_gates_ptr,  # (batch, 4 * hidden) pre-activation gates i|f|g|o
    c_prev_ptr,  # (batch, hidden) incoming cell state
    i_ptr,  # (batch, hidden) output: input-gate activation
    f_ptr,  # (batch, hidden) output: forget-gate activation
    g_ptr,  # (batch, hidden) output: cell-gate activation
    o_ptr,  # (batch, hidden) output: output-gate activation
    c_ptr,  # (batch, hidden) output: new cell state
    h_ptr,  # (batch, hidden) output: new hidden state
    hidden_size: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """One LSTM timestep forward: apply gate nonlinearities and the cell/hidden
    recurrence. One program per batch row; BLOCK_SIZE covers the hidden dim."""
    batch_idx = tl.program_id(0)
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = offsets < hidden_size

    gate_base = pre_gates_ptr + batch_idx * 4 * hidden_size
    i_pre = tl.load(gate_base + 0 * hidden_size + offsets, mask=mask, other=0.0).to(
        tl.float32
    )
    f_pre = tl.load(gate_base + 1 * hidden_size + offsets, mask=mask, other=0.0).to(
        tl.float32
    )
    g_pre = tl.load(gate_base + 2 * hidden_size + offsets, mask=mask, other=0.0).to(
        tl.float32
    )
    o_pre = tl.load(gate_base + 3 * hidden_size + offsets, mask=mask, other=0.0).to(
        tl.float32
    )

    c_prev = tl.load(
        c_prev_ptr + batch_idx * hidden_size + offsets, mask=mask, other=0.0
    ).to(tl.float32)

    i = tl.sigmoid(i_pre)
    f = tl.sigmoid(f_pre)
    g = tl_extra_shim.tanh(g_pre)
    o = tl.sigmoid(o_pre)

    c = f * c_prev + i * g
    h = o * tl_extra_shim.tanh(c)

    row = batch_idx * hidden_size + offsets
    tl.store(i_ptr + row, i, mask=mask)
    tl.store(f_ptr + row, f, mask=mask)
    tl.store(g_ptr + row, g, mask=mask)
    tl.store(o_ptr + row, o, mask=mask)
    tl.store(c_ptr + row, c, mask=mask)
    tl.store(h_ptr + row, h, mask=mask)


@libentry()
@triton.jit
def _lstm_cell_backward_kernel(
    i_ptr,  # (batch, hidden) cached input-gate activation
    f_ptr,  # (batch, hidden) cached forget-gate activation
    g_ptr,  # (batch, hidden) cached cell-gate activation
    o_ptr,  # (batch, hidden) cached output-gate activation
    c_ptr,  # (batch, hidden) cached new cell state at this step
    c_prev_ptr,  # (batch, hidden) cached incoming cell state at this step
    dh_ptr,  # (batch, hidden) in: recurrent hidden-state gradient
    dc_ptr,  # (batch, hidden) in/out: cell-state gradient carried across steps
    grad_out_ptr,  # (batch, hidden) upstream gradient into this step's output
    grad_gates_ptr,  # (batch, 4 * hidden) out: gradient w.r.t. pre-activation gates
    has_grad_out: tl.constexpr,
    hidden_size: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """One LSTM timestep backward: the chain-rule gate-gradient math. Consumes
    the recurrent gradients dh/dc, emits grad_gates (di|df|dg|do pre-activation)
    and overwrites dc with the gradient carried to the previous cell state."""
    batch_idx = tl.program_id(0)
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = offsets < hidden_size
    row = batch_idx * hidden_size + offsets

    i = tl.load(i_ptr + row, mask=mask, other=0.0).to(tl.float32)
    f = tl.load(f_ptr + row, mask=mask, other=0.0).to(tl.float32)
    g = tl.load(g_ptr + row, mask=mask, other=0.0).to(tl.float32)
    o = tl.load(o_ptr + row, mask=mask, other=0.0).to(tl.float32)
    c_t = tl.load(c_ptr + row, mask=mask, other=0.0).to(tl.float32)
    c_prev = tl.load(c_prev_ptr + row, mask=mask, other=0.0).to(tl.float32)

    dh = tl.load(dh_ptr + row, mask=mask, other=0.0).to(tl.float32)
    dc = tl.load(dc_ptr + row, mask=mask, other=0.0).to(tl.float32)
    if has_grad_out:
        dh = dh + tl.load(grad_out_ptr + row, mask=mask, other=0.0).to(tl.float32)

    tanh_c = tl_extra_shim.tanh(c_t)
    # h_t = o * tanh(c_t)
    do = dh * tanh_c
    do_pre = do * o * (1.0 - o)
    # cell-state gradient: tanh path from h plus the recurrent dc
    dc = dc + dh * o * (1.0 - tanh_c * tanh_c)

    di = dc * g
    df = dc * c_prev
    dg = dc * i
    di_pre = di * i * (1.0 - i)
    df_pre = df * f * (1.0 - f)
    dg_pre = dg * (1.0 - g * g)

    # gradient carried to the previous cell state
    dc_prev = dc * f

    gate_base = grad_gates_ptr + batch_idx * 4 * hidden_size
    tl.store(gate_base + 0 * hidden_size + offsets, di_pre, mask=mask)
    tl.store(gate_base + 1 * hidden_size + offsets, df_pre, mask=mask)
    tl.store(gate_base + 2 * hidden_size + offsets, dg_pre, mask=mask)
    tl.store(gate_base + 3 * hidden_size + offsets, do_pre, mask=mask)
    tl.store(dc_ptr + row, dc_prev, mask=mask)


def _lstm_block_size(hidden_size: int) -> int:
    # BLOCK_SIZE spans the hidden dim in one program; clamp to a sane range so
    # small hidden sizes still use a full warp and large ones stay within limits.
    block = triton.next_power_of_2(hidden_size)
    return max(32, min(block, 1024))


def cudnn_rnn_backward(
    input: torch.Tensor,
    weight: list,
    weight_stride0: int,
    weight_buf: torch.Tensor,
    hx: torch.Tensor,
    cx: torch.Tensor,
    output: torch.Tensor,
    grad_output_in: torch.Tensor,
    grad_hy_in: torch.Tensor,
    grad_cy_in: torch.Tensor,
    mode: int,
    hidden_size: int,
    proj_size: int,
    num_layers: int,
    batch_first: bool,
    dropout: float,
    train: bool,
    bidirectional: bool,
    batch_sizes: list,
    dropout_state: torch.Tensor,
    reserve: torch.Tensor,
    output_mask: list,
):
    """Compute gradients for cuDNN RNN backward pass.

    cuDNN's RNN backward relies on an opaque ``reserve`` buffer and packed
    ``weight_buf`` that cannot be reconstructed outside cuDNN, so this FlagGems
    implementation recomputes the backward analytically via BPTT. The
    LSTM-specific core computation -- the gate nonlinearities in the forward
    recompute and the chain-rule gate-gradient math in the backward -- runs in
    Triton kernels (:func:`_lstm_cell_forward_kernel` /
    :func:`_lstm_cell_backward_kernel`); the dense gate/weight matmuls stay on
    the BLAS path.

    Currently supports single-layer unidirectional LSTM (mode=2) only.

    Args:
        input: Input tensor (seq_len, batch, input_size) or (batch, seq_len, input_size) if batch_first
        weight: List of weight/bias tensors [w_ih, w_hh, b_ih, b_hh, ...]
        weight_stride0: Number of tensors per layer (typically 4 with biases)
        weight_buf: Flattened weight buffer (unused in this implementation)
        hx: Initial hidden state (num_layers, batch, hidden_size)
        cx: Initial cell state (num_layers, batch, hidden_size) for LSTM
        output: Forward output (unused, recomputed)
        grad_output_in: Gradient w.r.t. output (seq_len, batch, hidden_size)
        grad_hy_in: Gradient w.r.t. final hidden state (num_layers, batch, hidden_size)
        grad_cy_in: Gradient w.r.t. final cell state (num_layers, batch, hidden_size)
        mode: RNN mode (0=RNN_RELU, 1=RNN_TANH, 2=LSTM, 3=GRU)
        hidden_size: Hidden state dimension
        proj_size: Projection size (0 for no projection)
        num_layers: Number of RNN layers
        batch_first: If True, input is (batch, seq, input_size)
        dropout: Dropout probability
        train: Training mode flag
        bidirectional: Bidirectional RNN flag
        batch_sizes: Packed sequence batch sizes (empty for unpacked)
        dropout_state: Dropout state tensor
        reserve: cuDNN reserve workspace (unused in this implementation)
        output_mask: Mask for which gradients to compute [grad_input, grad_hx, grad_cx, grad_weight]

    Returns:
        Tuple of (grad_input, grad_hx, grad_cx, grad_weight_list)
    """
    logger.debug("GEMS CUDNN_RNN_BACKWARD")

    # Validate supported configuration
    if mode != 2:
        raise NotImplementedError("Only LSTM (mode=2) is currently supported")
    if num_layers != 1:
        raise NotImplementedError("Only single-layer RNN is currently supported")
    if bidirectional:
        raise NotImplementedError("Bidirectional RNN is not currently supported")
    if proj_size != 0:
        raise NotImplementedError("Projection is not currently supported")
    if batch_sizes:
        raise NotImplementedError("Packed sequences are not currently supported")

    # Extract weights for the single layer.
    w_ih, w_hh, b_ih, b_hh = weight[0], weight[1], weight[2], weight[3]

    # Work in (seq, batch, *) layout regardless of batch_first.
    inp = input.transpose(0, 1).contiguous() if batch_first else input.contiguous()
    seq_len, batch_size, _ = inp.shape

    # Compute in float32 for numerical stability, then cast results back.
    orig_dtype = input.dtype
    compute_dtype = torch.float32
    inp_c = inp.to(compute_dtype)
    w_ih_c = w_ih.to(compute_dtype)
    w_hh_c = w_hh.to(compute_dtype)
    b_ih_c = b_ih.to(compute_dtype)
    b_hh_c = b_hh.to(compute_dtype)
    h = hx.squeeze(0).to(compute_dtype).contiguous()  # (batch, hidden)
    c = cx.squeeze(0).to(compute_dtype).contiguous()

    device = inp_c.device
    BLOCK_SIZE = _lstm_block_size(hidden_size)
    grid = (batch_size,)

    def _empty():
        return torch.empty(
            (batch_size, hidden_size), device=device, dtype=compute_dtype
        )

    # --- Forward recomputation, caching per-step gate activations for BPTT. ---
    # The dense (x @ W_ih^T + h @ W_hh^T) projection is BLAS; the Triton kernel
    # applies the gate nonlinearities and the cell/hidden recurrence.
    h_prev_list = [h]
    c_prev_list = [c]
    i_list, f_list, g_list, o_list, c_new_list = [], [], [], [], []
    for t in range(seq_len):
        pre_gates = (
            inp_c[t] @ w_ih_c.t() + b_ih_c + h @ w_hh_c.t() + b_hh_c
        ).contiguous()  # (batch, 4H)
        i_t, f_t, g_t, o_t = _empty(), _empty(), _empty(), _empty()
        c_t, h_t = _empty(), _empty()
        _lstm_cell_forward_kernel[grid](
            pre_gates,
            c,
            i_t,
            f_t,
            g_t,
            o_t,
            c_t,
            h_t,
            hidden_size,
            BLOCK_SIZE,
        )
        i_list.append(i_t)
        f_list.append(f_t)
        g_list.append(g_t)
        o_list.append(o_t)
        c_new_list.append(c_t)
        h_prev_list.append(h_t)
        c_prev_list.append(c_t)
        h, c = h_t, c_t

    # --- Backward through time. Gate-gradient chain rule runs in Triton; the
    # input/weight/recurrent matmuls stay on the BLAS path. ---
    grad_input_seq = torch.zeros_like(inp_c) if output_mask[0] else None
    grad_w_ih_acc = torch.zeros_like(w_ih_c)
    grad_w_hh_acc = torch.zeros_like(w_hh_c)
    grad_b_ih_acc = torch.zeros_like(b_ih_c)
    grad_b_hh_acc = torch.zeros_like(b_hh_c)

    # Seed recurrent gradients from grad_hy / grad_cy (final-step upstream).
    dh = (
        grad_hy_in.squeeze(0).to(compute_dtype).contiguous()
        if grad_hy_in is not None
        else torch.zeros((batch_size, hidden_size), device=device, dtype=compute_dtype)
    )
    dc = (
        grad_cy_in.squeeze(0).to(compute_dtype).contiguous()
        if grad_cy_in is not None
        else torch.zeros((batch_size, hidden_size), device=device, dtype=compute_dtype)
    )
    grad_out_seq = None
    if grad_output_in is not None:
        go = grad_output_in.transpose(0, 1) if batch_first else grad_output_in
        grad_out_seq = go.to(compute_dtype).contiguous()

    zero_go = torch.empty(0, device=device, dtype=compute_dtype)
    for t in range(seq_len - 1, -1, -1):
        grad_gates = torch.empty(
            (batch_size, 4 * hidden_size), device=device, dtype=compute_dtype
        )
        has_grad_out = grad_out_seq is not None
        _lstm_cell_backward_kernel[grid](
            i_list[t],
            f_list[t],
            g_list[t],
            o_list[t],
            c_new_list[t],
            c_prev_list[t],
            dh,
            dc,  # updated in place to hold dc for the previous step
            grad_out_seq[t] if has_grad_out else zero_go,
            grad_gates,
            has_grad_out,
            hidden_size,
            BLOCK_SIZE,
        )

        # Weight / bias gradients accumulate over time (BLAS).
        grad_w_ih_acc += grad_gates.t() @ inp_c[t]
        grad_w_hh_acc += grad_gates.t() @ h_prev_list[t]
        grad_b_ih_acc += grad_gates.sum(dim=0)
        grad_b_hh_acc += grad_gates.sum(dim=0)

        # Input gradient and recurrent hidden-state gradient (BLAS).
        if grad_input_seq is not None:
            grad_input_seq[t] = grad_gates @ w_ih_c
        dh = grad_gates @ w_hh_c

    # dh / dc now hold gradients w.r.t. the initial hidden / cell states.
    grad_hx_out = dh.unsqueeze(0).to(orig_dtype) if output_mask[1] else None
    grad_cx_out = dc.unsqueeze(0).to(orig_dtype) if output_mask[2] else None

    if output_mask[0]:
        grad_input = grad_input_seq.to(orig_dtype)
        if batch_first:
            grad_input = grad_input.transpose(0, 1).contiguous()
    else:
        grad_input = None

    if output_mask[3]:
        grad_weight = [
            grad_w_ih_acc.to(orig_dtype),
            grad_w_hh_acc.to(orig_dtype),
            grad_b_ih_acc.to(orig_dtype),
            grad_b_hh_acc.to(orig_dtype),
        ]
    else:
        grad_weight = []

    return grad_input, grad_hx_out, grad_cx_out, grad_weight
