# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


def conv_transpose2d_output_size(
    in_size: int,
    kernel_size: int,
    stride: int,
    padding: int,
    output_padding: int,
    dilation: int,
) -> int:
    """
    Determines the output size of a 2D transposed convolution operation.

    Args:
        in_size: Input size.
        kernel_size: Kernel size.
        stride: Stride.
        padding: Padding.
        output_padding: Additional output padding.
        dilation: Dilation.

    Returns:
        Output size of 2D transposed convolution.
    """
    return (
        (in_size - 1) * stride
        - 2 * padding
        + dilation * (kernel_size - 1)
        + output_padding
        + 1
    )


@libentry()
@triton.jit
def conv_transpose2d_kernel(
    input_pointer,
    weight_pointer,
    output_pointer,
    in_n,
    in_c,
    input_height,
    input_width,
    out_c,
    weight_c,
    weight_height,
    weight_width,
    out_height,
    out_width,
    input_n_stride,
    input_c_stride,
    input_height_stride,
    input_width_stride,
    weight_n_stride,
    weight_c_stride,
    weight_height_stride,
    weight_width_stride,
    output_n_stride,
    output_c_stride,
    output_height_stride,
    output_width_stride,
    stride_height: tl.constexpr,
    stride_width: tl.constexpr,
    padding_height: tl.constexpr,
    padding_width: tl.constexpr,
    dilation_height: tl.constexpr,
    dilation_width: tl.constexpr,
    output_padding_height: tl.constexpr,
    output_padding_width: tl.constexpr,
    groups: tl.constexpr,
    BLOCK_NI_HO_WO: tl.constexpr,
    BLOCK_CI: tl.constexpr,
    BLOCK_CO: tl.constexpr,
):
    pid_ni_ho_wo = tl.program_id(0)
    pid_co = tl.program_id(1)
    pid_group = tl.program_id(2)

    # Calculate in_n, output_height, output_width values in kernel
    ni_ho_wo_offset = pid_ni_ho_wo * BLOCK_NI_HO_WO + tl.arange(0, BLOCK_NI_HO_WO)
    ni_ho_offset = ni_ho_wo_offset // out_width
    in_n_point_value = ni_ho_offset // out_height
    output_height_point_value = ni_ho_offset % out_height
    output_width_point_value = ni_ho_wo_offset % out_width

    # For conv transpose: input channels become output channels, and vice versa
    # Weight shape is (in_c, out_c/groups, kH, kW) for transpose
    out_per_group_c = out_c // groups

    # Load the input and weight pointers
    # For conv transpose: the weight is (in_c, out_c_per_group, kH, kW)
    output_c_offset = pid_co * BLOCK_CO + tl.arange(0, BLOCK_CO)

    # Input pointer: (n, in_c, h, w)
    input_pointer += (
        input_n_stride * in_n_point_value + input_c_stride * pid_group * weight_c
    )[:, None]

    # Weight pointer: (in_c, out_c_per_group, kH, kW)
    # For conv transpose, we need to flip the weight in the backward pass
    # But here we directly compute the transpose convolution
    weight_pointer += (
        weight_n_stride * pid_group * out_per_group_c
        + (weight_n_stride * output_c_offset)[None, :]
    )

    accum = tl.zeros((BLOCK_NI_HO_WO, BLOCK_CO), dtype=tl.float32)

    BLOCK_CI_COUNT = (weight_c + BLOCK_CI - 1) // BLOCK_CI
    for hwk in range(weight_height * weight_width * BLOCK_CI_COUNT):
        c = (hwk % BLOCK_CI_COUNT) * BLOCK_CI
        hw = hwk // BLOCK_CI_COUNT
        h = hw // weight_width
        w = hw % weight_width

        input_c_offset = c + tl.arange(0, BLOCK_CI)

        # For conv transpose, the input position calculation is different
        # We calculate which input positions contribute to this output position
        # h_input = (h_out - h * dilation + padding) / stride
        # This is equivalent to computing the convolution with flipped kernel

        # Conv transpose: output position comes from input position plus kernel offset
        input_height_offset = (
            output_height_point_value - h * dilation_height + padding_height
        ) // stride_height
        input_width_offset = (
            output_width_point_value - w * dilation_width + padding_width
        ) // stride_width

        # Check if the computed input position is valid
        input_height_offset = (
            output_height_point_value * stride_height
            + h * dilation_height
            - padding_height
        )
        input_width_offset = (
            output_width_point_value * stride_width + w * dilation_width - padding_width
        )

        curr_input_pointer = (
            input_pointer
            + (input_c_stride * input_c_offset)[None, :]
            + (input_height_stride * input_height_offset)[:, None]
            + (input_width_stride * input_width_offset)[:, None]
        )

        # Weight: flip both spatial dimensions
        flipped_h = weight_height - 1 - h
        flipped_w = weight_width - 1 - w
        curr_weight_pointer = (
            weight_pointer
            + (weight_c_stride * input_c_offset)[:, None]
            + (weight_height_stride * flipped_h)
            + (weight_width_stride * flipped_w)
        )

        input_mask = (
            (in_n_point_value < in_n)[:, None]
            & (input_c_offset < weight_c)[None, :]
            & (0 <= input_height_offset)[:, None]
            & (input_height_offset < input_height)[:, None]
            & (0 <= input_width_offset)[:, None]
            & (input_width_offset < input_width)[:, None]
        )
        weight_mask = (input_c_offset < weight_c)[:, None] & (
            output_c_offset < out_per_group_c
        )[None, :]

        input_block = tl.load(curr_input_pointer, mask=input_mask)
        weight_block = tl.load(curr_weight_pointer, mask=weight_mask)

        accum += tl.dot(input_block, weight_block, allow_tf32=False)

    output_pointer += (
        (output_n_stride * in_n_point_value)[:, None]
        + (output_c_stride * (pid_group * out_per_group_c + output_c_offset))[None, :]
        + (output_height_stride * output_height_point_value)[:, None]
        + (output_width_stride * output_width_point_value)[:, None]
    )
    output_mask = (
        (in_n_point_value < in_n)[:, None]
        & (output_c_offset < out_per_group_c)[None, :]
        & (output_height_point_value < out_height)[:, None]
        & (output_width_point_value < out_width)[:, None]
    )

    tl.store(output_pointer, accum, mask=output_mask)


class CudnnConvolutionTranspose(torch.autograd.Function):
    @staticmethod
    def forward(
        ctx,
        input,
        weight,
        padding,
        output_padding,
        stride,
        dilation,
        groups,
        benchmark,
        deterministic,
        allow_tf32,
    ):
        logger.debug("GEMS CUDNN_CONV_TRANSPOSE")
        assert weight.ndim == 4, "Weights must be 4D for conv_transpose2d"
        assert input.ndim == 4, "Input must be 4D for conv_transpose2d"

        # Parse stride
        if isinstance(stride, (list, tuple)):
            stride_height, stride_width = (
                stride[0],
                stride[1] if len(stride) > 1 else stride[0],
            )
        else:
            stride_height = stride_width = stride

        # Parse padding
        if isinstance(padding, (list, tuple)):
            padding_height, padding_width = (
                padding[0],
                padding[1] if len(padding) > 1 else padding[0],
            )
        else:
            padding_height = padding_width = padding

        # Parse output_padding
        if isinstance(output_padding, (list, tuple)):
            output_padding_height = output_padding[0]
            output_padding_width = (
                output_padding[1] if len(output_padding) > 1 else output_padding[0]
            )
        else:
            output_padding_height = output_padding_width = output_padding

        # Parse dilation
        if isinstance(dilation, (list, tuple)):
            dilation_height, dilation_width = (
                dilation[0],
                dilation[1] if len(dilation) > 1 else dilation[0],
            )
        else:
            dilation_height = dilation_width = dilation

        in_n, in_c, input_height, input_width = input.shape
        out_c, weight_c, weight_height, weight_width = weight.shape

        # For conv transpose: weight shape is (out_c, in_c, kH, kW)
        # We need to transpose to (in_c, out_c/groups, kH, kW) for the computation
        assert in_c == weight_c * groups, (
            f"Incompatible input channels {in_c} and weight {weight_c}"
            f" with groups {groups}"
        )

        out_height = conv_transpose2d_output_size(
            input_height,
            weight_height,
            stride_height,
            padding_height,
            output_padding_height,
            dilation_height,
        )
        out_width = conv_transpose2d_output_size(
            input_width,
            weight_width,
            stride_width,
            padding_width,
            output_padding_width,
            dilation_width,
        )

        output_dtype = input.dtype
        output = torch.empty(
            (in_n, out_c, out_height, out_width),
            device=input.device,
            dtype=output_dtype,
        )

        # Transpose weight from (out_c, in_c, kH, kW) to (in_c, out_c/groups, kH, kW)
        # This is needed because the conv_transpose2d_kernel expects weights in this format
        if groups == 1:
            weight_T = weight.transpose(0, 1).contiguous()
        else:
            # For grouped convolution transpose, we need special handling
            weight_reshaped = weight.reshape(
                groups, out_c // groups, weight_c, weight_height, weight_width
            )
            weight_T = (
                weight_reshaped.transpose(1, 2)
                .reshape(in_c, out_c // groups, weight_height, weight_width)
                .contiguous()
            )

        # Grid configuration
        grid = lambda META: (
            triton.cdiv(in_n * out_height * out_width, META["BLOCK_NI_HO_WO"]),
            triton.cdiv(int(out_c // groups), META["BLOCK_CO"]),
            groups,
        )

        conv_transpose2d_kernel[grid](
            input,
            weight_T,
            output,
            in_n,
            in_c,
            input_height,
            input_width,
            out_c,
            weight_c,
            weight_height,
            weight_width,
            out_height,
            out_width,
            *input.stride(),
            *weight_T.stride(),
            *output.stride(),
            stride_height,
            stride_width,
            padding_height,
            padding_width,
            dilation_height,
            dilation_width,
            output_padding_height,
            output_padding_width,
            groups=groups,
            BLOCK_NI_HO_WO=16,
            BLOCK_CI=32,
            BLOCK_CO=32,
        )

        ctx.save_for_backward(input, weight)
        ctx.stride = (stride_height, stride_width)
        ctx.padding = (padding_height, padding_width)
        ctx.output_padding = (output_padding_height, output_padding_width)
        ctx.dilation = (dilation_height, dilation_width)
        ctx.groups = groups
        ctx.weight_info = (out_c, weight_c, weight_height, weight_width)
        ctx.input_info = (in_n, in_c, input_height, input_width)

        return output

    @staticmethod
    def backward(ctx, grad_output):
        logger.debug("GEMS CUDNN_CONV_TRANSPOSE VJP")
        input, weight = ctx.saved_tensors

        stride_height, stride_width = ctx.stride
        padding_height, padding_width = ctx.padding
        output_padding_height, output_padding_width = ctx.output_padding
        dilation_height, dilation_width = ctx.dilation
        groups = ctx.groups

        out_c, weight_c, weight_height, weight_width = ctx.weight_info
        in_n, in_c, input_height, input_width = ctx.input_info

        # The backward of conv transpose is regular conv
        # with flipped weights and adjusted parameters
        revert_padding_height = dilation_height * (weight_height - 1) - padding_height
        revert_padding_width = dilation_width * (weight_width - 1) - padding_width

        # Flip the weight
        weight_flip = torch.flip(weight, dims=[2, 3]).contiguous()

        # Transpose weight for grouped conv
        if groups != 1:
            weight_flip = weight_flip.reshape(
                groups, out_c // groups, weight_c, weight_height, weight_width
            )
            weight_flip = (
                weight_flip.transpose(1, 2)
                .reshape(in_c, out_c // groups, weight_height, weight_width)
                .contiguous()
            )
        else:
            weight_flip = weight_flip.transpose(0, 1).contiguous()

        # Compute input gradient using regular conv
        grad_input = torch.nn.functional.conv2d(
            grad_output,
            weight_flip,
            stride=stride_height,
            padding=(revert_padding_height, revert_padding_width),
            dilation=(dilation_height, dilation_width),
            groups=groups,
        )

        # Compute weight gradient
        grad_weight = torch.nn.functional.conv2d(
            input.transpose(0, 1),
            grad_output.transpose(0, 1),
            stride=stride_height,
            padding=padding_height,
            dilation=dilation_height,
            groups=groups,
        ).transpose(0, 1)

        return (
            grad_input,
            grad_weight,
            None,  # padding
            None,  # output_padding
            None,  # stride
            None,  # dilation
            None,  # groups
            None,  # benchmark
            None,  # deterministic
            None,  # allow_tf32
        )


def cudnn_convolution_transpose(
    input: torch.Tensor,
    weight: torch.Tensor,
    padding=None,
    output_padding=None,
    stride=1,
    dilation=1,
    groups=1,
    benchmark=False,
    deterministic=False,
    allow_tf32=True,
):
    # Handle default values
    if padding is None:
        padding = (0, 0)
    elif isinstance(padding, int):
        padding = (padding, padding)

    if output_padding is None:
        output_padding = (0, 0)
    elif isinstance(output_padding, int):
        output_padding = (output_padding, output_padding)

    if isinstance(stride, int):
        stride = (stride, stride)
    elif isinstance(stride, tuple) and len(stride) == 1:
        stride = (stride[0], stride[0])

    if isinstance(dilation, int):
        dilation = (dilation, dilation)
    elif isinstance(dilation, tuple) and len(dilation) == 1:
        dilation = (dilation[0], dilation[0])

    return CudnnConvolutionTranspose.apply(
        input,
        weight,
        padding,
        output_padding,
        stride,
        dilation,
        groups,
        benchmark,
        deterministic,
        allow_tf32,
    )
