# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn


@triton.jit
def floor_kernel_(
    x_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
    IS_FP32: tl.constexpr,
    IS_FP16: tl.constexpr,
    IS_BF16: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)

    # Apply floor only for floating-point dtypes; otherwise, no-op
    out = x
    if IS_FP32:
        out = tl.floor(x)
    elif IS_FP16:
        x_fp32 = tl.cast(x, tl.float32)
        out = tl.cast(tl.floor(x_fp32), tl.float16)
    elif IS_BF16:
        x_fp32 = tl.cast(x, tl.float32)
        out = tl.cast(tl.floor(x_fp32), tl.bfloat16)

    tl.store(x_ptr + offsets, out, mask=mask)


def floor_(input):
    x = input
    if not isinstance(x, torch.Tensor):
        raise TypeError("floor_ expects a torch.Tensor.")
    if x.is_complex():
        raise TypeError("floor_ is not supported for complex tensors.")
    if not x.is_contiguous():
        raise ValueError(
            "floor_ Triton kernel currently supports only contiguous tensors."
        )

    n_elements = x.numel()
    if n_elements == 0:
        return x

    dtype = x.dtype
    IS_FP32 = dtype == torch.float32
    IS_FP16 = dtype == torch.float16
    IS_BF16 = dtype == torch.bfloat16

    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    with torch_device_fn.device(x.device):
        floor_kernel_[grid](
            x,
            n_elements,
            BLOCK_SIZE=BLOCK_SIZE,
            IS_FP32=IS_FP32,
            IS_FP16=IS_FP16,
            IS_BF16=IS_BF16,
        )
    return x
