# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGe
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def hardsigmoid_backward_func(grad_output, self):
    # hardsigmoid: y = clamp(x/6 + 0.5, 0, 1)
    # gradient: dy/dx = 1/6 when -3 < x < 3, else 0
    # => grad_input = grad_output * (|self| < 3) / 6
    grad_output_fp32 = grad_output.to(tl.float32)
    self_fp32 = self.to(tl.float32)
    in_range = (self_fp32 > -3.0) & (self_fp32 < 3.0)
    result = grad_output_fp32 * in_range / 6.0
    return result.to(grad_output.dtype)


def hardsigmoid_backward(grad_output, self):
    logger.debug("GEMS HARDSIGMOID_BACKWARD")
    return hardsigmoid_backward_func(grad_output, self)
