# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List, Union

import torch

logger = logging.getLogger(__name__)


def hsplit(
    A: torch.Tensor, indices_or_sections: Union[int, List[int]]
) -> List[torch.Tensor]:
    r"""Split a tensor into multiple sub-tensors horizontally (column-wise).

    This is equivalent to :func:`torch.tensor_split` with ``dim=1`` if ``A`` has
    2 or more dimensions, or with ``dim=0`` if ``A`` has 1 dimension.

    Args:
        A (torch.Tensor): Input tensor.
        indices_or_sections (int or List[int]): If an integer, split into that many
            equal parts. If a list of indices, split at those positions.

    Returns:
        List[torch.Tensor]: List of tensor views.
    """
    logger.debug("GEMS HSPLIT")

    # hsplit works on dim=1 for 2D+ tensors, dim=0 for 1D tensors
    if A.ndim == 0:
        raise RuntimeError("hsplit expects at least a 1-dimensional tensor")

    split_dim = 1 if A.ndim >= 2 else 0

    # Use tensor_split which handles both int and list cases
    return torch.tensor_split(A, indices_or_sections, dim=split_dim)
