# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging
import warnings

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

_SUPPORTED_DTYPES = (
    torch.float32,
    torch.float64,
    torch.complex64,
    torch.complex128,
)
_CPU_KEYSET = torch._C.DispatchKeySet(torch._C.DispatchKey.CPU)
_DEVICE_KEYSET = torch._C.DispatchKeySet(
    getattr(torch._C.DispatchKey, runtime.device.dispatch_key)
)

# Save the vendor kernels before ``use_gems`` installs its temporary ATen
# implementations.  Matrix square root is a library-composition operator:
# eigendecomposition and GEMM should remain in the vendor library, while the
# eigenvalue transform below is the generated Triton kernel.  Calling these
# saved handles also keeps complex tensors away from Triton kernels that do not
# accept complex pointers.
#
# This module is imported on older PyTorch versions too, even though its public
# registration is version-gated.  Guard the API and schema here so those
# environments keep importing FlagGems normally.
_CAN_CAPTURE_NATIVE_KERNELS = hasattr(torch.library, "get_kernel") and hasattr(
    torch.ops.aten, "linalg_matrix_sqrth"
)

if _CAN_CAPTURE_NATIVE_KERNELS:
    _NATIVE_ADD = torch.library.get_kernel(
        torch.ops.aten.add.Tensor, runtime.device.dispatch_key
    )
    _NATIVE_BMM = torch.library.get_kernel(
        torch.ops.aten.bmm.default, runtime.device.dispatch_key
    )
    _NATIVE_CONJ_PHYSICAL = torch.library.get_kernel(
        torch.ops.aten.conj_physical.default, runtime.device.dispatch_key
    )
    _NATIVE_COPY = torch.library.get_kernel(
        torch.ops.aten.copy_.default, runtime.device.dispatch_key
    )
    _NATIVE_EIGH = torch.library.get_kernel(
        torch.ops.aten._linalg_eigh.default, runtime.device.dispatch_key
    )
    _NATIVE_MM = torch.library.get_kernel(
        torch.ops.aten.mm.default, runtime.device.dispatch_key
    )
    _NATIVE_MUL_SCALAR = torch.library.get_kernel(
        torch.ops.aten.mul.Scalar, runtime.device.dispatch_key
    )
    _NATIVE_MUL_TENSOR = torch.library.get_kernel(
        torch.ops.aten.mul.Tensor, runtime.device.dispatch_key
    )
    _NATIVE_RESIZE = torch.library.get_kernel(
        torch.ops.aten.resize_.default, runtime.device.dispatch_key
    )


def _native_keyset(tensor):
    return _CPU_KEYSET if tensor.device.type == "cpu" else _DEVICE_KEYSET


def _native_mul(left, right):
    return _NATIVE_MUL_TENSOR.call_boxed(_native_keyset(left), left, right)


def _native_scale(tensor, scale):
    return _NATIVE_MUL_SCALAR.call_boxed(_native_keyset(tensor), tensor, scale)


def _native_add(left, right):
    return _NATIVE_ADD.call_boxed(_native_keyset(left), left, right, alpha=1)


def _native_matmul(left, right):
    keyset = _native_keyset(left)
    if left.ndim == 2:
        return _NATIVE_MM.call_boxed(keyset, left, right)

    n = left.shape[-1]
    batch_count = left.numel() // (n * n)
    left_3d = left.as_strided(
        (batch_count, n, n),
        (n * n, left.stride(-2), left.stride(-1)),
    )
    right_3d = right.as_strided(
        (batch_count, n, n),
        (n * n, right.stride(-2), right.stride(-1)),
    )
    result = _NATIVE_BMM.call_boxed(keyset, left_3d, right_3d)
    return result.reshape(left.shape)


def _native_adjoint(tensor):
    transposed = tensor.transpose(-2, -1)
    if not tensor.is_complex():
        return transposed
    # A CUDA-only redispatch skips the Conjugate fallback key. Materialize the
    # conjugation before the native matmul/add so complex inputs keep mH semantics.
    return _NATIVE_CONJ_PHYSICAL.call_boxed(_native_keyset(tensor), transposed)


def _native_copy_impl(keyset, dst, src, non_blocking=False):
    return _NATIVE_COPY.call_boxed(keyset, dst, src, non_blocking)


def _native_eigh(inp):
    # The native CUDA eigensolver internally calls aten::copy_.  Under a full
    # use_gems context that nested call would otherwise re-enter FlagGems.
    # Override only copy_ for the duration of the vendor-library call, then
    # restore the surrounding dispatcher registration.
    native_copy_lib = torch.library.Library("aten", "IMPL")
    native_copy_lib.impl(
        "copy_",
        _native_copy_impl,
        runtime.device.dispatch_key,
        with_keyset=True,
        allow_override=True,
    )
    try:
        return _NATIVE_EIGH.call_boxed(_native_keyset(inp), inp, "L", True)
    finally:
        native_copy_lib._destroy()


@libentry()
@triton.jit
def _clamp_sqrt_kernel(eigenvalues, output, n_elements, BLOCK_SIZE: tl.constexpr):
    offsets = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    values = tl.load(eigenvalues + offsets, mask=mask, other=0.0)
    result = tl.sqrt(tl.maximum(values, 0.0))
    tl.store(output + offsets, result, mask=mask)


def _validate_input(inp):
    if inp.ndim < 2:
        raise RuntimeError(
            "linalg.matrix_sqrth: The input tensor must have at least 2 dimensions."
        )
    if inp.shape[-2] != inp.shape[-1]:
        raise RuntimeError(
            "linalg.matrix_sqrth: A must be batches of square matrices, "
            f"but they are {inp.shape[-2]} by {inp.shape[-1]} matrices"
        )
    if inp.dtype not in _SUPPORTED_DTYPES:
        raise RuntimeError(
            "linalg.matrix_sqrth: Expected a floating point or complex tensor "
            f"with dtype float32, float64, complex64, or complex128, but got {inp.dtype}"
        )


def linalg_matrix_sqrth(inp):
    """Compute the principal square root of a Hermitian positive-definite matrix."""
    logger.debug("GEMS LINALG_MATRIX_SQRTH")
    _validate_input(inp)

    if inp.shape[-1] == 0:
        return inp.clone()

    # ATen reads only the lower triangle (UPLO="L") and assumes that it
    # describes a symmetric/Hermitian positive-definite matrix.
    eigenvalues, eigenvectors = _native_eigh(inp)

    sqrt_eigenvalues = torch.empty_like(eigenvalues)
    n_elements = eigenvalues.numel()
    if n_elements != 0:
        block_size = 256
        grid = (triton.cdiv(n_elements, block_size),)
        with torch_device_fn.device(eigenvalues.device):
            _clamp_sqrt_kernel[grid](
                eigenvalues,
                sqrt_eigenvalues,
                n_elements,
                BLOCK_SIZE=block_size,
            )

    scaled_eigenvectors = _native_mul(eigenvectors, sqrt_eigenvalues.unsqueeze(-2))
    result = _native_matmul(scaled_eigenvectors, _native_adjoint(eigenvectors))

    # Match ATen's final Hermitian projection, which removes reconstruction
    # roundoff from the opposite triangle.
    return _native_scale(_native_add(result, _native_adjoint(result)), 0.5)


def linalg_matrix_sqrth_out(inp, *, out):
    logger.debug("GEMS LINALG_MATRIX_SQRTH_OUT")
    result = linalg_matrix_sqrth(inp)

    if out.dtype != result.dtype:
        raise RuntimeError(
            f"Expected out tensor to have dtype {result.dtype}, but got {out.dtype} instead"
        )
    if out.device != result.device:
        raise RuntimeError(
            f"Expected out tensor to be on device {result.device}, but got {out.device}"
        )
    if tuple(out.shape) != tuple(result.shape):
        if out.numel() != 0:
            warnings.warn(
                "An output with one or more elements was resized since it had "
                f"shape {list(out.shape)}, which does not match the required "
                f"output shape {list(result.shape)}.",
                UserWarning,
                stacklevel=2,
            )
        _NATIVE_RESIZE.call_boxed(
            _native_keyset(out), out, result.shape, memory_format=None
        )

    _NATIVE_COPY.call_boxed(_native_keyset(out), out, result, False)
    return out
