# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils.triton_lang_extension import program_id

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def householder_product_kernel(
    A,
    tau,
    Q,
    M,
    N,
    K,
    a_batch_stride,
    q_batch_stride,
    tau_batch_stride,
    stride_row,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Compute Q = H(0) * H(1) * ... * H(k-1) where H(i) = I - tau[i] * v[i] * v[i]^T.

    Each program handles one batch element and a block of BLOCK_N columns.
    Vectorized over rows (BLOCK_M covers all M rows) and columns (BLOCK_N).
    """
    pid_batch = program_id(0)
    pid_col = tl.program_id(1)

    col_start = pid_col * BLOCK_N
    cols = col_start + tl.arange(0, BLOCK_N)
    col_mask = cols < N
    rows = tl.arange(0, BLOCK_M)
    row_mask = rows < M

    a_base = A + pid_batch * a_batch_stride
    q_base = Q + pid_batch * q_batch_stride
    tau_base = tau + pid_batch * tau_batch_stride

    # Pointers for Q block [BLOCK_M, BLOCK_N]
    q_ptrs = q_base + rows[:, None] * stride_row + cols[None, :]
    mask_2d = row_mask[:, None] & col_mask[None, :]

    # Initialize Q[:, cols] = I[:, cols]
    identity = tl.where(rows[:, None] == cols[None, :], 1.0, 0.0)
    tl.store(q_ptrs, identity, mask=mask_2d)

    # Apply Householder reflectors from k = K-1 down to 0
    for k_idx in range(K - 1, -1, -1):
        tau_k = tl.load(tau_base + k_idx)

        # Build v vector: v[i]=0 for i<k, v[k]=1, v[i]=A[i,k] for i>k
        a_col = tl.load(a_base + rows * stride_row + k_idx, mask=row_mask, other=0.0)
        v = tl.where(rows > k_idx, a_col, tl.where(rows == k_idx, 1.0, 0.0))

        # Load Q block
        q_block = tl.load(q_ptrs, mask=mask_2d, other=0.0)

        # Compute dots = v^T @ Q_block, shape [BLOCK_N]
        dots = tl.sum(v[:, None] * q_block, axis=0)

        # Update: Q_block -= tau_k * v * dots^T
        q_block = q_block - tau_k * (v[:, None] * dots[None, :])
        tl.store(q_ptrs, q_block, mask=mask_2d)


def linalg_householder_product(A, tau):
    """Computes the product of Householder matrices (orgqr).

    Given the output of torch.geqrf (Householder vectors A and scalars tau),
    computes Q = H(0) * H(1) * ... * H(k-1) where H(i) = I - tau[i] * v[i] * v[i]^T.

    Args:
        A: Input matrix of shape (..., m, n) containing Householder vectors.
        tau: Vector of shape (..., k) where k <= n.

    Returns:
        Q: Orthogonal matrix of shape (..., m, n).
    """
    logger.debug("GEMS LINALG_HOUSEHOLDER_PRODUCT")

    # Only float32 and float64 supported: householder_product requires real floating point
    assert A.dtype in (
        torch.float32,
        torch.float64,
    ), f"linalg_householder_product only supports float32 and float64, got {A.dtype}"

    shape = A.shape
    if len(shape) < 2:
        raise ValueError("A must be at least 2D")

    m = shape[-2]
    n = shape[-1]
    k = tau.shape[-1]

    # Handle batch dimensions
    if len(shape) == 2:
        batch_size = 1
        A_work = A.unsqueeze(0).contiguous()
        tau_work = tau.unsqueeze(0).contiguous()
    else:
        batch_dims = shape[:-2]
        batch_size = 1
        for d in batch_dims:
            batch_size *= d
        A_work = A.reshape(batch_size, m, n).contiguous()
        tau_work = tau.reshape(batch_size, k).contiguous()

    # Allocate output Q
    Q = torch.empty_like(A_work)

    # Compute strides
    a_batch_stride = A_work.stride(0)
    q_batch_stride = Q.stride(0)
    tau_batch_stride = tau_work.stride(0)
    stride_row = A_work.stride(1)  # n (columns per row)

    # Block sizes: BLOCK_M covers all rows, BLOCK_N tiles columns for parallelism
    BLOCK_M = triton.next_power_of_2(m)
    # Use smaller BLOCK_N to increase column parallelism on larger matrices
    BLOCK_N = min(triton.next_power_of_2(n), 32)
    num_col_blocks = triton.cdiv(n, BLOCK_N)

    grid = (batch_size, num_col_blocks)

    householder_product_kernel[grid](
        A_work,
        tau_work,
        Q,
        m,
        n,
        k,
        a_batch_stride,
        q_batch_stride,
        tau_batch_stride,
        stride_row,
        BLOCK_M=BLOCK_M,
        BLOCK_N=BLOCK_N,
    )

    # Reshape output to original batch shape
    Q = Q.reshape(shape)

    return Q
