# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def logit_kernel(
    x_ptr,
    n_elements,
    eps,
    has_eps: tl.constexpr,
    COMPUTE_FP32: tl.constexpr,
    COMPUTE_FP64: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)

    if COMPUTE_FP32:
        xc = x.to(tl.float32)
        if has_eps:
            xc = tl.maximum(xc, eps)
            xc = tl.minimum(xc, 1.0 - eps)
        y = tl.log(xc / (1.0 - xc))
        out = y.to(x.dtype)
    elif COMPUTE_FP64:
        xc = x
        if has_eps:
            xc = tl.maximum(xc, eps)
            xc = tl.minimum(xc, 1.0 - eps)
        out = tl.log(xc / (1.0 - xc))
    else:
        xc = x
        if has_eps:
            xc = tl.maximum(xc, eps)
            xc = tl.minimum(xc, 1.0 - eps)
        out = tl.log(xc / (1.0 - xc))

    tl.store(x_ptr + offsets, out, mask=mask)


def logit_(*args, **kwargs):
    logger.debug("GEMS LOGIT_")
    if len(args) == 0:
        raise TypeError("logit_ expected at least 1 argument (got 0)")
    x = args[0]
    eps = None
    if len(args) > 1:
        eps = args[1]
    if "eps" in kwargs:
        eps = kwargs["eps"]

    if not isinstance(x, torch.Tensor):
        raise TypeError("logit_ expects a torch.Tensor as the first argument")
    if not x.is_floating_point():
        raise TypeError("logit_ expects a floating point tensor")

    has_eps = eps is not None
    eps_value = float(eps) if has_eps else 0.0

    needs_copy_back = not x.is_contiguous()
    buf = x if not needs_copy_back else x.contiguous()

    n_elements = buf.numel()
    if n_elements == 0:
        return x

    dtype = buf.dtype
    compute_in_fp32 = dtype in (torch.float16, torch.bfloat16)
    compute_in_fp64 = dtype == torch.float64

    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    with torch_device_fn.device(x.device):
        logit_kernel[grid](
            buf,
            n_elements,
            eps_value,
            has_eps=has_eps,
            COMPUTE_FP32=compute_in_fp32,
            COMPUTE_FP64=compute_in_fp64,
            BLOCK_SIZE=BLOCK_SIZE,
        )

    if needs_copy_back:
        x.copy_(buf)

    return x
