# Generated by KernelGen: logical_xor_ v5.0

import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "ALWAYS_BOOL")])
@triton.jit
def logical_xor_func_(x, y):
    return tl.where((x != 0) ^ (y != 0), 1, 0)


def logical_xor_(A, B):
    logger.debug("GEMS LOGICAL_XOR_")
    logical_xor_func_(A, B, out0=A)
    return A
