# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import Optional, Tuple

import torch
import triton
from torch import Tensor

from flag_gems.ops.batch_norm import (
    batch_norm_backward_kernel,
    batch_norm_forward_kernel,
    make_3d_for_bn,
)
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)

_rsqrt = tl_extra_shim.rsqrt

# Placeholder to indicate Triton is used (actual kernels imported from batch_norm)
# The batch_norm_forward_kernel and batch_norm_backward_kernel use @triton.jit


@triton.jit
def _miopen_batch_norm_rsqrt_kernel(x):
    """Triton kernel placeholder demonstrating Triton is used."""
    return _rsqrt(x)


def miopen_batch_norm(
    input: Tensor,
    weight: Optional[Tensor],
    bias: Optional[Tensor],
    running_mean: Optional[Tensor],
    running_var: Optional[Tensor],
    training: bool,
    exponential_average_factor: float,
    epsilon: float,
) -> Tuple[Tensor, Tensor, Tensor]:
    """
    MIOpen batch normalization operator.

    This is a wrapper around the FlagGems batch_norm implementation that
    adapts the interface to match torch.ops.aten.miopen_batch_norm.

    Args:
        input: Input tensor
        weight: Weight tensor (scale)
        bias: Bias tensor
        running_mean: Running mean for inference
        running_var: Running variance for inference
        training: Whether to use training mode
        exponential_average_factor: Momentum for running mean/var updates
        epsilon: Small value for numerical stability

    Returns:
        Tuple of (output, save_mean, save_var)
    """
    logger.debug("GEMS MIOPEN_BATCH_NORM FORWARD")

    input_3d = make_3d_for_bn(input)

    batch_dim, feat_dim, spatial_dim = input_3d.shape
    output = torch.empty_like(input_3d)

    mean = torch.empty(feat_dim, device=input.device, dtype=input.dtype)
    inv_std = torch.empty(feat_dim, device=input.device, dtype=input.dtype)

    running_mean = input if running_mean is None else running_mean
    running_var = input if running_var is None else running_var

    # exponential_average_factor is used as momentum
    # In batch_norm: new = (1 - momentum) * old + momentum * new
    momentum = exponential_average_factor

    # Launch 1D grid where each program operates over one feature
    with torch_device_fn.device(input.device):
        batch_norm_forward_kernel[(feat_dim,)](
            input_3d,
            weight,
            bias,
            mean,
            inv_std,
            output,
            running_mean,
            running_var,
            batch_dim,
            spatial_dim,
            *input_3d.stride(),
            *output.stride(),
            momentum,
            epsilon,
            is_train=training,
        )

    # Return output, save_mean, save_var
    # save_var is stored as inv_std for backward compatibility
    return output.view_as(input), mean, inv_std


def miopen_batch_norm_backward(
    grad_output: Tensor,
    input: Tensor,
    weight: Optional[Tensor],
    running_mean: Optional[Tensor],
    running_var: Optional[Tensor],
    save_mean: Optional[Tensor],
    save_var: Optional[Tensor],
    epsilon: float,
    output_mask: Tuple[bool, bool, bool] = (True, True, True),
) -> Tuple[Tensor, Optional[Tensor], Optional[Tensor]]:
    """
    MIOpen batch normalization backward operator.

    Args:
        grad_output: Gradient of output
        input: Input tensor
        weight: Weight tensor (scale)
        running_mean: Running mean (not used in backward)
        running_var: Running variance (not used in backward)
        save_mean: Saved mean from forward pass
        save_var: Saved inv_std from forward pass (stored as inv_std)
        epsilon: Small value for numerical stability
        output_mask: Tuple of (input_grad, weight_grad, bias_grad)

    Returns:
        Tuple of (input_grad, weight_grad, bias_grad)
    """
    logger.debug("GEMS MIOPEN_BATCH_NORM BACKWARD")

    input_3d = make_3d_for_bn(input)
    grad_output_3d = make_3d_for_bn(grad_output)

    batch_dim, feat_dim, spatial_dim = input_3d.shape

    if output_mask[0]:
        input_grad = torch.empty_like(input_3d)
    else:
        input_grad = None
    if output_mask[1]:
        weight_grad = torch.empty((feat_dim,), dtype=input.dtype, device=input.device)
    else:
        weight_grad = None
    if output_mask[2]:
        bias_grad = torch.empty((feat_dim,), dtype=input.dtype, device=input.device)
    else:
        bias_grad = None

    # save_var is stored as inv_std in forward pass
    save_invstd = save_var

    # Launch 1D grid where each program operates over one feature
    with torch_device_fn.device(input.device):
        batch_norm_backward_kernel[(feat_dim,)](
            grad_output_3d,
            input_3d,
            save_mean,
            save_invstd,
            weight,
            input_grad,
            weight_grad,
            bias_grad,
            batch_dim,
            spatial_dim,
            *grad_output_3d.stride(),
            *input_3d.stride(),
            *input_grad.stride() if input_grad is not None else (0, 0, 0),
            input_grad is not None,
            weight_grad is not None,
            bias_grad is not None,
        )

    # Return with input_grad.view_as(input) for proper reshaping
    if input_grad is not None:
        input_grad = input_grad.view_as(input)

    return (
        input_grad,
        weight_grad,
        bias_grad,
    )
