# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def rad2deg_func(x):
    # 180.0 / pi
    return (x.to(tl.float32) * 57.29577951308232).to(x.dtype)


def rad2deg(A):
    logger.debug("GEMS RAD2DEG")
    return rad2deg_func(A)


def rad2deg_(A):
    logger.debug("GEMS RAD2DEG_")
    rad2deg_func(A, out0=A)
    return A
