# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def reflection_pad3d_backward_kernel(
    grad_ptr,
    out_ptr,
    N,
    C,
    D_in,
    H_in,
    W_in,
    D_out,
    H_out,
    W_out,
    pad_d0,
    pad_d1,
    pad_h0,
    pad_h1,
    pad_w0,
    pad_w1,
    stride_grad_n,
    stride_grad_c,
    stride_grad_d,
    stride_grad_h,
    stride_grad_w,
    stride_out_n,
    stride_out_c,
    stride_out_d,
    stride_out_h,
    stride_out_w,
    BLOCK_DHW: tl.constexpr,
):
    pid_bc = tle.program_id(1)
    pid_dhw = tle.program_id(0)

    pid_n = pid_bc % N
    pid_c = pid_bc // N

    # Compute output position (grad_output position)
    dhw_start = pid_dhw * BLOCK_DHW
    dhw_offs = dhw_start + tl.arange(0, BLOCK_DHW)
    mask = dhw_offs < D_out * H_out * W_out

    # Decode 3D coordinates for output position
    d_out = dhw_offs // (H_out * W_out)
    h_out = (dhw_offs // W_out) % H_out
    w_out = dhw_offs % W_out

    # Compute the input position this maps to via reflection
    # Depth dimension
    Dm1 = D_in - 1
    D_period = 2 * Dm1 if Dm1 > 0 else 1
    x_d = d_out - pad_d0
    t_d = tl.abs(x_d)
    m_d = t_d % D_period
    d_idx = tl.where(m_d < D_in, m_d, D_period - m_d)

    # Height dimension
    Hm1 = H_in - 1
    H_period = 2 * Hm1 if Hm1 > 0 else 1
    x_h = h_out - pad_h0
    t_h = tl.abs(x_h)
    m_h = t_h % H_period
    h_idx = tl.where(m_h < H_in, m_h, H_period - m_h)

    # Width dimension
    Wm1 = W_in - 1
    W_period = 2 * Wm1 if Wm1 > 0 else 1
    x_w = w_out - pad_w0
    t_w = tl.abs(x_w)
    m_w = t_w % W_period
    w_idx = tl.where(m_w < W_in, m_w, W_period - m_w)

    # Load gradient at output position - cast to float32 for atomic add
    grad_offs = (
        pid_n * stride_grad_n
        + pid_c * stride_grad_c
        + d_out * stride_grad_d
        + h_out * stride_grad_h
        + w_out * stride_grad_w
    )
    grad_val = tl.load(grad_ptr + grad_offs, mask=mask, other=0.0).to(tl.float32)

    # Compute output position for grad_input
    out_offs = (
        pid_n * stride_out_n
        + pid_c * stride_out_c
        + d_idx * stride_out_d
        + h_idx * stride_out_h
        + w_idx * stride_out_w
    )

    # Atomically add float32 value to float32 output (without mask for bfloat16 compatibility)
    tl.atomic_add(out_ptr + out_offs, grad_val)


def reflection_pad3d_backward(grad_output, self, padding):
    """Compute gradient of reflection_pad3d forward pass.

    Args:
        grad_output: Gradient of the loss with respect to the output of reflection_pad3d.
                    Shape: (N, C, D + pad_d0 + pad_d1, H + pad_h0 + pad_h1, W + pad_w0 + pad_w1)
        self: Original input tensor before padding. Shape: (N, C, D, H, W)
        padding: Tuple of 6 ints (pad_d0, pad_d1, pad_h0, pad_h1, pad_w0, pad_w1)

    Returns:
        Gradient with respect to self. Shape: (N, C, D, H, W)
    """
    logger.debug("GEMS REFLECTION_PAD3D_BACKWARD")

    if isinstance(padding, int):
        pad_d0 = pad_d1 = pad_h0 = pad_h1 = pad_w0 = pad_w1 = padding
    else:
        pad_d0, pad_d1, pad_h0, pad_h1, pad_w0, pad_w1 = padding

    # Validate input
    if self.dim() != 5:
        raise ValueError("input must be a 5D tensor")

    N, C, D_in, H_in, W_in = self.shape
    D_out, H_out, W_out = (
        D_in + pad_d0 + pad_d1,
        H_in + pad_h0 + pad_h1,
        W_in + pad_w0 + pad_w1,
    )

    # Validate shapes
    expected_grad_shape = (N, C, D_out, H_out, W_out)
    if tuple(grad_output.shape) != expected_grad_shape:
        raise ValueError(
            f"grad_output has shape {tuple(grad_output.shape)}, expected {expected_grad_shape}"
        )

    # Handle empty padding case - just reshape
    if (
        pad_d0 == 0
        and pad_d1 == 0
        and pad_h0 == 0
        and pad_h1 == 0
        and pad_w0 == 0
        and pad_w1 == 0
    ):
        return grad_output.clone()

    grad_output = grad_output.contiguous()

    # For bfloat16, we need to accumulate in float32 and cast back
    # This is because tl.atomic_add doesn't support bfloat16 directly
    output_dtype = self.dtype
    if self.dtype in (torch.bfloat16,):
        out = torch.zeros(
            (N, C, D_in, H_in, W_in), device=self.device, dtype=torch.float32
        )
    else:
        out = torch.zeros_like(self)

    # Launch kernel with output-space parallelization
    # Grid: (num_dhw_blocks, N*C) where each block handles BLOCK_DHW output positions
    BLOCK_DHW = 256
    grid = (
        triton.cdiv(D_out * H_out * W_out, BLOCK_DHW),
        N * C,
    )

    reflection_pad3d_backward_kernel[grid](
        grad_output,
        out,
        N,
        C,
        D_in,
        H_in,
        W_in,
        D_out,
        H_out,
        W_out,
        pad_d0,
        pad_d1,
        pad_h0,
        pad_h1,
        pad_w0,
        pad_w1,
        *grad_output.stride(),
        *out.stride(),
        BLOCK_DHW=BLOCK_DHW,
    )

    # Cast back to original dtype if needed
    if output_dtype in (torch.bfloat16,):
        out = out.to(dtype=output_dtype)

    return out
