# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def slice_kernel_contiguous(
    input_ptr,
    output_ptr,
    input_offset,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Fast path for contiguous slices with step=1."""
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    data = tl.load(input_ptr + input_offset + offsets, mask=mask)
    tl.store(output_ptr + offsets, data, mask=mask)


@triton.jit
def slice_kernel_1d(
    input_ptr,
    output_ptr,
    start,
    step,
    input_stride_0,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Strided 1D slice kernel (handles step != 1)."""
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    in_idx = start + offsets * step
    data = tl.load(input_ptr + in_idx * input_stride_0, mask=mask)
    tl.store(output_ptr + offsets, data, mask=mask)


@triton.jit
def slice_kernel_2d(
    input_ptr,
    output_ptr,
    dim,
    start,
    step,
    input_stride_0,
    input_stride_1,
    output_size_0,
    output_size_1,
    BLOCK_SIZE: tl.constexpr,
):
    """Optimized 2D slice kernel."""
    pid_0 = tl.program_id(0)
    pid_1 = tl.program_id(1)

    out_idx_0 = pid_0
    out_idx_1_base = pid_1 * BLOCK_SIZE
    out_idx_1 = out_idx_1_base + tl.arange(0, BLOCK_SIZE)
    mask = out_idx_1 < output_size_1

    # Map to input coordinates
    in_idx_0 = tl.where(dim == 0, start + out_idx_0 * step, out_idx_0)
    in_idx_1 = tl.where(dim == 1, start + out_idx_1 * step, out_idx_1)

    input_offset = in_idx_0 * input_stride_0 + in_idx_1 * input_stride_1
    output_offset = out_idx_0 * output_size_1 + out_idx_1

    data = tl.load(input_ptr + input_offset, mask=mask, other=0.0)
    tl.store(output_ptr + output_offset, data, mask=mask)


@triton.jit
def slice_kernel_3d(
    input_ptr,
    output_ptr,
    dim,
    start,
    step,
    input_stride_0,
    input_stride_1,
    input_stride_2,
    output_size_1,
    output_size_2,
    BLOCK_SIZE: tl.constexpr,
):
    """Optimized 3D slice kernel."""
    pid_0 = tl.program_id(0)
    pid_1 = tl.program_id(1)
    pid_2_base = tl.program_id(2)

    out_idx_0 = pid_0
    out_idx_1 = pid_1
    out_idx_2_base = pid_2_base * BLOCK_SIZE
    out_idx_2 = out_idx_2_base + tl.arange(0, BLOCK_SIZE)
    mask = out_idx_2 < output_size_2

    # Map to input coordinates
    in_idx_0 = tl.where(dim == 0, start + out_idx_0 * step, out_idx_0)
    in_idx_1 = tl.where(dim == 1, start + out_idx_1 * step, out_idx_1)
    in_idx_2 = tl.where(dim == 2, start + out_idx_2 * step, out_idx_2)

    input_offset = (
        in_idx_0 * input_stride_0
        + in_idx_1 * input_stride_1
        + in_idx_2 * input_stride_2
    )
    output_offset = (
        out_idx_0 * (output_size_1 * output_size_2)
        + out_idx_1 * output_size_2
        + out_idx_2
    )

    data = tl.load(input_ptr + input_offset, mask=mask, other=0.0)
    tl.store(output_ptr + output_offset, data, mask=mask)


@triton.jit
def slice_kernel_4d(
    input_ptr,
    output_ptr,
    dim,
    start,
    step,
    input_stride_0,
    input_stride_1,
    input_stride_2,
    input_stride_3,
    output_size_0,
    output_size_1,
    output_size_2,
    output_size_3,
    BLOCK_SIZE: tl.constexpr,
):
    """Optimized 4D slice kernel using 3D grid (flatten first two dims)."""
    pid_01 = tl.program_id(0)  # Combined dimension 0 and 1
    pid_2 = tl.program_id(1)
    pid_3_base = tl.program_id(2)

    # Decompose combined dimension
    out_idx_0 = pid_01 // output_size_1
    out_idx_1 = pid_01 % output_size_1
    out_idx_2 = pid_2
    out_idx_3_base = pid_3_base * BLOCK_SIZE
    out_idx_3 = out_idx_3_base + tl.arange(0, BLOCK_SIZE)
    mask = out_idx_3 < output_size_3

    # Map to input coordinates
    in_idx_0 = tl.where(dim == 0, start + out_idx_0 * step, out_idx_0)
    in_idx_1 = tl.where(dim == 1, start + out_idx_1 * step, out_idx_1)
    in_idx_2 = tl.where(dim == 2, start + out_idx_2 * step, out_idx_2)
    in_idx_3 = tl.where(dim == 3, start + out_idx_3 * step, out_idx_3)

    input_offset = (
        in_idx_0 * input_stride_0
        + in_idx_1 * input_stride_1
        + in_idx_2 * input_stride_2
        + in_idx_3 * input_stride_3
    )
    output_offset = (
        out_idx_0 * (output_size_1 * output_size_2 * output_size_3)
        + out_idx_1 * (output_size_2 * output_size_3)
        + out_idx_2 * output_size_3
        + out_idx_3
    )

    data = tl.load(input_ptr + input_offset, mask=mask, other=0.0)
    tl.store(output_ptr + output_offset, data, mask=mask)


def slice(input_tensor, dim=0, start=None, end=None, step=1):
    logger.debug("GEMS SLICE")
    # ``aten::slice.Tensor`` is a view operation: the returned tensor shares
    # storage with the input.  The result is built as a zero-copy view via
    # ``torch.as_strided`` rather than an allocated copy.
    assert input_tensor.dtype not in (
        torch.bool,
        torch.complex64,
        torch.complex128,
    ), f"slice: unsupported dtype {input_tensor.dtype}"

    ndim = input_tensor.ndim
    dim = int(dim) % ndim if ndim > 0 else 0
    dim_size = int(input_tensor.size(dim))

    # ``start`` / ``end`` / ``step`` may be None, plain ints, SymInts or 0-dim
    # tensors.
    def _to_int(value, default):
        if value is None:
            return default
        if isinstance(value, torch.Tensor):
            value = value.item()
        return int(value)

    start = _to_int(start, 0)
    end = _to_int(end, dim_size)
    step = _to_int(step, 1)

    assert step != 0, "slice step cannot be zero"
    assert step > 0, "slice step must be positive"

    # Negative indices are interpreted relative to the dim size.
    if start < 0:
        start += dim_size
    if end < 0:
        end += dim_size

    # Clamp to the valid range.
    start = max(0, min(start, dim_size))
    end = max(0, min(end, dim_size))

    # Slice length for a positive step.
    slice_len = max(0, (end - start + step - 1) // step)

    size = list(input_tensor.shape)
    size[dim] = slice_len

    # Scale the stride along ``dim`` by ``step`` and advance the storage offset
    # by ``start`` (in units of the original element stride).
    strides = list(input_tensor.stride())
    strides[dim] = strides[dim] * step
    storage_offset = input_tensor.storage_offset() + start * input_tensor.stride(dim)

    return torch.as_strided(input_tensor, size, strides, storage_offset)
