# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)

# ndtri is the inverse of the standard normal CDF, which is exactly what
# libdevice exposes as normcdfinv. Using it directly is more accurate than
# composing sqrt(2) * erfinv(2p - 1): measured on H20 in float32 the former
# reaches a max absolute error of 2.9e-07 against the float64 reference while
# the latter reaches 1.3e-05.
_NORMCDFINV = tl_extra_shim.normcdfinv


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def special_ndtri_func(x):
    # The input dtype is kept as-is so that float64 dispatches to the double
    # precision libdevice variant. Measured on H20 against the float64
    # reference, the max absolute error is 2.9e-07 for float32 inputs and
    # 1.1e-15 for float64 inputs.
    return _NORMCDFINV(x)


# ndtri is only defined for single and double precision in PyTorch: both
# ndtri_cuda and ndtri_cpu raise NotImplementedError for Half and BFloat16.
# The same restriction is kept here so the operator matches the reference.
_SUPPORTED_DTYPES = (torch.float32, torch.float64)


def special_ndtri(self):
    logger.debug("GEMS SPECIAL_NDTRI")
    if self.dtype not in _SUPPORTED_DTYPES:
        raise NotImplementedError(
            f"\"ndtri\" not implemented for '{self.dtype}'; supported dtypes are "
            f"{_SUPPORTED_DTYPES}"
        )
    return special_ndtri_func(self)
