# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "INT_TO_FLOAT")])
@triton.jit
def special_bessel_y1_func(x):
    # bessel_y1 oscillates sharply near its zeros, so float32 truncation cannot
    # meet float64's rtol=1e-7. Route by input dtype: keep double precision for
    # float64, otherwise compute in float32.
    inp_dtype = x.type.element_ty
    if inp_dtype == tl.float64:
        return tl_extra_shim.y1(x.to(tl.float64)).to(x.dtype)
    return tl_extra_shim.y1(x.to(tl.float32)).to(x.dtype)


def special_bessel_y1(A):
    logger.debug("GEMS SPECIAL_BESSEL_Y1")
    return special_bessel_y1_func(A)
