# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


# Shared H_n(x) computation for degree n in [0, 9].
# Physicist's Hermite polynomial: H_0(x)=1, H_1(x)=2x,
# H_m(x) = 2*x*H_{m-1}(x) - 2*(m-1)*H_{m-2}(x).
# Computed in the input's own precision (float32/float64) using the same
# three-term recurrence as PyTorch to avoid precision loss and reduce the
# catastrophic cancellation of the expanded-polynomial form.
@triton.jit
def _hermite_Hn(x, n_int):
    two_x = 2.0 * x

    # H_0(x) = 1 (kept as a tensor in x's dtype so selection stays elementwise)
    h0 = 0.0 * x + 1.0
    # H_1(x) = 2*x
    h1 = two_x
    # H_m(x) = 2*x*H_{m-1}(x) - 2*(m-1)*H_{m-2}(x)
    h2 = two_x * h1 - 2.0 * h0
    h3 = two_x * h2 - 4.0 * h1
    h4 = two_x * h3 - 6.0 * h2
    h5 = two_x * h4 - 8.0 * h3
    h6 = two_x * h5 - 10.0 * h4
    h7 = two_x * h6 - 12.0 * h5
    h8 = two_x * h7 - 14.0 * h6
    h9 = two_x * h8 - 16.0 * h7

    # Select H_n based on padded-n value (n_int in [0, 9])
    result = h0
    result = tl.where(n_int == 1, h1, result)
    result = tl.where(n_int == 2, h2, result)
    result = tl.where(n_int == 3, h3, result)
    result = tl.where(n_int == 4, h4, result)
    result = tl.where(n_int == 5, h5, result)
    result = tl.where(n_int == 6, h6, result)
    result = tl.where(n_int == 7, h7, result)
    result = tl.where(n_int == 8, h8, result)
    result = tl.where(n_int == 9, h9, result)

    return result


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def hermite_polynomial_h_func(x, n):
    n_int = n.to(tl.int32)
    result = _hermite_Hn(x, n_int)
    return result.to(x.dtype)


def special_hermite_polynomial_h_tensor_tensor(x, n):
    logger.debug("GEMS SPECIAL_HERMITE_POLYNOMIAL_H")
    return hermite_polynomial_h_func(x, n)


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def hermite_polynomial_h_func_tensor_scalar(x, n):
    n_int = n.to(tl.int32)
    result = _hermite_Hn(x, n_int)
    return result.to(x.dtype)


def special_hermite_polynomial_h(x, n):
    logger.debug("GEMS SPECIAL_HERMITE_POLYNOMIAL_H")
    if x.dtype not in (torch.float32, torch.float64):
        raise ValueError(f"Unsupported dtype {x.dtype}")

    # Validate n is in supported range [0, 9]
    if isinstance(n, torch.Tensor):
        n_int = n.to(torch.int32)
        n_min = n_int.min().item()
        n_max = n_int.max().item()
        if n_min < 0 or n_max > 9:
            raise ValueError(
                f"special_hermite_polynomial_h only supports n in [0, 9], "
                f"got n in [{n_min}, {n_max}]"
            )
    elif isinstance(n, (int, float)):
        if int(n) < 0 or int(n) > 9:
            raise ValueError(
                f"special_hermite_polynomial_h only supports n in [0, 9], got n={n}"
            )

    if isinstance(x, torch.Tensor) and isinstance(n, torch.Tensor):
        return hermite_polynomial_h_func(x, n)
    elif isinstance(x, torch.Tensor):
        return hermite_polynomial_h_func_tensor_scalar(x, n)
    else:
        raise ValueError("First argument must be a tensor")
