# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _special_modified_bessel_i0_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(
        x_ptr + offsets,
        mask=mask,
        other=0.0,
    ).to(tl.float32)

    ax = tl.abs(x)
    use_small = ax <= 3.75

    # ---------------------------------------------------------
    # Small region: |x| <= 3.75
    # ---------------------------------------------------------
    z = ax * (1.0 / 3.75)
    y = z * z

    p_small_inner = tl.fma(y, 0.0045813, 0.0360768)
    p_small_inner = tl.fma(y, p_small_inner, 0.2659732)
    p_small_inner = tl.fma(y, p_small_inner, 1.2067492)
    p_small_inner = tl.fma(y, p_small_inner, 3.0899424)
    p_small_inner = tl.fma(y, p_small_inner, 3.5156229)
    res_small = tl.fma(y, p_small_inner, 1.0)

    # ---------------------------------------------------------
    # Large region: |x| > 3.75
    #
    # tl.where does not short-circuit, so use a safe denominator
    # for lanes that will eventually select the small branch.
    # ---------------------------------------------------------
    safe_ax = tl.where(use_small, 3.75, ax)
    yb = 3.75 / safe_ax

    p_big_inner = tl.fma(yb, 0.00392377, -0.01647633)
    p_big_inner = tl.fma(yb, p_big_inner, 0.02635537)
    p_big_inner = tl.fma(yb, p_big_inner, -0.02057706)
    p_big_inner = tl.fma(yb, p_big_inner, 0.00916281)
    p_big_inner = tl.fma(yb, p_big_inner, -0.00157565)
    p_big_inner = tl.fma(yb, p_big_inner, 0.00225319)
    p_big_inner = tl.fma(yb, p_big_inner, 0.01328592)
    p_big = tl.fma(yb, p_big_inner, 0.39894228)

    res_big = tl.exp(safe_ax) * p_big * tl.rsqrt(safe_ax)

    result = tl.where(use_small, res_small, res_big)

    tl.store(out_ptr + offsets, result, mask=mask)


def _launch_special_modified_bessel_i0(out: torch.Tensor, x: torch.Tensor):
    assert x.is_cuda and out.is_cuda, "Input and output must be CUDA tensors"
    assert (
        out.numel() == x.numel()
    ), "Input and output must have the same number of elements"
    assert out.device == x.device, "Input and output must be on the same device"

    x_in = x
    out_in = out

    # Ensure floating point compute
    if not x_in.is_floating_point():
        x_in = x_in.to(torch.get_default_dtype())

    # Cast input to match the desired output dtype if needed
    # (Compute will be done in fp32 inside kernel; store will cast to out dtype)
    if x_in.dtype != out_in.dtype:
        x_in = x_in.to(out_in.dtype)

    x_contig = x_in.contiguous()
    out_was_noncontig = not out_in.is_contiguous()
    out_contig = out_in.contiguous() if out_was_noncontig else out_in

    n_elements = out_contig.numel()
    # BLOCK_SIZE=1024 balances occupancy and register pressure on H20
    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    _special_modified_bessel_i0_kernel[grid](
        x_contig, out_contig, n_elements, BLOCK_SIZE=BLOCK_SIZE
    )

    if out_was_noncontig:
        out_in.copy_(out_contig)
    return out_in


def special_modified_bessel_i0(x: torch.Tensor):
    logger.debug("GEMS SPECIAL_MODIFIED_BESSEL_I0")
    if not x.is_cuda:
        raise ValueError(
            "special_modified_bessel_i0: input tensor must be on CUDA device"
        )
    # Result dtype follows PyTorch's floating type behavior
    out_dtype = x.dtype if x.is_floating_point() else torch.get_default_dtype()
    out = torch.empty_like(x.to(dtype=out_dtype), dtype=out_dtype, device=x.device)
    _launch_special_modified_bessel_i0(out, x)
    return out


def special_modified_bessel_i0_out(x: torch.Tensor, out: torch.Tensor):
    logger.debug("GEMS SPECIAL_MODIFIED_BESSEL_I0_OUT")
    if not (x.is_cuda and out.is_cuda):
        raise ValueError(
            "special_modified_bessel_i0_out: input and output tensors must be on CUDA device"
        )
    if not out.is_floating_point():
        raise TypeError(
            "special_modified_bessel_i0_out: output tensor must be a floating point type"
        )
    if x.numel() != out.numel():
        raise ValueError(
            "special_modified_bessel_i0_out: input and output must have the same number of elements"
        )
    _launch_special_modified_bessel_i0(out, x)
    return out
