# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def ndtr_func(x):
    # ndtr(x) = 0.5 * (1 + erf(x / sqrt(2)))
    # Compute in float32 for precision, then cast back
    x_f32 = x.to(tl.float32)
    SQRT_2 = 1.4142135623730951  # sqrt(2)
    result = 0.5 * (1.0 + tl.math.erf(x_f32 / SQRT_2))
    return result.to(x.dtype)


def special_ndtr(A):
    logger.debug("GEMS SPECIAL_NDTR")
    return ndtr_func(A)
