# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from flag_gems.ops.igammac_ import igammac_func

logger = logging.getLogger(__name__)


def special_gammaincc(self, other):
    """Computes the regularized upper incomplete gamma function Q(a, x).

    Delegates to the existing igammac kernel; `special_gammaincc` is the
    out-of-place counterpart of `igammac_`, so the shared pointwise kernel is
    invoked without an `out0` argument.
    """
    logger.debug("GEMS SPECIAL_GAMMAINCC")
    # The igammac kernel only supports floating point dtypes; igammac_cuda does
    # not support Half/BFloat16 either. Reject them explicitly.
    supported_dtypes = (torch.float32, torch.float64)
    if self.dtype not in supported_dtypes or other.dtype not in supported_dtypes:
        raise RuntimeError(
            f"special_gammaincc Triton kernel supports dtypes {supported_dtypes}, "
            f"but got self.dtype={self.dtype}, other.dtype={other.dtype}"
        )
    return igammac_func(self, other)
