# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List, Union

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def split_copy_kernel(
    input_ptr,
    output_ptr,
    num_elements: tl.constexpr,
    dim_size_input: tl.constexpr,
    dim_size_output: tl.constexpr,
    split_dim: tl.constexpr,
    dim_prod_pre: tl.constexpr,
    dim_prod_post: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Kernel to copy a split from input to output tensor."""
    pid = tl.program_id(0)
    offset = pid * BLOCK_SIZE
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = offset + offsets < num_elements

    # Compute the linear index
    idx = offset + offsets

    # Convert linear index to multi-dimensional index
    # For the split dimension, we use the output dimension size
    # For other dimensions, we use the input dimension sizes

    # Linear index = pre_idx * dim_size_input * post_dim + split_idx * post_dim + post_idx
    # But we need to map to the correct position in the input tensor

    # Compute indices for each dimension
    pre_idx = idx // (dim_size_output * dim_prod_post)
    split_idx = (idx // dim_prod_post) % dim_size_output
    post_idx = idx % dim_prod_post

    # Compute input index
    # The split dimension offset is already accounted for in the output tensor layout
    input_idx = (
        pre_idx * dim_size_input * dim_prod_post + split_idx * dim_prod_post + post_idx
    )

    # Load from input and store to output
    data = tl.load(input_ptr + input_idx, mask=mask)
    tl.store(output_ptr + idx, data, mask=mask)


def tensor_split(
    input: torch.Tensor,
    indices_or_sections: Union[int, List[int], torch.Tensor],
    dim: int = 0,
) -> List[torch.Tensor]:
    """
    Split a tensor into multiple sub-tensors along a given dimension.

    This implementation uses Triton kernels to copy data to the output tensors.
    Note: Unlike torch.tensor_split which returns views, this returns copies.
    """
    logger.debug("GEMS tensor_split")

    # Validate input
    if not isinstance(input, torch.Tensor):
        raise TypeError(f"Expected tensor, got {type(input)}")

    # Handle empty tensor
    if input.numel() == 0:
        # Return list of empty tensors with appropriate shapes
        if isinstance(indices_or_sections, int):
            n = indices_or_sections
        else:
            n = (
                len(indices_or_sections) + 1
                if isinstance(indices_or_sections, (list, tuple))
                else 1
            )
        output_tensors = []
        for i in range(n):
            output_shape = list(input.shape)
            output_shape[dim] = 0
            output_tensors.append(
                torch.empty(output_shape, dtype=input.dtype, device=input.device)
            )
        return output_tensors

    # Normalize dim
    dim = dim % input.ndim
    dim_size = input.shape[dim]

    # Handle indices_or_sections
    if isinstance(indices_or_sections, int):
        # Split into n sections
        n = indices_or_sections
        if n <= 0:
            raise ValueError(f"indices_or_sections must be positive, got {n}")

        # Calculate split sizes
        base_size = dim_size // n
        remainder = dim_size % n

        split_sizes = []
        for i in range(n):
            if i < remainder:
                split_sizes.append(base_size + 1)
            else:
                split_sizes.append(base_size)

    elif isinstance(indices_or_sections, (list, tuple)):
        # Split at specific indices
        indices = list(indices_or_sections)
        if not all(isinstance(i, int) for i in indices):
            raise TypeError("All elements in indices_or_sections must be integers")

        # Validate indices are sorted and in range
        if len(indices) > 0:
            if indices[0] < 0 or indices[-1] > dim_size:
                raise ValueError(
                    f"indices_or_sections must be in range [0, {dim_size}]"
                )
            if any(indices[i] >= indices[i + 1] for i in range(len(indices) - 1)):
                raise ValueError("indices_or_sections must be strictly increasing")

        # Calculate split sizes
        prev_idx = 0
        split_sizes = []
        for idx in indices:
            split_sizes.append(idx - prev_idx)
            prev_idx = idx
        split_sizes.append(dim_size - prev_idx)

    elif isinstance(indices_or_sections, torch.Tensor):
        # Handle tensor indices (must be on CPU, 0-d or 1-d)
        indices_or_sections = indices_or_sections.cpu()
        if indices_or_sections.ndim > 1:
            raise ValueError("indices_or_sections tensor must be 0-d or 1-d")

        if indices_or_sections.ndim == 0:
            # Single integer value
            return tensor_split(input, indices_or_sections.item(), dim)
        else:
            # List of indices
            indices = indices_or_sections.tolist()
            return tensor_split(input, indices, dim)

    else:
        raise TypeError(
            f"indices_or_sections must be int, list, tuple, or tensor, got {type(indices_or_sections)}"
        )

    # Create output tensors using Triton kernel
    output_tensors = []

    # Pre-compute dimension products
    dim_prod_post = 1
    for d in range(dim + 1, input.ndim):
        dim_prod_post *= input.shape[d]

    dim_prod_pre = 1
    for d in range(dim):
        dim_prod_pre *= input.shape[d]

    # Process each split
    current_dim_idx = 0
    # Standard block size for element-wise copy kernel
    BLOCK_SIZE = 1024

    for split_size in split_sizes:
        # Create output tensor
        output_shape = list(input.shape)
        output_shape[dim] = split_size
        output_tensor = torch.empty(
            output_shape, dtype=input.dtype, device=input.device
        )

        if split_size == 0:
            # Empty tensor
            output_tensors.append(output_tensor)
            continue

        # Calculate total elements in this split
        total_elements = 1
        for i, s in enumerate(output_shape):
            total_elements *= s

        # Ensure input is contiguous for correct indexing
        input_contiguous = input.contiguous()

        # Launch Triton kernel
        grid = (triton.cdiv(total_elements, BLOCK_SIZE),)
        split_copy_kernel[grid](
            input_contiguous,
            output_tensor,
            total_elements,
            dim_size,  # dim_size_input
            split_size,  # dim_size_output
            dim,  # split_dim
            dim_prod_pre,
            dim_prod_post,
            BLOCK_SIZE=BLOCK_SIZE,
        )

        output_tensors.append(output_tensor)
        current_dim_idx += split_size

    return output_tensors
