# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2026, Yuanzhu Li
# Copyright 2026, BAAI (Beijing Academy of Artificial Intelligence)
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def trunc_func(x):
    x_fp32 = x.to(tl.float32)
    return tl_extra_shim.trunc(x_fp32).to(x.dtype)


def trunc(A):
    logger.debug("GEMS TRUNC")
    return trunc_func(A)


def trunc_(A):
    logger.debug("GEMS TRUNC_")
    trunc_func(A, out0=A)
    return A
