# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List, Union

import torch

logger = logging.getLogger(__name__)


def _normalize_split_sizes(split_sizes):
    if isinstance(split_sizes, torch.Tensor):
        split_sizes = split_sizes.tolist()

    if hasattr(split_sizes, "__iter__"):
        split_sizes = list(split_sizes)

    return [int(size) for size in split_sizes]


def _normalize_dim(inp, dim):
    assert dim >= -inp.ndim and dim < inp.ndim, "Invalid dim"
    return dim % inp.ndim


def unsafe_split_with_sizes(
    self: torch.Tensor,
    split_sizes: Union[List[int], torch.Tensor],
    dim: int = 0,
) -> List[torch.Tensor]:
    """Splits a tensor into sub-tensors along a given dimension,
    where each split has a specified size. Returns views (no copy).

    This is the "unsafe" variant of split_with_sizes that returns views
    into the original tensor without performing safety checks.
    """
    logger.debug("GEMS UNSAFE_SPLIT_WITH_SIZES")

    dim = _normalize_dim(self, dim)
    split_sizes = _normalize_split_sizes(split_sizes)

    split_sum = sum(split_sizes)
    assert split_sum == self.shape[dim], "Invalid split_sizes"

    result = []
    start = 0
    for size in split_sizes:
        # Use narrow to create a view into the original tensor
        out = torch.narrow(self, dim, start, size)
        result.append(out)
        start += size

    return result
