# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import Optional, Tuple

import torch
import triton
import triton.language as tl

from flag_gems.runtime import device as runtime_device
from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def upsample_trilinear3d_kernel(
    output_ptr,
    input_ptr,
    NC,
    OD,
    OH,
    OW,
    ID,
    IH,
    IW,
    scale_d,
    scale_h,
    scale_w,
    bias_d,
    bias_h,
    bias_w,
    BLOCK_SIZE: tl.constexpr,
):
    pid_nc = tl.program_id(0)
    pid_spatial = tl.program_id(1)

    idx = pid_spatial * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    total_spatial = OD * OH * OW
    mask = idx < total_spatial

    # Compute od, oh, ow from flat index
    ow = idx % OW
    oh = (idx // OW) % OH
    od = idx // (OW * OH)

    # Compute source coordinates
    src_d = od.to(tl.float32) * scale_d + bias_d
    src_h = oh.to(tl.float32) * scale_h + bias_h
    src_w = ow.to(tl.float32) * scale_w + bias_w

    # Clamp to valid range
    src_d = tl.maximum(0.0, tl.minimum(src_d, ID - 1.0))
    src_h = tl.maximum(0.0, tl.minimum(src_h, IH - 1.0))
    src_w = tl.maximum(0.0, tl.minimum(src_w, IW - 1.0))

    # Compute lower and upper indices for trilinear interpolation
    id0 = tl.floor(src_d).to(tl.int32)
    ih0 = tl.floor(src_h).to(tl.int32)
    iw0 = tl.floor(src_w).to(tl.int32)

    id1 = tl.minimum(id0 + 1, ID - 1)
    ih1 = tl.minimum(ih0 + 1, IH - 1)
    iw1 = tl.minimum(iw0 + 1, IW - 1)

    # Interpolation weights
    td = src_d - id0.to(tl.float32)
    th = src_h - ih0.to(tl.float32)
    tw = src_w - iw0.to(tl.float32)

    wd0 = 1.0 - td
    wd1 = td
    wh0 = 1.0 - th
    wh1 = th
    ww0 = 1.0 - tw
    ww1 = tw

    # Compute input strides for flattened (NC, ID, IH, IW) layout
    d_stride_in = IH * IW
    h_stride_in = IW

    # Base offset for the batch and channel
    in_offset_base = pid_nc * ID * IH * IW

    # Load 8 corners of the cube
    offset_000 = in_offset_base + id0 * d_stride_in + ih0 * h_stride_in + iw0
    offset_001 = in_offset_base + id0 * d_stride_in + ih0 * h_stride_in + iw1
    offset_010 = in_offset_base + id0 * d_stride_in + ih1 * h_stride_in + iw0
    offset_011 = in_offset_base + id0 * d_stride_in + ih1 * h_stride_in + iw1
    offset_100 = in_offset_base + id1 * d_stride_in + ih0 * h_stride_in + iw0
    offset_101 = in_offset_base + id1 * d_stride_in + ih0 * h_stride_in + iw1
    offset_110 = in_offset_base + id1 * d_stride_in + ih1 * h_stride_in + iw0
    offset_111 = in_offset_base + id1 * d_stride_in + ih1 * h_stride_in + iw1

    x000 = tl.load(input_ptr + offset_000, mask=mask)
    x001 = tl.load(input_ptr + offset_001, mask=mask)
    x010 = tl.load(input_ptr + offset_010, mask=mask)
    x011 = tl.load(input_ptr + offset_011, mask=mask)
    x100 = tl.load(input_ptr + offset_100, mask=mask)
    x101 = tl.load(input_ptr + offset_101, mask=mask)
    x110 = tl.load(input_ptr + offset_110, mask=mask)
    x111 = tl.load(input_ptr + offset_111, mask=mask)

    # Convert to float32 for interpolation
    x000 = x000.to(tl.float32)
    x001 = x001.to(tl.float32)
    x010 = x010.to(tl.float32)
    x011 = x011.to(tl.float32)
    x100 = x100.to(tl.float32)
    x101 = x101.to(tl.float32)
    x110 = x110.to(tl.float32)
    x111 = x111.to(tl.float32)

    # Trilinear interpolation
    # First interpolate along depth
    x00 = wd0 * x000 + wd1 * x100
    x01 = wd0 * x001 + wd1 * x101
    x10 = wd0 * x010 + wd1 * x110
    x11 = wd0 * x011 + wd1 * x111

    # Then interpolate along height
    x0 = wh0 * x00 + wh1 * x10
    x1 = wh0 * x01 + wh1 * x11

    # Finally interpolate along width
    out = ww0 * x0 + ww1 * x1

    out = out.to(x000.dtype)

    out_offset = pid_nc * total_spatial + idx
    tl.store(output_ptr + out_offset, out, mask=mask)


def upsample_trilinear3d(
    self: torch.Tensor,
    output_size: Tuple[int, int, int],
    align_corners: bool,
    scales_d: Optional[float] = None,
    scales_h: Optional[float] = None,
    scales_w: Optional[float] = None,
) -> torch.Tensor:
    logger.debug("GEMS UPSAMPLE_TRILINEAR3D")
    assert (
        self.device.type == runtime_device.name
    ), f"Expected device {runtime_device.name}, got {self.device.type}"
    assert self.ndim == 5, f"Input must be 5D (NCDHW), got {self.ndim}D"

    N, C, ID, IH, IW = self.shape
    OD, OH, OW = output_size
    NC = N * C

    def calculate_scale_and_bias(in_sz, out_sz, scale):
        if align_corners:
            if out_sz > 1:
                scale_val = (in_sz - 1.0) / (out_sz - 1.0)
            else:
                scale_val = 0.0
            bias_val = 0.0
        else:
            if scale is not None:
                real_scale = 1.0 / scale
            else:
                real_scale = in_sz / out_sz

            scale_val = real_scale
            bias_val = 0.5 * real_scale - 0.5

        return scale_val, bias_val

    scale_d, bias_d = calculate_scale_and_bias(ID, OD, scales_d)
    scale_h, bias_h = calculate_scale_and_bias(IH, OH, scales_h)
    scale_w, bias_w = calculate_scale_and_bias(IW, OW, scales_w)

    # Reshape input to (NC, ID, IH, IW) and output to (NC, OD, OH, OW)
    inp = self.reshape(NC, ID, IH, IW).contiguous()
    out = torch.empty((NC, OD, OH, OW), device=self.device, dtype=self.dtype)

    if out.numel() == 0:
        return out.view(N, C, OD, OH, OW)

    total_spatial = OD * OH * OW
    grid = (NC, triton.cdiv(total_spatial, 256))

    with torch_device_fn.device(self.device):
        upsample_trilinear3d_kernel[grid](
            out,
            inp,
            NC,
            OD,
            OH,
            OW,
            ID,
            IH,
            IW,
            scale_d,
            scale_h,
            scale_w,
            bias_d,
            bias_h,
            bias_w,
            # 256 threads per block balances occupancy for typical 3D upsampling sizes
            BLOCK_SIZE=256,
        )

    return out.view(N, C, OD, OH, OW)
