name: cpp-ops

permissions:
  contents: read

on:
  workflow_call:

jobs:
  test:
    runs-on: h20
    steps:
      - id: checkout-attempt-1
        uses: actions/checkout@v6
        continue-on-error: true
      - id: sleep-1
        if: steps.checkout-attempt-1.outcome == 'failure'
        shell: bash
        run: sleep 30s

      - id: checkout-attempt-2
        if: steps.checkout-attempt-1.outcome == 'failure'
        uses: actions/checkout@v6
        continue-on-error: true
      - id: sleep-2
        if: steps.checkout-attempt-2.outcome == 'failure'
        shell: bash
        run: sleep 30s

      - id: checkout-attempt-3
        if: steps.checkout-attempt-2.outcome == 'failure'
        uses: actions/checkout@v6
      - shell: bash
        run: |
          export PATH="/home/secure/.pyenv/bin:/usr/local/cuda/bin:$PATH"
          eval "$(pyenv init -)"
          export CMAKE_ARGS="-DFLAGGEMS_BUILD_C_EXTENSIONS=ON -DCMAKE_BUILD_TYPE=Release"
          pip install -v -e . --no-build-isolation
      - shell: bash
        run: |
          export PATH="/home/secure/.pyenv/bin:/usr/local/cuda/bin:$PATH"
          eval "$(pyenv init -)"
          cd build/cpython-*/ctests
          export FLAGGEMS_SOURCE_DIR=$(python -c "import os;import flag_gems;print(os.path.dirname(flag_gems.__file__))")
          ctest -V
