name: Sync docs branch
on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-attempt-1
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          ref: gh-pages
          submodules: recursive
          fetch-depth: 0
        continue-on-error: true
      - id: sleep-1
        if: steps.checkout-attempt-1.outcome == 'failure'
        shell: bash
        run: sleep 30s

      - id: checkout-attempt-2
        if: steps.checkout-attempt-1.outcome == 'failure'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          ref: gh-pages
          submodules: recursive
          fetch-depth: 0
        continue-on-error: true
      - id: sleep-2
        if: steps.checkout-attempt-2.outcome == 'failure'
        shell: bash
        run: sleep 30s

      - id: checkout-attempt-3
        if: steps.checkout-attempt-2.outcome == 'failure'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          ref: gh-pages
          submodules: recursive
          fetch-depth: 0

      - id: rebase
        run: |
          git rebase master
          git push -u origin gh-pages -f
